### ISSUE TITLE
Interactive Debugging Capability

### ISSUE THREAD

**Issue by dlanz** [codefori/vscode-ibmi#1073]
**Is your feature request related to a problem? Please describe.**
I'm able to debug batch jobs from within VSCode for IBM i which is great! But it be nice to also be able to debug interactive jobs somehow.

**Describe the solution you'd like**
I'm not sure the best way to achieve this, but perhaps similar functionality as in RDi using STRSRVJOB's? Or potentially tn5052 with the IBM i session directly in VSCode for IBM i. Though, I'm probably more inclined to favor the STRSRVJOB method as I believe Kerberos authentication support would be more likely.

**Describe alternatives you've considered**
Any other options for debugging interactive jobs from within VSCode for IBM i. Really anything that helps me avoid using SEU.

**Comment by worksofliam** [comment]
@cwbuck Yes, interactive debugging and SEP is coming. It's out of my control at the moment as someone else at IBM is working on it, and I just add the integration when it's released.
