### ISSUE TITLE
`IBM i: Go to file...` enhancement

### ISSUE THREAD

**Issue by m-tyler** [codefori/vscode-ibmi#1165]
This has been bothering me for a few releases.  The dialog box that appears when the `Go to File` command is initiated, wants to help me by finding matching members to open.  This is great and does help except it slows when it attempts to create the entry that matches exactly what I am typing.  But for some reason, there is a delay in generating the search text as the first line item.   It finds what I assume are cached entries from the Object Browser, prior opens, etc, and shows them in the list.  It seems if the exact search string is going to make it into the list it should appear right away or if the delay is intentional, at the bottom of the list.

What appears as I type up to a certain point.
![image](https://user-images.githubusercontent.com/1353665/227356121-c3ef402c-171a-4958-88dc-8a6b38eaa817.png)

After a moment I then see examples of the matches it finds.
![image](https://user-images.githubusercontent.com/1353665/227356290-62fc7325-4f1d-455b-9513-221e7915946c.png)

My issue is that the delay in creating the list with the (first) item that matches the search text I type it takes longer than I expect it should.  Many times I see the list without the search text, and move to click on the item I want only to have the list redrawn and the item I want down one, causing me to click on the wrong item.

**Comment by worksofliam** [comment]
@m-tyler Go to File has changed a lot in newer releases by @chrjorgensen. I will close this I believe it has covered bits you mentioned, but you're welcome to reopen or create a new issue.
