### ISSUE TITLE
Error on IBM i Debug

### ISSUE THREAD

**Issue by viruslogic** [codefori/vscode-ibmi#1203]
### Discussed in https://github.com/orgs/halcyon-tech/discussions/1202

<div type='discussions-op-text'>

<sup>Originally posted by **viruslogic** March 30, 2023</sup>
Hi,

My name is Marcos and I'm an AS400 developer from Spain. I've been using all the necessary extensions to develop from VS Code for a long time and I'm excited about it.

Recently I read the news that an extension was available to debug from VS Code.  I've been following all the installation steps: PTFs, Certificates, Services, etc. 

The thing is that when I go to start the debug I get an error and I don't know what to do.

The message I get is: "You are not authorised to program IRPG301 in library IDEA. 

![image](https://user-images.githubusercontent.com/10233590/228839665-a64ca895-dcd0-4723-9916-addefeb1a441.png)

The problem is that the source is in one library and the object is in another. If I try to run debug to start from the library where the object is, it still doesn't work. 

But if I copy the object to the library where the source is, it works.

Can someone give me a hand? 

Thanks!</div>

**Comment by viruslogic** [comment]
Thank you for closing the discussion. I saw that an issue could be created from the discussion and that's why it was in two different places.

Sorry for the inconvenience.

**Comment by mkwan01** [comment]
We do not support the scenario where program object and source are located in different libraries at the moment. This scenario may work in the future if we allow the user to add a new source lookup path. This enhancement has other dependencies and it is currently not in our plan yet.

**Comment by viruslogic** [comment]
Thank you for the reply. I solved it with a work around. The compilation process is done with a cl that compiles both in the library where the objects have to be and in the source library.

But I think it is an interesting improvement. It is not the first client where the sources are not in the same library as the objects.

**Comment by mkwan01** [comment]
> Does the debugger support source embedded in the program object? Like STRDBG does?
Yes, this is supported.

> Does the debugger support debug encryption key (keyword DBGENCKEY on the CRT-command)?
This is not supported yet. We have an RFE for this feature. We can give it a higher priority in the future TODO list, since users ask for this feature.
