### ISSUE TITLE
Problem tab error with IASP and local deployment

### ISSUE THREAD

**Issue by pabloto** [codefori/vscode-ibmi#1257]
Hi, 

I'm working in local, I've an IASP on my IBM i, when I compile a program, if I go into problem tab and click on an error it opens a new tab with prefix the IASP name, and obviously it can't find it, I record a video to better explain my problem:

![problem tab](https://user-images.githubusercontent.com/9719313/234540992-296b93fe-d199-4b8a-9400-f4d9530070e3.gif)

this problem occurs from one of the last code for i extension update, now I'm at v1.8.0.

Let me know if you need more info.

Many thanks

**Comment by worksofliam** [comment]
@pabloto Is there an iASP defined in the connection settings?

**Comment by worksofliam** [comment]
A video would be good. Thanks!

**Comment by pabloto** [comment]
> A video would be good. Thanks!

Can't you the video of my issue?

**Comment by pabloto** [comment]
> @pabloto Is there an iASP defined in the connection settings?

No. There isn't

**Comment by worksofliam** [comment]
@pabloto Your gif doesn't play for me the whole way through. Any chance you can provide an mp4 instead?

**Comment by pabloto** [comment]
Hi @worksofliam , 

Any news about it?

Thank you

**Comment by worksofliam** [comment]
@pabloto I am just getting around to this. Do you have an ASP defined in your connection settings?

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after you do the compile and the error happens.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by pabloto** [comment]
> @pabloto I am just getting around to this. Do you have an ASP defined in your connection settings?

No.

<img width="1067" alt="image" src="https://github.com/halcyon-tech/vscode-ibmi/assets/9719313/cce04a72-a94e-4a33-8bc3-4e9c9daa921d">

but it doesn't matter if i set the value and reconnect it behaves the same way

**Comment by worksofliam** [comment]
@pabloto Any chance you can share the generated EVFEVENT file after the compile? Usually exists in `$YOURLIB/EVFEVENT/$OBJNAME`.

**Comment by pabloto** [comment]
I clear the output, and compile my program missing one semicolon and open the error from problem.

> Please share the contents of your Code for IBM i output channel after you do the compile and the error happens.
> 
> <img alt="image" width="939" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

[codeforioutput.txt](https://github.com/halcyon-tech/vscode-ibmi/files/11488703/codeforioutput.txt)

**Comment by pabloto** [comment]
> @pabloto Any chance you can share the generated EVFEVENT file after the compile? Usually exists in `$YOURLIB/EVFEVENT/$OBJNAME`.

[testgenrsa.txt](https://github.com/halcyon-tech/vscode-ibmi/files/11488814/testgenrsa.txt)

**Comment by worksofliam** [comment]
@pabloto After deploying some code, can you please share the output of the 'IBM i Deployment' tab?

<img width="1057" alt="image" src="https://github.com/halcyon-tech/vscode-ibmi/assets/3708366/52cf99e0-c7b4-4953-8bd0-717322d4b07e">

I see in the error log the path is pointing to `/DIRECTA1/source/utility/./JSonWebToken/qrpglesrc/testgenrsa.sqlrpgle`, and I need to understand where your files are being uploaded to

**Comment by pabloto** [comment]
Here's the deployment tab:
`
UPLOADING: /Users/paolosalvatore/gitlab/utility/.vscode/launch.json -> /source/utility/.vscode/launch.json
UPLOADING: /Users/paolosalvatore/gitlab/utility/JSonWebToken/qfdssrc/ujwtsec0f.sql -> /source/utility/JSonWebToken/qfdssrc/ujwtsec0f.sql
UPLOADING: /Users/paolosalvatore/gitlab/utility/JSonWebToken/qrpgleref/ujwtsrvpgm.rpgleinc -> /source/utility/JSonWebToken/qrpgleref/ujwtsrvpgm.rpgleinc
UPLOADING: /Users/paolosalvatore/gitlab/utility/JSonWebToken/qrpglesrc/testcrtkey.rpgle -> /source/utility/JSonWebToken/qrpglesrc/testcrtkey.rpgle
UPLOADING: /Users/paolosalvatore/gitlab/utility/JSonWebToken/qrpglesrc/testgenrsa.sqlrpgle -> /source/utility/JSonWebToken/qrpglesrc/testgenrsa.sqlrpgle
UPLOADING: /Users/paolosalvatore/gitlab/utility/JSonWebToken/qrpglesrc/testjwt.rpgle -> /source/utility/JSonWebToken/qrpglesrc/testjwt.rpgle
UPLOADING: /Users/paolosalvatore/gitlab/utility/JSonWebToken/qrpglesrc/ujwt01r.sqlrpgle -> /source/utility/JSonWebToken/qrpglesrc/ujwt01r.sqlrpgle
UPLOADING: /Users/paolosalvatore/gitlab/utility/makefile -> /source/utility/makefile
Deployment finished.

`

**Comment by pabloto** [comment]
Any news about it? Thank you

**Comment by worksofliam** [comment]
@pabloto Yep. Small follow up for you:

* Your deployment directory is set to `/source/utility/` (or something similar)
* RPG compiler is referring to `/DIRECTA1/source/utility` because it belongs in an ASP.

This is expected behaviour from the RPG compiler. At initial glance, we can only add workaround. Have you considered setting your deploy directory to `/DIRECTA1/source/utility` instead for the time being?

**Comment by pabloto** [comment]
On Monday I will try, but before the latest updates it worked.

I'll give you a feedback 

Thanks

**Comment by worksofliam** [comment]
@pabloto let me know what version it worked on and I will check the relevant changes.

**Comment by pabloto** [comment]
> @pabloto let me know what version it worked on and I will check the relevant changes.

Hi, 

I tried to install some previous version, but it let me go back only 3 or 4 versions, before It get me an error. 

Putting the deploy directory with the /Iasp/ before the directory it works. 

For the moment thank you
