### ISSUE TITLE
Ability to set the default deploy option

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-ibmi#1381]
Chosen from the connection settings

**Comment by markhull1990** [comment]
Hello!

I'm looking to make this my first contribution (I'm new to JS and TS). I've added a "Default Deployment Location" in the connection settings on the features tab, but I'm struggling to come up with the logic of how it should behave in Deployment.ts.  Does anyone have any thoughts on how best to implement this?

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/137716546/6b7c5b36-6d6b-48b8-b92d-f1d891cf1bdf)

**Comment by worksofliam** [comment]
Hey mark

We are looking for 'default deploy **option**', not location 😄 

Ideally would be a dropdown with 6 options, the first being 'no default' and the remaining items being the options available when selecting which deploy method to use.

Also, I think this belongs in the Source Code tab.

Hope this helps!
