### ISSUE TITLE
Move CL runner logic to new extension

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-ibmi#1387]
And also add a way to run an enter CL file without compiling - e.g. one command at a time as requested by @edmundreinhardt

**Comment by sebjulliand** [comment]
@edmundreinhardt what would be the use case for running a whole CL file?

**Comment by edmundreinhardt** [comment]
> @edmundreinhardt what would be the use case for running a whole CL file?

@sebjulliand 
Hi Seb, both Merlin and ARCAD pomote the idea of pseudo source. Ie. that the CL commands to build a MSFG or DTAATA etc are all stored in IFS streamfiles with the corresponding file extension i.e. .MSGF and .DTAARA.
Inteliigent build tools like ARCAD and BOB can   immediately infer the purpose of these files containing CL command and run those CL command to create the corresponding QSYS object.
The idea is that we can compile RPG and SQL files from the active editor but we cannot do so with these CL pseudo-source files.
So we would like to add this ability for the developer using Code 4 IBM i

**Comment by sebjulliand** [comment]
Understood 😊 Thanks @edmundreinhardt

**Comment by worksofliam** [comment]
Could we just not have an action that compiles the object and then runs it?

**Comment by chrjorgensen** [comment]
> Could we just not have an action that compiles the object and then runs it?

I agree - having full CL functionality (e.g. variables, conditionals, error monitoring) via the CL compiler is better than running all CL statements one at a time. This would allow more intelligent builds.

But the compiled CL program should have a temporary name, since it could conflict with "real" programs having the same name as the object intended to be created - table and program can have the same name. Or it should be compiled to the temp library - don't know which's best...

**Comment by worksofliam** [comment]
I have been working with @sebjulliand today and some decisions have been made:

* we are not going to build a new extension for pseudo source runner officially right now. Maybe if we get bored we might, but we already have tons to do.
* I am going move the CL runner logic to the CL extension. I think it makes sense there, plus we can use the parser there instead of the hack we have i think.
* we are going to work on adding a way to the FS (file system) extension (not yet released) to generate the CL command that was used to create the chosen object.

**Comment by worksofliam** [comment]
* Also consider moving install process logic to the CL extension too.
* Try and add API call to get help text for CL commands too. Idea documented in #1904
