### ISSUE TITLE
Allow for protected filters to run identified user actions

### ISSUE THREAD

**Issue by m-tyler** [codefori/vscode-ibmi#1400]
**Is your feature request related to a problem? Please describe.**
Allow for protected filters to run identified user actions

**Describe the solution you'd like**
I like the idea of the protected filter and protecting modifying source viewed in libraries that are considered production level or at least protected by a CMS tool like Rocket Aldon.  My issue with protected filters blocking ALL actions is that I have added actions that allow me to perform checkouts on members in protected libraries.   I don't want all actions to be allowed but a few that I can mark (with a manual configuration in the settings.json or as a config item on the maintenance panel). 

**Describe alternatives you've considered**
I have two work-a-rounds.
1. return to a 5250 session, open the CMS tool, and perform the checkout there.
2. remove the protect flag from the filter, refresh, perform my checkout action, change the filter to protected again, and refresh again. 

**Additional context**
I do understand the reasoning for not allowing this as it could/would open up the ability to make any and all actions available to walk around the protection.

**Comment by sebjulliand** [comment]
Sounds OK to me. It will be up to the users to be careful with what they do with their actions 😄
