### ISSUE TITLE
Protected source members

### ISSUE THREAD

**Issue by mprovvedi** [codefori/vscode-ibmi#1431]
Last week while i was opening source members in VSCode a lock icon appeared next to them (as shown below), without changing any configuration.

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/107923967/2e0f24be-b841-4cb8-a394-cd3db2e1bfed)

I tried to check both the filter settings (the "Protected" checkbox is unchecked) and the connection settings (the "Read only mode" in the "Source Code" tab is unchecked).
This morning i tried to create a new connection and when i was switching between connections to emulate all the settings the same thing happened.
I also tried to create new filters for other source files but the members are still locked.

Finally, i found out that this happens when you put a non exisisting library in the library list on VSCode. So i think that this happened last week because we had to delete one library in the library list.

Is this a feature to prevent to compile with the wrong library list or is this a bug? If this is a feauture, is it possible to show some error messages to enlight the problem?

Thank you!
<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.0.0|
|Visual Studio Code version|1.80.0|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Account Microsoft (microsoft-authentication): 0.0.1
Autenticazione GitHub (github-authentication): 0.0.2
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Collegamento automatico per debug di Node (debug-auto-launch): 1.0.0
Creazione estensione (extension-editing): 1.0.0
Db2 for IBM i (vscode-db2i): 0.2.11
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.11.1
Esegui merge del conflitto (merge-conflict): 1.0.0
Funzionalità dei linguaggi TypeScript e JavaScript (typescript-language-features): 1.0.0
Funzionalità del linguaggio JSON (json-language-features): 1.0.0
GIT (git): 1.0.0
Git Base (git-base): 1.0.0
Git Graph (git-graph): 1.30.0
GitHub (github): 0.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.5
Material Icon Theme (material-icon-theme): 4.28.0
Monokai Pro (theme-monokai-pro-vscode): 1.2.1
Overtype (overtype): 0.5.0
Path Intellisense (path-intellisense): 2.8.4
Prettier - Code formatter (prettier-vscode): 9.19.0
RPGLE (vscode-rpgle): 0.19.3
Supporto di npm per VS Code (npm): 1.0.1
TODO Highlight (vscode-todo-highlight): 1.0.5
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|2|
|CCSID|1144|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|git|setccsid||||
|ls|tar||||
|md5sum|||||
|sort|||||
|stat|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=QGPL
CURLIB=QGPL
PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
TZ=<CET>-1<CEST>,M3.5.0,M10.5.0
_=/QOpenSys/usr/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "��$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: La libreria ILEDITOR esiste gi�."
  },
  {
    "command": "system \"DLTOBJ OBJ(ILEDITOR/O_*) OBJTYPE(*FILE)\"",
    "code": 255,
    "stderr": "CPF2125: Non � stato cancellato alcun oggetto."
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "liblist: 001-0081 Errore CPF2110 rilevato aggiungendo la libreria DBLFIVG all'elenco librerie."
  }
]
```
</details>

**Comment by chrjorgensen** [comment]
@alfax218 How did you get the non-existing library in your library list in VS Code? By deleting it on the server but not (yet) updated your VS Code library list?

The extension checks that you have update authority to the source members you open - and I guess it will consider the authority not sufficient if the check command fails because of the bad library list.

You can run `Change Library List` from the VS Code command palette and press `Enter` on the prompt containing the current library list - then all libraries are verified and any non-existing libraries are removed from your list.

I will make a PR so the library list is validated when connecting to the system.

**Comment by chrjorgensen** [comment]
@alfax218 I can confirm that having a non-existing library in the library list will cause the lock icon ![billede](https://github.com/halcyon-tech/vscode-ibmi/assets/13275072/f27375a0-d98c-4f0e-be80-fe140b4d2161) to appear and the file considered readonly.

The PR #1433 will partially fix this by validating the library list when connecting and prompt for removal of non-existing libraries from the library list,

**Comment by alfax218** [comment]
@chrjorgensen This is perfect, thank you!

**Comment by chrjorgensen** [comment]
@alfax218 After some thoughts, I think it would be fair to move this validation to the `Connect and Reload Server` settings function, so it is only run when requested. This is a special case that does not need to run on every connection, right? We always recommend running `Connect and Reload Server` when issues appear, to pick up any changes on the server. WDYT?

**Comment by alfax218** [comment]
@chrjorgensen I get your point and agree, but I also thought that it would be nice if the section `User Library List` on the left panel could change color to red if some library fails the check, maybe also enlight the wrong library.

Maybe only prompt with `Connect and Reload Server`, and color red on every failed check (e.g. when you run `Refresh Object Browser`).

**Comment by chrjorgensen** [comment]
@alfax218 If you activate `Show description of libraries in User Library List view` in the connection settings, any non-existing libraries will have `*** NOT FOUND ***` as the description. I think this should be enough to realize that libraries are invalid, right?

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/13275072/57d89222-76f2-4030-a3f0-fa9b9415e750)

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/13275072/22285d82-2711-4a09-ad15-d3a3f9b76100)

**Comment by chrjorgensen** [comment]
@alfax218 I will be off the upcoming weeks, so no more action on this from me right now...

**Comment by ThomasBarberot** [comment]
Hello. I have the same problem (and some collegues too) : after a VSCode update, some source files became "protected" (and I was able to modify them before). I tried to remove the connection, the profile, the filters, but I've still got the problem :
![Sources](https://github.com/halcyon-tech/vscode-ibmi/assets/123751292/2e650305-87cb-4963-884b-52a79cd7d4ee)
All the libraries in the list exist.
My profile has a group profile, and all created objects are owned by the group profile. For example:
![DSPOBJAUT QRPGLESRC in Library](https://github.com/halcyon-tech/vscode-ibmi/assets/123751292/b6916f04-1938-4868-8625-459579f66b85)
Of course, using SEU or RDi, there is no problem to update them.
It happens on sevaral partitions, so it bacame a real problem : I cannot maintain my sources!
Do you have an idea?
Thanks

**Comment by sebjulliand** [comment]
Hi @ThomasBarberot ,
can you check if your user library list is OK, as stated below? If not, remove the faulty libraries and you should be ok.

> @alfax218 If you activate `Show description of libraries in User Library List view` in the connection settings, any non-existing libraries will have `*** NOT FOUND ***` as the description. I think this should be enough to realize that libraries are invalid, right?
> 
> ![image](https://user-images.githubusercontent.com/13275072/253205942-57d89222-76f2-4030-a3f0-fa9b9415e750.png)
> 
> ![image](https://user-images.githubusercontent.com/13275072/253206032-22285d82-2711-4a09-ad15-d3a3f9b76100.png)

Otherwise, please share the content of both `IBM i` and `Code for IBM i` outputs after you expand a source file showing locked members.
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/11096890/1586e6a8-1518-42f1-a267-e8878e2066d4)

**Comment by ThomasBarberot** [comment]
Sébastien,
The libray list is correct :
![Sources2](https://github.com/halcyon-tech/vscode-ibmi/assets/123751292/5960f447-21c6-43a3-a3a4-21dad80512ad)

After opening a protected membre, here is the IBM i output :
```
Commands:
		CHKOBJ OBJ(FR109677/QCMDSRC) OBJTYPE(*FILE) AUT(*UPD)
		
qsh: 001-00
50 Syntax error on line 1: token ";" not expected.
```

And the Code for i output (where we can find the same problem with the ";"):
```
/home/FR109677: echo "This should be the only text!"
{
    "code": 0,
    "signal": null,
    "stdout": "This should be the only text!",
    "stderr": ""
}

.: pwd
{
    "code": 0,
    "signal": null,
    "stdout": "/home/FR109677",
    "stderr": ""
}

/home/FR109677: pwd
{
    "code": 0,
    "signal": null,
    "stdout": "/home/FR109677",
    "stderr": ""
}

/home/FR109677: /QOpenSys/usr/bin/qsh
liblist
{
    "code": 0,
    "signal": null,
    "stdout": "QSYS        SYS\nQSYS2       SYS\nQHLPSYS     SYS\nQUSRSYS     SYS\nQSHELL      PRD\nAMSSAMPLE   USR\nFR109677    USR\nQUSRBRM     USR\nQTEMP       USR\nQGPL        USR",
    "stderr": ""
}

/home/FR109677: system "CRTLIB LIB(FR109677VS) TEXT('Code for i temporary objects. May be cleared.')"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF2111: Library FR109677VS already exists."
}

/home/FR109677: [ -d "/home/FR109677/.vscode" ]
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/FR109677: system "DLTOBJ OBJ(FR109677VS/O_*) OBJTYPE(*FILE)"
/home/FR109677: rm -f /home/FR109677/.vscode/vscodetemp*
/home/FR109677: echo $SHELL
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF2125: No objects deleted."
}

{
    "code": 0,
    "signal": null,
    "stdout": "/QOpenSys/pkgs/bin/bash",
    "stderr": ""
}

/home/FR109677: system "DSPOBJD OBJ(QSYS/*ALL) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(FR109677VS/O_wrApx1l4)"
/home/FR109677: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select OS_VERSION || '.' || OS_RELEASE as VERSION from sysibmadm.env_sys_info
/home/FR109677: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select max(ptf_group_level) as HIGHEST_DB2_PTF_GROUP_LEVEL from qsys2.group_ptf_info where PTF_GROUP_DESCRIPTION like 'DB2 FOR IBM I%' and ptf_group_status = 'INSTALLED';
/home/FR109677: ls $HOME/.vscode/codeforiserver-1.0.0-alpha-33.jar
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_WRAPX1L4 created in library FR109677VS.\nCPF9862: Member O_WRAPX1L4 added to output file O_WRAPX1L4 in library FR109677VS.",
    "stderr": ""
}

/home/FR109677: system "QSYS/CPYTOIMPF FROMFILE(FR109677VS/O_wrApx1l4 O_wrApx1l4) TOSTMF('/home/FR109677/.vscode/vscodetemp-O_7iNAi3yA') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"
{
    "code": 4,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\n **** CLI ERROR *****\n         SQLSTATE: 42601\nNATIVE ERROR CODE: -104\nToken | was not valid. Valid tokens: + - AS <IDENTIFIER>.",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "/home/FR109677/.vscode/codeforiserver-1.0.0-alpha-33.jar",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n\nHIGHEST_DB2_PTF_GROUP_LEVEL \n----------------------------\n                          19\n\n  1 RECORD(S) SELECTED.\n\nDB2>",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "CPC2958: All records copied from file O_WRAPX1L4 in FR109677VS.",
    "stderr": ""
}

.: rm -f /home/FR109677/.vscode/vscodetemp-O_7iNAi3yA
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

.: system "DLTOBJ OBJ(FR109677VS/O_wrApx1l4) OBJTYPE(*FILE)"
/home/FR109677: system "DSPOBJD OBJ(QSYS/*ALL) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(FR109677VS/O_rYdyQcjZ)"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_RYDYQCJZ created in library FR109677VS.\nCPF9862: Member O_RYDYQCJZ added to output file O_RYDYQCJZ in library FR109677VS.",
    "stderr": ""
}

/home/FR109677: system "QSYS/CPYTOIMPF FROMFILE(FR109677VS/O_rYdyQcjZ O_rYdyQcjZ) TOSTMF('/home/FR109677/.vscode/vscodetemp-O_pqZGJrcd') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPC2958: All records copied from file O_RYDYQCJZ in FR109677VS.",
    "stderr": ""
}

.: rm -f /home/FR109677/.vscode/vscodetemp-O_pqZGJrcd
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

.: system "DLTOBJ OBJ(FR109677VS/O_rYdyQcjZ) OBJTYPE(*FILE)"
/home/FR109677: system "DSPOBJD OBJ(QSYS/*ALL) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(FR109677VS/O_1gSpsoNf)"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_1GSPSONF created in library FR109677VS.\nCPF9862: Member O_1GSPSONF added to output file O_1GSPSONF in library FR109677VS.",
    "stderr": ""
}

/home/FR109677: system "QSYS/CPYTOIMPF FROMFILE(FR109677VS/O_1gSpsoNf O_1gSpsoNf) TOSTMF('/home/FR109677/.vscode/vscodetemp-O_XX2A3OIS') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPC2958: All records copied from file O_1GSPSONF in FR109677VS.",
    "stderr": ""
}

.: rm -f /home/FR109677/.vscode/vscodetemp-O_XX2A3OIS
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

.: system "DLTOBJ OBJ(FR109677VS/O_1gSpsoNf) OBJTYPE(*FILE)"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/FR109677: system "DSPFD FILE(FR109677/*ALL) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(FR109677VS/O_IfRBXNfv)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_IFRBXNFV created in library FR109677VS.\nCPF9862: Member O_IFRBXNFV added to output file O_IFRBXNFV in library FR109677VS.\nCPF3030: 5 records added to member O_IFRBXNFV in file O_IFRBXNFV in FR109677VS.",
    "stderr": ""
}

/home/FR109677: system "QSYS/CPYTOIMPF FROMFILE(FR109677VS/O_IfRBXNfv O_IfRBXNfv) TOSTMF('/home/FR109677/.vscode/vscodetemp-O_QKw9Iy15') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPC2958: All records copied from file O_IFRBXNFV in FR109677VS.",
    "stderr": ""
}

.: rm -f /home/FR109677/.vscode/vscodetemp-O_QKw9Iy15
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

.: system "DLTOBJ OBJ(FR109677VS/O_IfRBXNfv) OBJTYPE(*FILE)"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/FR109677: /QOpenSys/usr/bin/qsh
liblist -d AMSSAMPLE FR109677 QUSRBRM QTEMP QGPL && liblist -c FR109677 && liblist -a QGPL QTEMP KIIMOBJ KIIMSRC && system  "CHKOBJ OBJ(FR109677/QCMDSRC) OBJTYPE(*FILE) AUT(*UPD)"; if [[ $? -ne 0 ]]; then exit 1; fi
{
    "code": 2,
    "signal": null,
    "stdout": "",
    **"stderr": "qsh: 001-0050 Syntax error on line 1: token \";\" not expected."**
}

/home/FR109677: system "DSPFD FILE(FR109677/QCMDSRC) TYPE(*MBR) OUTPUT(*OUTFILE) OUTFILE(FR109677VS/O_thcUuOpc)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_THCUUOPC created in library FR109677VS.\nCPF9862: Member O_THCUUOPC added to output file O_THCUUOPC in library FR109677VS.\nCPF3030: 1 records added to member O_THCUUOPC in file O_THCUUOPC in FR109677VS.",
    "stderr": ""
}

/home/FR109677: system "QSYS/CPYTOIMPF FROMFILE(FR109677VS/O_thcUuOpc O_thcUuOpc) TOSTMF('/home/FR109677/.vscode/vscodetemp-O_QCz0Ery9') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPC2958: All records copied from file O_THCUUOPC in FR109677VS.",
    "stderr": ""
}

.: rm -f /home/FR109677/.vscode/vscodetemp-O_QCz0Ery9
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

.: system "DLTOBJ OBJ(FR109677VS/O_thcUuOpc) OBJTYPE(*FILE)"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/FR109677: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
CREATE OR REPLACE ALIAS FR109677VS.FR109677_QCMDSRC_DSPPCML for "FR109677"."QCMDSRC"("DSPPCML")
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n  ?>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.",
    "stderr": ""
}

/home/FR109677: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT LENGTH(srcdta) as LENGTH FROM FR109677VS.FR109677_QCMDSRC_DSPPCML limit 1
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\nLENGTH     \n-----------\n         80\n\n  1 RECORD(S) SELECTED.",
    "stderr": ""
}

/home/FR109677: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select srcdat, rtrim(translate(srcdta, x'2F', x'25')) as srcdta from FR109677VS.FR109677_QCMDSRC_DSPPCML
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\nSRCDAT   SRCDTA                                                                          \n-------- --------------------------------------------------------------------------------\n 230530  CMD        ('Display the PCML in a module')                                     \n 230530                                                                                  \n 230530  /* Command processing program is DSPPCMLR.RPGLE */                              \n 230530                                                                                  \n 230530  /* CRTBNDRPG MYLIB/DSPPCMLR                  */                                 \n 230530  /* CRTCMD MYLIB/DSPPCML PGM(MYLIB/DSPPCMLR)  */                                 \n 230530                                                                                  \n 230530  PARM       KWD(OBJ) TYPE(QUALOBJ) PROMPT('Object containing module')            \n 230530  PARM       KWD(MODULE) TYPE(QUALMOD) DFT(*ALLBNDMOD) SNGVAL((*ALLBNDMOD +       \n 230530             *ALLBNDMOD)) PROMPT('Module')                                        \n 230530  PARM       KWD(OBJTYPE) TYPE(*CHAR) LEN(10) RSTD(*YES) DFT(*PGM) +              \n 230530             VALUES(*PGM *SRVPGM) SPCVAL((*PGM *PGM) (*SRVPGM *SRVPGM)) +         \n 230530             PROMPT('Object type') CHOICE('*PGM *SRVPGM')                         \n 230530  PARM       KWD(STATSONLY) TYPE(*CHAR) LEN(10) RSTD(*YES) DFT(*NO) +             \n 230530             VALUES(*NO *YES) SPCVAL((*NO *NO) (*YES *YES)) PROMPT('Show +        \n 230530             stats only') CHOICE('*NO *YES')                                      \n 230530                                                                                  \n 230530  QUALOBJ: QUAL TYPE(*NAME) EXPR(*YES) LEN(10)                                    \n 230530  QUAL       TYPE(*NAME) EXPR(*YES) LEN(10) DFT(*LIBL) SPCVAL((*CURLIB +          \n 230530             *CURLIB) (*LIBL *LIBL)) PROMPT('Library')                            \n 230530  QUALMOD: QUAL TYPE(*NAME) EXPR(*YES) LEN(10)                                    \n 230530  QUAL       TYPE(*NAME) EXPR(*YES) LEN(10) DFT(*ANY) SPCVAL((*ANY *ANY)) +       \n 230530             PROMPT('Library')                                                    \n\n 23 RECORD(S) SELECTED.",
    "stderr": ""
}
```

**Comment by sebjulliand** [comment]
Thanks @ThomasBarberot. I'll get back to you soon.

**Comment by ThomasBarberot** [comment]
Great. Ask if you want anything else

**Comment by ThomasBarberot** [comment]
Hello.
My default shell is set to bash: 

![shell](https://github.com/halcyon-tech/vscode-ibmi/assets/123751292/7646a943-d3de-477f-972e-7741ad9bb4b6)

I don't have any `.bashrc` file in my home directory (or I don't kwon where to seek).

My home directory `.profile` file is:
```
PATH=/QOpenSys/pkgs/bin:$PATH
export PATH
PASE_PATH=/QOpenSys/pkgs/bin:$PASE_PATH
export PASE_PATH
PS1='$PWD >'
export PS1
```

With my shell setted to bash, I've got some character conversion problems: the accentued (é, à...) or specials (@, #...) characters are not displayed correctly.

So I tried to reset the shell to "default", not bash, and surprise!: accentuated and special characters are correctly displayed and I can update the members which are no more longer protected!:
```
Commands:
		CHKOBJ OBJ(FR109677/QCMDSRC) OBJTYPE(*FILE) AUT(*UPD)

CPC2206:  Ownership of object QZSHSYSTEM in QTEMP type *USRSPC changed.
```
So there is a conflict between bash and my profile/partition configuration (I think I have already asked for this). And when I connect the partition, it always asks me to set shell to bash (which is a problem for me).

**Comment by chrjorgensen** [comment]
@ThomasBarberot Can you try and comment out the PASE_PATH statements and switch to bash again?

It's not needed to change this, and it could interfere with the PASE functionally...

**Comment by ThomasBarberot** [comment]
@sebjulliand I tried to set bash on and to comment what you said:
```
PATH=/QOpenSys/pkgs/bin:$PATH
export PATH
# PASE_PATH=/QOpenSys/pkgs/bin:$PASE_PATH
# export PASE_PATH
PS1='$PWD >'
export PS1
```
But the problem reoccurs

**Comment by chrjorgensen** [comment]
@ThomasBarberot Too bad it didn't work...

I would suggest to try the filing command in another SSH client like Putty. Seems like your open source environment is not correctly set up, which can be verified or dismissed with another SSH client.

Also follow the instructions on the IBM i open source page for setting up bash: https://ibmi-oss-docs.readthedocs.io/en/latest/user_setup/README.html

**Comment by ThomasBarberot** [comment]
@sebjulliand: the following command `system  "CHKOBJ OBJ(AMSSAMPLE/QDDSSRC) OBJTYPE(*FILE) AUT(*UPD)"` is working well in putty (I made a try with a incorrect name to be sure of the command execution):
![putty](https://github.com/halcyon-tech/vscode-ibmi/assets/123751292/ddc0bab8-8d7d-4dae-aea7-efb6a1e27498)
And I checked the bash installation, nothing seems wrong :-(

**Comment by chrjorgensen** [comment]
@ThomasBarberot The command you should try in another SSH client is not just the `system` command, but this full command:

```bash
/QOpenSys/usr/bin/qsh liblist -d AMSSAMPLE FR109677 QUSRBRM QTEMP QGPL && liblist -c FR109677 && liblist -a QGPL QTEMP KIIMOBJ KIIMSRC && system  "CHKOBJ OBJ(FR109677/QCMDSRC) OBJTYPE(*FILE) AUT(*UPD)"; if [[ $? -ne 0 ]]; then exit 1; fi
```

What is the result of the above command?

**Comment by ThomasBarberot** [comment]
@sebjulliand 
I can't run the whole command because of errors I don't know how to fix:
![putty2](https://github.com/halcyon-tech/vscode-ibmi/assets/123751292/5995b561-6639-4009-905e-533263c05594)
