### ISSUE TITLE
Truncate text of /copy members when compiling SQLRPGLE source

### ISSUE THREAD

**Issue by allthom** [codefori/vscode-ibmi#1463]
👉🏻 Hellò, strange things happening here (at least for me).
I think it is an issue of the system, but maybe some of you has already faced this kind of problem. 
I'll try to tell you what's happening.

I am converting a small set of pgms to complete free form syntax for testing reason.

In my shop we use to have very long name for subprocedure i.e. if we have a subp that retrieves a list of customer by town or state it will be named something like "RetrieveCustomerListByTownOrState".

Now i have created an "ad hoc" library for my testing. All source phisical file are created with a lenght of 184.

i have a /COPY member that contains some sub-p with a long definition like this
`Dcl-PR ContaTesseratiDLSocietaDisciplina Zoned(6:0) EXTPROC('ContaTesseratiDLSocietaDisciplina');`
it end up at column 98.

then i have another source where I include the source simply with a `/COPY` statement
`/COPY QCPYSRC,STATESCPY`

When I compile the source that include those sub-p i receive this error in the compiler listing
`      Dcl-PR ContaPrestitiDLSocietaDisciplina Zoned(6:0) EXTPROC('ContaPrestiti   034100              DLSocietaDisciplina`
 It seem that the sql compiler (the source I am tryng to compile is a SQLRPGLE source) truncate text of source at column 80

Where can i look to solve this problem?
<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.0.2|
|Visual Studio Code version|1.80.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 9.7.23
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.3.3
ESLint (vscode-eslint): 2.4.2
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.12.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.19.3
RPGLE Free (vscode-rpgfree): 0.0.26
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL (remote-wsl): 0.80.2
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R3M0|
|Tech Refresh|12|
|CCSID|65535|
|SQL|Disabled
|Source dates|Disabled

### Enabled features

|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|
|-|-|-|
|attr|GENCMDXML.PGM|QZDFMDB2.PGM|
|iconv|GETNEWLIBL.PGM||
|ls|||
|setccsid|||
|tar|||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "��$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CPYTOSTMF FROMMBR('/QSYS.lib/STATISTICH.lib/VSCODE.file/RPGLINT.mbr') TOSTMF('/tmp/vscodetemp-O_WVf3SJSx') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)\"",
    "code": 255,
    "stderr": "CPFA0A9: L'oggetto non � stato trovato. L'oggetto � /QSYS.lib/STATISTICH.lib/VSCODE.file/RPGLINT.mbr.\nCPFA097: Oggetto non copiato. L'oggetto � /QSYS.lib/STATISTICH.lib/VSCODE.file/RPGLINT.mbr.",
    "cwd": "."
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPC9801:  Oggetto MXCMD2RUN di tipo *DTAQ creato nella libreria QTEMP.\nCPC9801:  Oggetto MXRSNDMG di tipo *DTAQ creato nella libreria QTEMP.\nCPC7301:  File QSQLT00184 creato nella libreria QTEMP.\nCPC7305:  Membro XSTA02R aggiunto al file QSQLT00184 in QTEMP.\nSQL9001:  Precompilazione SQL non riuscita.",
    "cwd": "/home/LUCAG"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"LUCAG\" && export HOME=\"/home/LUCAG\" && export LIBLS=\"STATISTICH LND_DW ACGGAA JGPL QTEMP QGPL SANZIONI TECNICA KENTRO NUOVA NUOVAOBJ FIGCOBJR2X INUOVA INUOVAOBJ SPORT PO36LIB ICOMUNE LND_SRC LND_DAT LND_OBJ\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/LUCAG"
  }
]
```
</details>

**Comment by chrjorgensen** [comment]
@allthom Check this link for information on how to control the length of the temporary source file created by the SQL precompiler:

[https://ibm.biz/rpgcafe_PPMINOUTLN_qsqlpre](https://ibm.biz/rpgcafe_PPMINOUTLN_qsqlpre

**Comment by chrjorgensen** [comment]
@allthom Also note that your /COPY member must start with `**free` as line 1 or it will be considered fixed format with code between columns 1 and 80!

[https://www.ibm.com/docs/en/i/7.3?topic=specifications-free-form-statements](https://www.ibm.com/docs/en/i/7.3?topic=specifications-free-form-statements)
