### ISSUE TITLE
RPGLESRC no longer viewable via Object Browser

### ISSUE THREAD

**Issue by hollygit** [codefori/vscode-ibmi#1478]
I can no longer see RPG Source in Object Browser. Note: this system is on os vers 7.2
 
 I tried on version 2.0.2 and 2.01.
 
<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.0.1|
|Visual Studio Code version|1.81.0|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Auto Close Tag (auto-close-tag): 0.5.14
Beautify (beautify): 1.5.0
Beautify css/sass/scss/less (code-beautifier): 2.3.3
COBOL (cobol): 9.7.23
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.3.3
Dev Containers (remote-containers): 0.304.0
ESLint (vscode-eslint): 2.4.2
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.13.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
HTML CSS Support (vscode-html-css): 1.13.1
Highlight Matching Tag (highlight-matching-tag): 0.11.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Live Server (LiveServer): 5.7.9
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
Tailwind CSS IntelliSense (vscode-tailwindcss): 0.9.11
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL (remote-wsl): 0.80.2
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|n/a|
|Tech Refresh|n/a|
|CCSID|?|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|
|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|
|git|iconv|GETNEWLIBL.PGM||
|grep|setccsid|||
|ls|tar|||
|md5sum||||
|sort||||
|stat||||
|tn5250||||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home*******"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"******\" && export HOME=\"/home/******\" && export LIBLS=\"V4CESHIPF V4CESHIP COMEDGE CECARTRDB LIBHTTP CECREDIT AFPTOOL SPLTOOL V4MSGR V4FILES V4MASTER V4PRMODS HOLLY CECART\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/******"
  }
]
```
</details>

**Comment by hollygit** [comment]
[image: image.png]

**Comment by worksofliam** [comment]
@hollygit Photos cannot be uploaded via email. Please post it on the issue itself.

**Comment by hollygit** [comment]
Note: it works fine on other systems.   Is OS 7.2 too old now?

**Comment by hollygit** [comment]
Ok, I will do that.

**Comment by hollygit** [comment]
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/85589578/fddaf8b1-e0a8-4ee0-bb11-2823c09cca01)

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the list doesn't appear.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by hollygit** [comment]
Commands:
		CHKOBJ OBJ(HOLLY/QRPGLESRC) OBJTYPE(*FILE) AUT(*UPD)

Commands:
		CHKOBJ OBJ(V4PRMODS/QRPGSRC) OBJTYPE(*FILE) AUT(*UPD)

**Comment by worksofliam** [comment]
Stale? Guessing it worked out?
