### ISSUE TITLE
"QlgGetPathFromFileID() error" Obtained when Start Debug Service is called [Contains a possible solution]

### ISSUE THREAD

**Issue by crisrivlop** [codefori/vscode-ibmi#1510]
Hi there!
I was trying to use the _Start Debug Service_ feature. I already configured the certificates. But when i tried to execute _Start Debug Service_ i recieve the [EQARD1005D](https://www.ibm.com/docs/en/wdfrhcw/1.4.0?topic=messages-remote-debug-service) message.
As I explore through the code for ibm output panel, I saw an error related to the execution of _**startDebugService.sh**_ on the ifs.
The message i got on stdout is the following:

> QlgGetPathFromFileID() error\Illegal base64 character 28\nEQARD1005E The argument \"error\" is not valid. \n\nUse the -help option to display the command line help.

Before that in the same output I saw **encryptKeystorePassword.sh** was executed an output in stdout was:

> "QlgGetPathFromFileID() error\nENCRIPTED_RESULT"
> Note: ENCRIPTED_RESULT is just an alias of the data i found (a base64 string).

As your may notice it contains an special new line character (\n). It could be added to the extension the support of this kind of cases in which the expected value (ENCRIPTED_RESULT) is in the result message. But has a previous string which ends with \n.

So in this extension at [Source on src/api/debug/server.ts](https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/api/debug/server.ts) Last line of tail is going to be read when next code is executed: 

``` js
const encryptResult = await connection.sendCommand({
    command: `${MY_JAVA_HOME} DEBUG_SERVICE_KEYSTORE_PASSWORD="${host}" ${path.posix.join(directory, `encryptKeystorePassword.sh`)} | /usr/bin/tail -n 1`
 });
```
but other string could be there, for this case specifically  "QlgGetPathFromFileID() error\n" which is discribed in the following link why it happends: ["QlgGetPathFromFileID() error"](https://code400.com/forum/forum/iseries-programming-languages/java/149454-rpg-java-jvm-startup-issue). Those kind of messages brings a line breaks with especial scape character \n instead of real line break. So as is discuse in the previous article if you don't have **"SPECIAL AUTHORITY" = *ALLOBJ** for your profile. Those messages can appear and you could recieve in constant **encryptResult** on the  [server.ts](https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/api/debug/server.ts) file. As **encryptResult** is loaded with 
QlgGetPathFromFileID() error\nENCRIPTED_RESULT the next step:

``` js
const encryptResult = await connection.sendCommand({
    command: `${MY_JAVA_HOME} DEBUG_SERVICE_KEYSTORE_PASSWORD="${host}" ${path.posix.join(directory, `encryptKeystorePassword.sh`)} | /usr/bin/tail -n 1`
 });
```

Is going to fail because the expected value is a base64 string.

Next image describes how the **ENCRIPTED_RESULT** could to be obtained in this kind of cases
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/5351172/fc36331f-66c4-4c63-93e3-1ba82420d612)

Code used: 

``` js
const encryptResult = "QlgGetPathFromFileID() error\nENCRIPTED_RESULT";
const encryptResultFixed = encryptResult.split("\n").reverse()[0];
console.log(encryptResultFixed);
```

**Comment by crisrivlop** [comment]
Update: I changed tail -n 1 to tail -n 0 and it worked. No obstant tail -n 1 worked using qsh inside de server, could it be a ccsid problem?

**Comment by worksofliam** [comment]
Closing as we have changed how the debug startup is handled.
