### ISSUE TITLE
Source dates overwritten

### ISSUE THREAD

**Issue by alfax218** [codefori/vscode-ibmi#1511]
Hello!
I found this bug recently, probably due to the changes of the release 2.1.0.

Sometimes (not always) when I start a new line in my source file all the source dates disappear.
Then, if I save the file, all the source dates become equal to current day (event though I cannot see them). The dates seem to reappear only if I re-open the file.

These are my settings:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/107923967/a71041ee-e538-46c8-b79a-b8360b775acc)

This is an example of dates disappearing and reappearing with current date:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/107923967/19a28395-ea39-4403-b105-075bf82f4c06)
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/107923967/1592b67f-48bd-4b2a-8123-1b3a73cccb77)

Let me know if you need more infos.
Thank you!

**Comment by jkyeung** [comment]
Does this still happen? Have you been able to discern any patterns that would let you predict when it's going to happen, and increase the chance someone can reproduce it?
