### ISSUE TITLE
Syntax Highlighting Issue

### ISSUE THREAD

**Issue by NicholasLanders** [codefori/vscode-ibmi#1513]
Save us time! Click 'Report an Issue' from the Help and Support panel inside of VS Code after you have connected to a system.

**Describe the bug**
When on version 2.1.1 (using local IFS deployment) when there was a compilation error, there was no highlighting on the screen. I could only see it on the output log. When I rolled back to 2.0.2 it worked with no issue. 

**To Reproduce**
1. ctrl + e to compile. 
2. When error happens the syntax highlighting does not follow. 

**Expected behavior**
Syntax highlighting to show. 

**Environment (please complete the following information):**
 - Extension version 2.1.1
 - IBM i OS version [e.g. 7.3]

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the list doesn't appear.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by worksofliam** [comment]
Closing as stale.
