### ISSUE TITLE
Add "RPGPPOPT(*LVL2)" to CRTSQLRPGI Action

### ISSUE THREAD

**Issue by SJLennon** [codefori/vscode-ibmi#1520]
When creating SQLRPG programs from the IFS, I think most people will use relative paths for `/COPY` and `/INCLUDE` files, for example, `/INCLUDE ../Copy_Mbrs/Srv_Msg_P.RPGLE`. Since the preprocessor creates a temporary file, the RPG compiler cannot find such relative files and the compile fails. Using RPGPPOPT(*LVL2) expands the the files before the preprocessor see them and the compile succeeds.

**Describe the solution you'd like**
When creating a new `actions.json` file please add `RPGPPOPT(*LVL2)` to the `CRTSQLRPGI` strings.

I know I can edit `actions.json` manually and that is what I have done. Not a problem, just a convenience and I don't think it will hurt most people.

**Comment by JDubbTX** [comment]
I agree that RPGPPOPT(*LVL2) is a good option for most.  My company uses it as a default in our build application.
