### ISSUE TITLE
Keep last file opened in open file dialog

### ISSUE THREAD

**Issue by MarcJose** [codefori/vscode-ibmi#1529]
Hello everyone :)
I may have a feature request below:

**Is your feature request related to a problem? Please describe.**
When opening multiple files, it is quite annoying to always having to type the full path again.

**Describe the solution you'd like**
It would be neat if the file open dialogue would remember the last used library and source file.
This would be the same behaviour as inside RDi.

For example, after opening the first file with [Ctrl]+[Alt]+[P]:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/56023816/f1cce564-d1a1-4539-82de-5d0355cfa156)

Then when opening the second file with [Ctrl]+[Alt]+[P] it would display:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/56023816/bd1b7324-46ea-498e-880d-5fc4f86e6966)

Currently, the input field is completely empty :/

Kind regards,
Marc

**Comment by worksofliam** [comment]
This is a pretty neat idea! Since this window can accept both an IFS path or a member path, we'd have to support remembering the path for both.

**Comment by chrjorgensen** [comment]
@worksofliam I tested this - and it seems to me that it's not possible to have an initial value in a QuickPick, which is the component used in the open file dialog... ❔
