### ISSUE TITLE
When I save a program(source member) it erases all the date stamps from SRCDAT

### ISSUE THREAD

**Issue by gtank1** [codefori/vscode-ibmi#1557]
**Describe the bug**
The date stamp column is all set to 000000 for all lines of code in the source member I edit, loosing all history.

Los problemas en espanol estan bien.

**To Reproduce**
1. Open a source member
2. Save the source member
3. Open on the IBM i using wrkmbrpdm (or any other source editing tool)
       A. Or query the code using SQL   
            i.  Create Alias CODE for library/sourceFile(MemberName)
            ii. Select * from Code 
4. All likes date field(SRCDAT) is set to 000000

**Expected behavior**
The freshly edited lines should be updated  to today's date stamp and the old ones should remain the same.

**Screenshots**
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/5958676/ba896d35-3db7-4e79-b5b1-efb09626815b)

**Environment (please complete the following information):**
|Code for IBM i version|2.2.1|
|Visual Studio Code version|1.82.2|
|Operating System|win32_x64|
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.4.1
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
IBM i Project Explorer (vscode-ibmi-projectexplorer): 1.2.2
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
**Additional context**

**Comment by worksofliam** [comment]
Do you have source dates enabled in the connection settings?

**Comment by AMetnik** [comment]
@gtank1 
We had the same issue, until we read the documentation about the source dates:
Can be found here: [Source dates prerequisites](https://halcyon-tech.github.io/docs/#/pages/developing/sourcedates?id=prerequisites-to-using-source-dates)

**Comment by jkyeung** [comment]
> @gtank1 We had the same issue, until we read the documentation about the source dates: Can be found here: [Source dates prerequisites](https://halcyon-tech.github.io/docs/#/pages/developing/sourcedates?id=prerequisites-to-using-source-dates)

Sorry to piggyback onto this issue, but: I have a couple suggestions for those docs (are they pull-request-able?):

1. It's not a _hard_ prereq for QCSSID to be set properly. I am on a system with QCSSID = 65535, and I have source dates enabled. It seems to work as well as it would on a properly configured system. It would be more accurate to say that proper QCSSID is "strongly encouraged" and/or that 65535 is "not supported; use at your own risk".
2.  We're well past the stage where diff mode is a test enhancement. It is here to stay, and from my experience, it is hands-down better than edit mode. Even users who want to exactly replicate SEU's behavior regarding dates will not get it with edit mode, despite its description. (_Conceptually_ edit mode is SEU-style, but in practice, it doesn't work that well because the mechanism for multi-line edits is so drastically different.)

**Comment by chrjorgensen** [comment]
@jkyeung 

> 1. It's not a _hard_ prereq for QCSSID to be set properly. I am on a system with QCSSID = 65535, and I have source dates enabled. It seems to work as well as it would on a properly configured system. It would be more accurate to say that proper QCSSID is "strongly encouraged" and/or that 65535 is "not supported; use at your own risk".

You're correct, the documentation is a bit off talking about the system value QCCSID must be set. It is more accurate to say that the system value  _or the userprofile_ must have a CCSID value different from 65535.

Code for IBM i uses SQL to read and write source date for source members, and SQL does not work when running in a job having CCSID 65535. The job CCSID comes from the userprofile for the job, which _can_ point to system value QCCSID (*SYSVAL), but also can specify a specific CCSID.

So there **must** be a CCSID value different from 65535, but it does not need to be the system value QCCSID that is set.

Btw, the [GitHub repository](https://github.com/halcyon-tech/docs) for the documentation is open for Pull Requests, and you are welcome to suggest some changes to the docs, if you find them insufficient or inaccurate.

**Comment by worksofliam** [comment]
Closing due to lack of response.
