### ISSUE TITLE
Improve navigation to selected source member

### ISSUE THREAD

**Issue by jkyeung** [codefori/vscode-ibmi#1563]
**Is your feature request related to a problem? Please describe.**
There is a lot of typing to do in "Go to File..." if you want to navigate to a specific source member and it's not one of the suggestions. In particular, you have to type the entire member name _and_ the entire extension. This is particularly cumbersome if you aren't even 100% sure what the extension _is_. For example, you know there's a member in QRPGLESRC, but it might be .RPGLE or .SQLRPGLE and if you guess the wrong one, or make a typo, you have to start over from scratch.

**Describe the solution you'd like**
It's multifaceted:

1. As early as possible, detect whether the search is for a source member or a stream file. If it's a source member, don't require the extension.
2. If it's not feasible to differentiate source members and stream files before the search input is finalized, then assume source members if invoked from the object browser (rename the feature as "Go to member...") and add a "Go to file..." feature on the IFS browser.
3. Include all members in the suggestions, so that even if it's the first time VS Code is encountering it, the user only has to type enough to uniquely identify the member.
4. If there are performance concerns with gigantic numbers of members, make a setting to control whether the suggestions include all or only recent/cached members. Or perhaps be more sophisticated and only suggest libraries until the user has typed the first slash; and then only suggest files until the user has typed the second slash; and then only suggest recent/cached members until the user has typed the first letter of the member name; and then finally suggest all remaining possibilities.
5. When the user has typed something into the "Go to File..." dialog and no member matched their input, the "Try Again" button should not attempt to open the same incorrect input again. Instead, it should close the just-opened and now-useless editor (the error message says "editor could not be opened", yet there is now a tab, listed in the "open editors" pane, that you have to manually close to get rid of), and immediately bring back the "Go to File..." dialog, ideally with the same input that the user just tried, so that they can edit it instead of starting over from scratch. Even if for some reason they *wanted* VS Code to attempt to open the exact same input again, it would already be right there for them to just press Enter.

**Describe alternatives you've considered**
Provide a way to do what PDM does: user right-clicks on an object browser folder that represents a source file; a search dialog pops up where the user can type some characters; then the _selector_ is positioned (as though pressing the down arrow repeatedly) to the first member that starts with those characters, or to the previous member if no such member exists, or to the first member if there are no previous members. Nothing is _opened_, but the selector is closer to where the user wants, which could save a lot of scrolling.

**Additional context**
I don't think any more is needed, but I can elaborate further if requested.

**Comment by jkyeung** [comment]
Related issues: #1051, #1165

**Comment by chrjorgensen** [comment]
@jkyeung Will [PR #1242](https://github.com/codefori/vscode-ibmi/pull/1242) solve some of your issues?

**Comment by jkyeung** [comment]
It would probably ease the pain. I don't know for sure because I don't know precisely what that PR does, and in general it's hard to really tell how well something works until you try it for yourself anyway. But from what I can tell, it should be an improvement over what we have now.

**Comment by worksofliam** [comment]
@jkyeung since this issue is quite old and @chrjorgensen did a lot of work to improve the Go to File feature, I will close this.

You're welcome to reopen or create a new issue based off of changes that have been made.
