### ISSUE TITLE
Connection with the debug engine was lost

### ISSUE THREAD

**Issue by JDubbTX** [codefori/vscode-ibmi#1572]
Save us time! Click 'Report an Issue' from the Help and Support panel inside of VS Code after you have connected to a system.

**Describe the bug**
Debugging an RPGLE source, which I successfully debugged all the way through a few minutes ago.  Now the debug engine connection gets lost on the 2nd step after stepping through once.

**To Reproduce**
Debugging a SQLRPGLE source member.  went away for a while and came back.  debugged again and now it can't debug through.

**Expected behavior**
Should debug all the way through without losing connection to debug engine

**Video**
![EDC7470E-FD07-44E8-A623-AEC716F4D391](https://github.com/codefori/vscode-ibmi/assets/56802156/14e9e402-9fba-4ce5-a029-cf968aa48e81)

**Environment (please complete the following information):**
 - Extension version
   IBM i Debug v1.0.0
   Code for IBM i v2.3.1
 - IBM i OS version 7.4

**Additional context**

**Comment by mkwan01** [comment]
Can you attach the output of the debug service here? The debug service output either appears at the debug service green screen console, or a QPRINT file for a JVM process, depending on how you start debug service.

**Comment by JDubbTX** [comment]
It seems to be running in a JVM service but I'm not sure how to get the output from it?  Not much in its job log and no spool files.... Where is output written to?  

![image](https://github.com/codefori/vscode-ibmi/assets/56802156/eadff8d5-329e-4564-8bb9-b4b93d4140cd)

job log entries:  

```text
Java Virtual Machine is IBM Technology for Java.  PID(834)
JVM properties were loaded from a properties file.        
```

NO spool files output

**Comment by mkwan01** [comment]
There is a FAQ on this in the Merlin debug doc link (https://www.ibm.com/docs/en/merlin/1.0?topic=environment-debugging):

Question: How can I see the output of the debug service?
Answer: You can see the output of IBM i Debug Service from the QPRINT file at the output queue QUSRSYS/QDBGSRV. You may need to stop the debug service before inspecting the content of the QPRINT file.

**Comment by mkwan01** [comment]
If you use RDi, the QPRINT file will appear under the Spool Files filter.

**Comment by worksofliam** [comment]
@JDubbTX Closing this for now, but if it's still an issue for you, please post back.
