### ISSUE TITLE
Webviews for Actions not functioning.

### ISSUE THREAD

**Issue by m-tyler** [codefori/vscode-ibmi#1578]
After upgrading to 2.4.0 I receive "Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state." when using my actions that show the webview or maintaining actions.

<hr />

![image](https://github.com/codefori/vscode-ibmi/assets/1353665/40b5de3b-e887-44c6-b8b7-d5a26af4dba1)

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.4.0|
|Visual Studio Code version|1.82.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code Spell Checker (code-spell-checker): 3.0.1
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.2
Db2 for IBM i (vscode-db2i): 0.5.0
ESLint (vscode-eslint): 2.4.2
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.14.0
Excel Viewer (gc-excelviewer): 4.2.58
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
Partial Diff (partial-diff): 1.4.3
Rainbow CSV (rainbow-csv): 3.7.1
SQL Formatter VSCode (sql-formatter-vsc): 2.1.1
Text Marker (Highlighter) (text-marker): 1.11.0
Todo Tree (todo-tree): 0.0.226
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
classdiagram-ts (classdiagram-ts): 0.1.67
macros (macros): 1.2.1
undefined (indent-rainbow): 8.3.1
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|2|
|CCSID|37|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|git|iconv|GETNEWLIBL.PGM|||
|grep|setccsid||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash

PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PCR=
PROFILENAME=D2
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=10.10.0.135 65331 22
SSH_CONNECTION=10.10.0.135 65331 10.0.4.31 22
TZ=<MST>7<MDT>,M3.2.0,M11.1.0
_=/QOpenSys/usr/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
  
  },
  {
    "command": "system \"DLTOBJ OBJ(ILEDITOR/O_*) OBJTYPE(*FILE)\"",
    "code": 255,
    "stderr": "CPF2125: No objects deleted.",
  
  }
]
```
</details>

**Comment by m-tyler** [comment]
I am seeing this error on all functionality that uses the webview for its interface.

**Comment by m-tyler** [comment]
I updated to VSCODE version 1.83 and the web views are now working.

**Comment by chrjorgensen** [comment]
@m-tyler Thanks for reporting this - guess we can conclude that the VS Code version was the cause...
