### ISSUE TITLE
Command: IBM i: Compare with Selected and readonly open tabs does not remove readonly attribute

### ISSUE THREAD

**Issue by m-tyler** [codefori/vscode-ibmi#1584]
Command: IBM i: Compare with Selected and readonly open tabs does not remove readonly attribute.  When the context menu command `Select for Compare` and the command `IBM i: Compare with Selected` are selected the tool chooses the active tab in which to preload the input box for the member to compare to.  If this active tab happens to be for a member opened in read only mode the readonly attributes are appended to the open member string.

![image](https://github.com/codefori/vscode-ibmi/assets/1353665/b4d8424a-2eb5-4883-9534-ef1d48dd4312)

Expectations would be that the text `?readonly%3Dtrue` not appear in the input string.

This is a low priority for me as I can easily just remove that string or not open members in readonly when comparing.
<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.4.0|
|Visual Studio Code version|1.83.0|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code Spell Checker (code-spell-checker): 3.0.1
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.2
Db2 for IBM i (vscode-db2i): 0.5.0
ESLint (vscode-eslint): 2.4.2
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.14.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Markdown Language Features (markdown-language-features): 1.0.0
Markdown Math (markdown-math): 1.0.0
Markdown Preview Enhanced (markdown-preview-enhanced): 0.8.5
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
Partial Diff (partial-diff): 1.4.3
RPGLE (vscode-rpgle): 0.21.4
SQL Formatter VSCode (sql-formatter-vsc): 2.1.1
Text Marker (Highlighter) (text-marker): 1.11.0
Todo Tree (todo-tree): 0.0.226
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
classdiagram-ts (classdiagram-ts): 0.1.67
macros (macros): 1.2.1
undefined (indent-rainbow): 8.3.1
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|2|
|CCSID|37|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|git|iconv|GETNEWLIBL.PGM|||
|grep|setccsid||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>
</details>

**Comment by sebjulliand** [comment]
I'll look into that, I need some distraction 😅

**Comment by sebjulliand** [comment]
There you go 😉
