### ISSUE TITLE
Remove dupes from library list?

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-ibmi#1590]
https://github.com/codefori/vscode-ibmi/blob/75232f2e7d88abfdaadc77c3851abf77e44aa72c/src/api/CompileTools.ts#L517

**Comment by beckhamrryyaann** [comment]
@worksofliam could you give a little more info on what you are needing and I will look into? I'm just not sure what you mean in the subject and you referencing line 517 in 75232f2.  thanks

**Comment by worksofliam** [comment]
Hey @beckhamrryyaann 

We need to remove any duplicates from the end of the `ileSetup.libraryList` array between lines 517 and 539, before they are printed on line 545.

https://github.com/codefori/vscode-ibmi/blob/75232f2e7d88abfdaadc77c3851abf77e44aa72c/src/api/CompileTools.ts#L545.
