### ISSUE TITLE
Object browser issue

### ISSUE THREAD

**Issue by u031055** [codefori/vscode-ibmi#1592]
👉🏻 Issue text goes here.

We are trying to evaluate VS code for IBMi development in our CVS IBMi application before rolling the same out for DEV usage.
While performing the evaluation we ran into some issues, reaching out to this group to get feedback for resolving these issues.

Let me know if there is a separate forum that I should use to log these items for feedback, we may have more such items in upcoming weeks. Thanks

1. Unable to add Object Browser Filter once added. Tried Right Click+Delete Filter but created filter is not getting removed. Did refresh and also tried restarting VS code but did not work.

2. Similar issue with Profiles, once a profile is created I am unable to delete/remove it.

3. In few of our machines, we are runing into issues with adding object brower/source filters. Getting error ‘CPC2957: No records copied from file O_C4ZSGSMW in ZU031055.
CPF2817: Copy command ended because of error.’
We have validated system temporary setting’s to ensure Temporary library(ZU031055) and Temporary IFS directory are setup correctly. This is holding many developers to evaluate Code for IBMi.

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.4.0|
|Visual Studio Code version|1.74.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.2
Configuration Editing (configuration-editing): 1.0.0
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.18
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|n/a|
|CCSID|65535|
|SQL|Disabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|ZU031055.GETNEWLIBL|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv||||
|git|setccsid||||
|ls|tar||||
|md5sum|||||
|sort|||||
|stat|||||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"QSYS/CPYTOIMPF FROMFILE(ZU031055/O_C4zSGsMW O_C4zSGsMW) TOSTMF('/home/u031055/vscodetemp-O_TiCu1dVS') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)\"",
    "code": 255,
    "stderr": "CPC2957: No records copied from file O_C4ZSGSMW in ZU031055.\nCPF2817: Copy command ended because of error.",
    "cwd": "/home/U031055"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"u031055\" && export HOST=\"rxcdev\" && export HOME=\"/home/U031055\" && export LIBLS=\"SOFTMENU2X DBU11 SSAPRDOBJ SSAPRDFIL CDAPRDSRC CDAPRDFIL CDAPRDOBJ CDAQATOBJ CDADEVOBJ UTDPRDOBJ UTDPRDFIL UTCPRDOBJ UTCPRDFIL QUSRTOOL TAATOOL V2SYRPG V2SYCBL V2SYVENG V2SY Y28110524 V1SYVENG V1SY APIUTILS QATUTILS QGPL CLMPRDOBJ CLMQATOBJ CLMINDOBJ MSBDEVEXT CLMDEVEXT CLMDEVOBJ CLMDEVFIL COMPRDOBJ COMQATOBJ COMINDOBJ COMDEVOBJ COMDEVFIL APIPRDOBJ APIPRDSRC APIQATOBJ APIINDOBJ APIDEVOBJ APIDEVFIL MSBDEVFIL APICETFIL ELGDEVFIL EZTDEVFIL ECLDEVFIL O_Y2GEN70 O_Y2GEN86 V5R12EPTF1 RTOPRDOBJ RTOQATOBJ RTODEVOBJ QMOD APCSGPL APCSGPL2 CMKPRDGPL QTEMP\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/U031055"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"u031055\" && export HOST=\"rxcdev\" && export HOME=\"/home/U031055\" && export LIBLS=\"SOFTMENU2X DBU11 SSAPRDOBJ SSAPRDFIL CDAPRDSRC CDAPRDFIL CDAPRDOBJ CDAQATOBJ CDADEVOBJ UTDPRDOBJ UTDPRDFIL UTCPRDOBJ UTCPRDFIL QUSRTOOL TAATOOL V2SYRPG V2SYCBL V2SYVENG V2SY Y28110524 V1SYVENG V1SY APIUTILS QATUTILS QGPL CLMPRDOBJ CLMQATOBJ CLMINDOBJ MSBDEVEXT CLMDEVEXT CLMDEVOBJ CLMDEVFIL COMPRDOBJ COMQATOBJ COMINDOBJ COMDEVOBJ COMDEVFIL APIPRDOBJ APIPRDSRC APIQATOBJ APIINDOBJ APIDEVOBJ APIDEVFIL MSBDEVFIL APICETFIL ELGDEVFIL EZTDEVFIL ECLDEVFIL O_Y2GEN70 O_Y2GEN86 V5R12EPTF1 RTOPRDOBJ RTOQATOBJ RTODEVOBJ QMOD APCSGPL APCSGPL2 CMKPRDGPL QTEMP\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/U031055"
  }
]
```
</details>

**Comment by worksofliam** [comment]
You are on an older version of VS Code, 1.74. Please upgrade to 1.83.

**Comment by digvijay2k2** [comment]
Thanks Liam, are all these issues related to older version ?
Re-confirming as this object browser issue is not occurring  for all developers but few selective. Thanks

**Comment by worksofliam** [comment]
@digvijay2k2 It could well be. We generally only support ~0.03 versions of VS Code.
