### ISSUE TITLE
Don't allow it to connect to IBM i if password and private key are not specified at the same time

### ISSUE THREAD

**Issue by william-xiang** [codefori/vscode-ibmi#1599]
On IBM i Login, if both password and private key are not specified, the connect button can still be clicked, and it will try to use the ssh keys in the local machine for ssh. But those keys may not the one for IBM i machine. 

It would be better to not enable the connect button if both password and private keys are not specified at the same time. 

https://github.com/codefori/vscode-ibmi/assets/24379419/1d9cd625-4807-4533-ae1f-fe48e637d35a

**Comment by worksofliam** [comment]
Actually solved this in #1911 which will be out with 2.9.0.
