### ISSUE TITLE
Cannot manage ibm I objects

### ISSUE THREAD

**Issue by MauroCroci** [codefori/vscode-ibmi#1601]
Hi, I have installed IBM i Development Pack for Visual Studio Code and i can see all objects in IFS browser, but nothing in Object Browser, if I try to create a source file in a library (example QCLSRC) it works, but i can't see it in Object Browser, I tried to manage settings and filters of my library (XMAURO) but without results.
Thanks in advance

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.4.0|
|Visual Studio Code version|1.83.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 9.10.15
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.2
Db2 for IBM i (vscode-db2i): 0.5.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.14.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.21.4
Remote - SSH (remote-ssh): 0.106.5
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4|
|Tech Refresh|n/a|
|CCSID|1144
![Cattura](https://github.com/codefori/vscode-ibmi/assets/24793962/daf4c97e-58f8-4e55-b522-2e157dc8af56)
|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|grep|setccsid||||
|ls|tar||||
|md5sum|||||
|sort|||||
|stat|||||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "export BUILDLIB=\"BOADBF\" && export CURLIB=\"BOADBF\" && export USERNAME=\"qpgmr\" && export HOST=\"192.168.109.19\" && export HOME=\"/\" && export LIBLS=\"XMAURO\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=BOADBF: is not an identifier",
    "cwd": "/"
  },
  {
    "command": "export BUILDLIB=\"BOADBF\" && export CURLIB=\"BOADBF\" && export USERNAME=\"qpgmr\" && export HOST=\"192.168.109.19\" && export HOME=\"/\" && export LIBLS=\"XMAURO\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=BOADBF: is not an identifier",
    "cwd": "/"
  },
  {
    "command": "export BUILDLIB=\"BOADBF\" && export CURLIB=\"BOADBF\" && export USERNAME=\"qpgmr\" && export HOST=\"192.168.109.19\" && export HOME=\"/\" && export LIBLS=\"XMAURO\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=BOADBF: is not an identifier",
    "cwd": "/"
  }
]
```
</details>

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the list doesn't appear.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by MauroCroci** [comment]
Thanks for your quick answer.
![Cattura2](https://github.com/codefori/vscode-ibmi/assets/24793962/d2a620d0-cffb-42e1-a0d0-68cfe73eb92e)

**Comment by sebjulliand** [comment]
Hi @MauroCroci , it seems that `bsh` is interfering here. Can you try making `bash` your default shell, following the instructions here? https://ibmi-oss-docs.readthedocs.io/en/latest/troubleshooting/SETTING_BASH.html

**Comment by MauroCroci** [comment]
Thanks, I followed instructions in SQL MODE:  CALL QSYS2.SET_PASE_SHELL_INFO('CROCI', '/QOpenSys/pkgs/bin/bash')
I saw that in table created through the command there is the list of all object in my library XMAURO but in Visual Code I don't see the object list and I have this
![Cattura3](https://github.com/codefori/vscode-ibmi/assets/24793962/029569ca-2ae0-4c93-81b2-63036e1b2c51)
 log:

**Comment by sebjulliand** [comment]
OK so now you can have a look at the Tip page in our documentation, especially this part about SQL returning no results: https://codefori.github.io/docs/#/pages/tips/setup?id=no-results-from-sql-execution
That may sort it out 😄

**Comment by MauroCroci** [comment]
Thanks, I tried but I have the same problem, this is what I see after the fix made with putty (I cannot use qsecofr and I don't know if this could be a problem).
![Cattura4](https://github.com/codefori/vscode-ibmi/assets/24793962/e837ea61-bb26-416d-894c-f0012e1497b4)
