### ISSUE TITLE
I don't see my library in user library list

### ISSUE THREAD

**Issue by GiuGitHub** [codefori/vscode-ibmi#1604]
Hi, I can't view any libraries in user library list, even though the connection was successful. What could I have done wrong? Thanks for all

**Comment by sebjulliand** [comment]
Hi,
you probably have installed the `IBM i Project Explorer` extension.

Either disable it of you don't use it or uncheck this preference and reload VSCode to make the Library List view available again.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/a52e0238-5d03-4913-8b26-cb6dc22c85f7)

**Comment by GiuGitHub** [comment]
Hi, thank you for the answer, I checked but I don't have installed the extension that you wrote to me, I show you the pack I installed  
<img width="324" alt="Pack" src="https://github.com/codefori/vscode-ibmi/assets/99175275/2572bc1e-883d-4539-829a-47e4cebcb032">

**Comment by sebjulliand** [comment]
Hmm, the view shows up but is empty, my bad.
Do you have any errors in the Code for i output?

**Comment by GiuGitHub** [comment]
No I haven't error, the pack I installed is: IBM i Development Extension Pack 
IBM i and language specific
[Code for IBM i]
[IBMi Languages]
[RPGLE]
[COBOL]
[CL]
[RPGLE Free]
[Code for IBM i Walkthroughs]
[IBM i Notebooks]
[Db2 for IBM i]
[IBM i Renderer]
[Error Lens]
[TODO Highlight]
Otherwise, could you recommend a tutorial for me to follow please?

**Comment by worksofliam** [comment]
Can you share a screenshot of what you're seeing?

**Comment by GiuGitHub** [comment]
Yes, thanks for your support
<img width="200" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/99175275/00aa1425-8559-49ff-84d3-fcfb832da9de">

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the list doesn't appear.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by GiuGitHub** [comment]
sorry, I didn't explain myself very well, my English isn't the best... I was following a tutorial where as soon as you connected to the IBM i with your user account it loaded the libraries, do I have to run some commands to be able to view them?

**Comment by worksofliam** [comment]
@GiuGitHub No worries, we really need that output channel data as I mentioned above.
