### ISSUE TITLE
Opening IFS shortcut works but throws error message "cannot stat '.*'"

### ISSUE THREAD

**Issue by jwoehr** [codefori/vscode-ibmi#1606]
Save us time! Click 'Report an Issue' from the Help and Support panel inside of VS Code after you have connected to a system.

**Describe the bug**
As of recently, opening any IFS shortcut to my home directory produces an error message, though it seems to work okay.

> /QOpenSys/pkgs/bin/stat: cannot stat '.*': A file or directory in the path name does not exist.

**To Reproduce**
1. Open any IFS shortcut
2. See error

**Expected behavior**
No error message

**Screenshots**
![Screenshot from 2023-10-20 11-35-44](https://github.com/codefori/vscode-ibmi/assets/4604036/3c949d86-f01b-4301-9f74-969fed568af4)

**Environment (please complete the following information):**
 - Extension version v2.4.0
 - IBM i OS version 7.5

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the error appears.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by jwoehr** [comment]
Nothing:
![image](https://github.com/codefori/vscode-ibmi/assets/4604036/bef08501-e93f-402d-baa6-c4f113d924ae)

**Comment by worksofliam** [comment]
@jwoehr Looks like you're on the Tasks output channel there, but our logs go to the Code for IBM i output channel. You can change it in the dropdown in top-right of the panel.

**Comment by jwoehr** [comment]
D'oh ...
```
/home/JWOEHR: cd '/home/JWOEHR/work' && /QOpenSys/pkgs/bin/stat --dereference --printf="%A	%h	%U	%G	%s	%Y	%n
" * .*  
{
    "code": 1,
    "signal": null,
    "stdout": "drwxr-sr-x\t3\tjwoehr\tUNKNOWN\t8192\t1697815603\tBamberger\ndrwxr-sr-x\t3\tjwoehr\tUNKNOWN\t8192\t1677696482\tCamel\ndrwxr-sr-x\t2\tjwoehr\tUNKNOWN\t8192\t1680131200\tDDS\ndrwxr-sr-x\t3\tjwoehr\tUNKNOWN\t8192\t1691019318\tGoAccess\ndrwxr-sr-x\t8\tjwoehr\tUNKNOWN\t12288\t1678723844\tGoogle\ndrwxr-sr-x\t5\tjwoehr\tUNKNOWN\t28672\t1664503431\tIBMiUnit\ndrwxr-sr-x\t3\tjwoehr\tUNKNOWN\t8192\t1685739203\tILEastic\ndrwxr-sr-x\t3\tjwoehr\tUNKNOWN\t8192\t1652389101\tNode\ndrwxr-sr-x\t3\tjwoehr\tUNKNOWN\t8192\t1674431974\tOATTravel\ndrwxr-sr-x\t5\tjwoehr\tUNKNOWN\t8192\t1668989351\tOAuth\ndrwxr-sr-x\t3\tjwoehr\tUNKNOWN\t8192\t1664449246\tOSSILE\ndrwxr-sr-x\t3\tjwoehr\tUNKNOWN\t8192\t1696612354\tOpenPyxl\ndrwxr-sr-x\t6\tjwoehr\tUNKNOWN\t8192\t1695737625\tPACCAR\ndrwxr-sr-x\t2\tjwoehr\tUNKNOWN\t8192\t1683862877\tPHP\ndrwxr-sr-x\t10\tjwoehr\tUNKNOWN\t24576\t1687707613\tPython\ndrwxr-sr-x\t3\tjwoehr\tUNKNOWN\t8192\t1685934512\tReactPHP\ndrwxr-sr-x\t2\tjwoehr\tUNKNOWN\t8192\t1687463038\tUDTF\ndrwxr-sr-x\t5\tjwoehr\tUNKNOWN\t12288\t1688097757\tVarietyWholesale\ndrwxr-sr-x\t2\tjwoehr\tUNKNOWN\t12288\t1671557099\tapache-camel\ndrwxr-sr-x\t31\tjwoehr\tUNKNOWN\t24576\t1684361130\tbob-recursive-example\ndrwxr-sr-x\t3\tjwoehr\tUNKNOWN\t8192\t1685063015\tc\ndrwxr-sr-x\t2\tjwoehr\tUNKNOWN\t8192\t1668107045\tcl\ndrwxr-sr-x\t2\tjwoehr\tUNKNOWN\t8192\t1676337132\tcobol\ndrwxr-sr-x\t4\tjwoehr\tUNKNOWN\t8192\t1687201997\tgforth\ndrwxr-sr-x\t9\tjwoehr\tUNKNOWN\t28672\t1695150413\tiledocs-page-builder\ndrwxr-sr-x\t5\tjwoehr\tUNKNOWN\t8192\t1664676639\tmigrate\ndrwxr-sr-x\t11\tjwoehr\tUNKNOWN\t24576\t1695150352\tnoxDB\ndrwxr-sr-x\t3\tjwoehr\tUNKNOWN\t8192\t1672182352\trcs\ndrwxr-sr-x\t2\tjwoehr\tUNKNOWN\t8192\t1668719897\trest\ndrwxr-sr-x\t7\tjwoehr\tUNKNOWN\t8192\t1696134069\trpg\ndrwxr-sr-x\t14\tjwoehr\tUNKNOWN\t24576\t1679407420\tublu\ndrwxr-sr-x\t3\tjwoehr\tUNKNOWN\t8192\t1685737798\tuserstuff\ndrwxr-sr-x\t8\tjwoehr\tUNKNOWN\t24576\t1664554542\twkhtmltopdf",
    "stderr": "/QOpenSys/pkgs/bin/stat: cannot stat '.*': A file or directory in the path name does not exist."
}
```

**Comment by worksofliam** [comment]
@jwoehr Just to confirm, the list still appears but you're also getting this error message?

**Comment by jwoehr** [comment]
> @jwoehr Just to confirm, the list still appears but you're also getting this error message?

That is correct. I'm working thru that to see if all the files appear.

**Comment by jwoehr** [comment]
Hmm, looks like this only happens on one 7.5 server. Investigating ...

**Comment by chrjorgensen** [comment]
I have this error message too - haven't investigated it but the server is on 7.5 and bash 5.2.

**Comment by chrjorgensen** [comment]
The same error occurs on 7.3 - and it's when there's no hidden files (filename preceded with dot) in the directory.
I wonder why this is happening now... something must have changed in the `stat` command...

**Comment by sebjulliand** [comment]
I guess https://github.com/codefori/vscode-ibmi/pull/1659 fixed that!

**Comment by chrjorgensen** [comment]
@sebjulliand Exactly! 😄
