### ISSUE TITLE
Problem with CLLE lint

### ISSUE THREAD

**Issue by edoardomessa** [codefori/vscode-ibmi#1614]
Hi,
when I make this command:
![Screenshot 2023-10-25 alle 12 08 58 PM](https://github.com/codefori/vscode-ibmi/assets/148963214/4461d8f9-1f82-4578-9be3-98f1f8cdd717)

after the /*FIRST all become comment.
Thanks,
Edoardo

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.4.0|
|Visual Studio Code version|1.83.1|
|Operating System|darwin_arm64|

<details>
<summary>Active extensions</summary>

```
CL (vscode-clle): 1.1.2
COBOL (cobol): 9.10.16
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.2
Db2 for IBM i (vscode-db2i): 0.5.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.15.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
Git Graph (git-graph): 1.30.0
GitHub (github): 0.0.1
GitLab Workflow (gitlab-workflow): 3.81.0
GitLens — Git supercharged (gitlens): 14.4.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.22.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|8|
|CCSID|280|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|vscode.GETNEWLIBL|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv||||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash

_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "£§$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(vscode) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2158: La libreria VSCODE esiste nell'unità ASP DIRECTA1.\nCPF2111: La libreria VSCODE esiste già."
  },
  {
    "command": "system \"DLTOBJ OBJ(vscode/O_*) OBJTYPE(*FILE)\"",
    "code": 255,
    "stderr": "CPF2125: Non è stato cancellato alcun oggetto."
  }
]
```
</details>

**Comment by chrjorgensen** [comment]
@edoardomessa This is not an error in the linter - it's an error in the CL configuration in the [IBMi Languages](https://marketplace.visualstudio.com/items?itemName=barrettotte.ibmi-languages) extension... it treats `/*` as beginning of comment regardless of the context...

Please submit an issue in the [repo](https://github.com/barrettotte/vscode-ibmi-languages) over there. Thanks.
