### ISSUE TITLE
Copies with non-latin characters

### ISSUE THREAD

**Issue by HenryMiller** [codefori/vscode-ibmi#1617]
Hello,

All /copy source members with a £ or $ don't open by pressing "F12 = Definition".
All other source members open without problems.
I tried on 3 different Ibm I servers including Pub400.com.

<img width="337" alt="image" src="https://github.com/halcyon-tech/vscode-ibmi/assets/1829995/45bc9f87-49bc-4bf9-89c8-f0d4c7f5402c">

<img width="656" alt="image" src="https://github.com/halcyon-tech/vscode-ibmi/assets/1829995/126b81b0-d170-4af2-ad37-4557c1381428">

<img width="654" alt="image" src="https://github.com/halcyon-tech/vscode-ibmi/assets/1829995/92008d3e-d7ad-4d9f-9c7a-01c77d6f7002">

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.3.1|
|Visual Studio Code version|1.82.3|
|Operating System|darwin_arm64|

<details>
<summary>Active extensions</summary>

```
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code Runner (code-runner): 0.12.0
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.2
Db2 for IBM i (vscode-db2i): 0.5.0
ESLint (vscode-eslint): 2.4.2
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitLens — Git supercharged (gitlens): 14.3.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Jira and Bitbucket (Atlassian Labs) (atlascode): 3.0.6
Live Server (LiveServer): 5.7.9
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
RPGLE (vscode-rpgle): 0.21.4
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
YAML (vscode-yaml): 1.14.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|n/a|
|CCSID|273|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/HMILLER1.lib||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|HMILLER1.GETNEWLIBL|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|||||
|git|setccsid|||||
|grep||||||
|ls||||||
|md5sum||||||
|sort||||||
|stat||||||
|tar||||||
|tn5250||||||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#§$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"HMILLER\" && export HOST=\"pub400.com\" && export HOME=\"/home/HMILLER\" && export LIBLS=\"HMILLER2 HMILLER1 GAMES400 QTEMP QGPL\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/HMILLER"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"HMILLER\" && export HOST=\"pub400.com\" && export HOME=\"/home/HMILLER\" && export LIBLS=\"HMILLER2 HMILLER1 GAMES400 QTEMP QGPL\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/HMILLER"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"HMILLER\" && export HOST=\"pub400.com\" && export HOME=\"/home/HMILLER\" && export LIBLS=\"HMILLER2 HMILLER1 GAMES400 QTEMP QGPL\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/HMILLER"
  }
]
```
</details>

**Comment by HenryMiller** [comment]
No worries, that's absolutely fine.

**Comment by worksofliam** [comment]
Attached PR will solve includes with `$` in it (like your example)

**Comment by HenryMiller** [comment]
Hi, 
still not working on my side.

<img width="964" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/1829995/7653e307-9e83-453f-9a55-b7ca7b22a5bb">

**Comment by worksofliam** [comment]
Likely something to do with that £ going through your shell. Can you run 'ls /QSYS.LIB/<THELIB>.LIB/<THEFILE>.FILE/*' against the source file that has the member with the £ in it?

**Comment by HenryMiller** [comment]
Hi, 
you are right, I got "not found" and this is weird.


-bash-5.2$ ls '/QSYS.LIB/SMEPER.LIB/SRC.FILE/X1SER_66U.MBR' 
/QSYS.LIB/SMEPER.LIB/SRC.FILE/X1SER_66U.MBR
-bash-5.2$ ls '/QSYS.LIB/SMEPER.LIB/SRC.FILE/X1SER_66U.MBR' 
/QSYS.LIB/SMEPER.LIB/SRC.FILE/X1SER_66U.MBR
-bash-5.2$ ls '/QSYS.LIB/SMEPER.LIB/SRC.FILE/B£DEC0XB.MBR'
/QSYS.LIB/SMEPER.LIB/SRC.FILE/B£DEC0XB.MBR not found

**Comment by worksofliam** [comment]
@chrjorgensen don't we have an API that will take care of these types of characters in the shell? I forget.

**Comment by chrjorgensen** [comment]
@worksofliam I can't recreate the issue on my system...

@HenryMiller Please verify you are on the latest version of Code for IBM i and the RPGLE extensions!

Your screenshot with `QILEGEN` not found does not make sense: there are no variant characters in that name, and it should be found without any problem - IF it can be found in the library list!

Things working in 5250 session may not work in VS Code - 5250 is in EBCDIC, whereas VS Code is in UTF-8, so there's a lot conversion going on between codepages. The variant characters (#@$ in EBCDIC 37 (US)) are always causing trouble, and you should verify your codepage setup according to the documentation here: [https://codefori.github.io/docs/#/pages/tips/ccsid](https://codefori.github.io/docs/#/pages/tips/ccsid)

**Comment by HenryMiller** [comment]
Hi @chrjorgensen ,
My QCCSID DSPSYSVAL is 1144,my USER PROFILE has Qccsid 1144 as well and I 'm  running "Code for IBM i
v2.6.1"
I think that's something related to OS/400 itself, as it is not able to find the member from QSH or a SSH session  as well.
-bash-5.2$ ls '/QSYS.LIB/SMEPER.LIB/SRC.FILE/B£DEC0XB.MBR'
**/QSYS.LIB/SMEPER.LIB/SRC.FILE/B£DEC0XB.MBR not found**

**Comment by chrjorgensen** [comment]
Happy New Year @HenryMiller !

The effects of your CCSID 1144 is only visible in 5250 and SQL output - QSHELL and PASE (bash) uses CCSID 37.... and your variant characters (like £) is shown / returned in the CCSID 37 (US) form of #. Try running your bash command like this

```bash
ls '/QSYS.LIB/SMEPER.LIB/SRC.FILE/B*.MBR'
```

and you will see what I mean. CCSID is just a tag, telling how to present the binary data - the binary value of # is presented differently in CCSID 37 (#) and CCSID 1144 (£).

CPYTOSTMF on the other hand recognizes your CCSID 1144 and converts the filename accordingly.

So bottom line is, CCSID is handled differently in native environment (5250, SQL, commands) than in shell environments (QSHELL, PASE). It is important to set your PASE environment correctly, since VS Code uses SSH and thus PASE to get the information from the IBM i server. Read more here: https://codefori.github.io/docs/#/pages/tips/ccsid?id=setting-environment-variables

VS Code errors in IBM i object names (library, file, member) is a sign of misconfiguration of the PASE (or maybe even IBM i) environment...

All this talk about CCSID is not relevant for your case of QILEGEN member not found - since there are no variant characters (#@$ in CCSID 37) in the name and thus no conversion necessary. To me it looks more like the library list is wrong, not including the library containing QILEGEN, or the [RPGLE extension](https://github.com/codefori/vscode-rpgle) is outdated. Please verify the library list is correct and that all your extensions are updated.

**Comment by HenryMiller** [comment]
Happy New Year @chrjorgensen !
Thank you for your post.
I did manually add QIBM_PASE_CCSID     '1208'   and PASE_LANG 'IT_IT'  system environment variables , even if I am on V7R4,  and now everything looks ok.
Thank you so much, really appreciated!!!!

**Comment by chrjorgensen** [comment]
@HenryMiller Glad to hear it is working for you now! :smiley:
