### ISSUE TITLE
Trying to start debug but getting an error

### ISSUE THREAD

**Issue by SvenGJansson** [codefori/vscode-ibmi#1626]
👉🏻I'm trying to start and run debugger, but I get an error I do not understand. Here is a screen shot:
![image](https://github.com/codefori/vscode-ibmi/assets/106283611/983cfb8b-fbef-4bc3-a59a-cd616348e4a8)

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.4.0|
|Visual Studio Code version|1.84.0|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.5.1
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Debug (ibmidebug): 1.0.0
IBM i system debugger (ibm-i-run-system-debugger-in-acs): 0.0.1
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.23.0
Remote - SSH (remote-ssh): 0.107.0
Remote Explorer (remote-explorer): 0.4.1
Server Ready Action (debug-server-ready): 1.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|7|
|CCSID|278|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/usr/bin||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|
|attr|ILEDITOR.GETNEWLIBL|QZDFMDB2.PGM|startDebugService.sh|
|iconv||||
|ls||||
|setccsid||||
|tar||||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "ÄÖÅ"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CPYTOSTMF FROMMBR('/QSYS.lib/R03754.lib/VSCODE.file/RPGLINT.mbr') TOSTMF('/tmp/vscodetemp-O_uqZlvUDX') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(278)\"",
    "code": 255,
    "stderr": "CPFA0A9: Object not found.  Object is /QSYS.lib/R03754.lib/VSCODE.file/RPGLINT.mbr.\nCPFA097: Object not copied.  Object is /QSYS.lib/R03754.lib/VSCODE.file/RPGLINT.mbr.",
    "cwd": "."
  },
  {
    "command": "system \"CPYTOSTMF FROMMBR('/QSYS.lib/R03754.lib/VSCODE.file/RPGLINT.mbr') TOSTMF('/tmp/vscodetemp-O_uqZlvUDX') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(278)\"",
    "code": 255,
    "stderr": "CPFA0A9: Object not found.  Object is /QSYS.lib/R03754.lib/VSCODE.file/RPGLINT.mbr.\nCPFA097: Object not copied.  Object is /QSYS.lib/R03754.lib/VSCODE.file/RPGLINT.mbr.",
    "cwd": "."
  },
  {
    "command": "export BUILDLIB=\"R03754\" && export CURLIB=\"R03754\" && export USERNAME=\"r03754\" && export HOST=\"rbpte.ibmi.resurs.com\" && export HOME=\"/home/R03754\" && export LIBLS=\"" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=R03754: is not an identifier",
    "cwd": "/home/R03754"
  }
]
```
</details>

**Comment by mkwan01** [comment]
This is a generic error message, which does not provide too much useful information.

Questions:
1. How do you start the debug service? Do you see any error when starting the debug service?
2. How do you generate the certificate and where does the certificate file exist?

**Comment by mkwan01** [comment]
Please note that you need to specify the password when you create the IBM i connection. If the password is not specified, you can get this error message. Please verify whether the password is specified for your connection.

**Comment by duieolson** [comment]
I am getting this error as well.  Has anyone found a solution?
When I kickoff the debug(call of the program), it prompts me for my password(I chose this as I am forced to change passwords often). It takes the password fine and moves on.  But throws the exact same message as above.
Debugger, Debug Service and Debug Server are all running.
![image](https://github.com/codefori/vscode-ibmi/assets/124823426/9d9b359c-6ebb-4f25-96db-0fad3921c73d)
I started them from New Nav for i on the TCP server screen.  Above image.

I went thru the VSCode setup Debugger walkthrough and generated the certs, overlaying what existed.  Didn't matter.
I have no idea where to go from here.

Code for IBM i version   2.4.0
IBM i Debug version  1.0.0

VSCode
Version: 1.85.1 (system setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by mkwan01** [comment]
@duieolson Please try to get the output of the debug service and attach it to this issue. Depending on how you start the debug service, the output may appear in a QPRINT file of a JVM process or directly appear in the green screen console.
