### ISSUE TITLE
Getting error when opening a source member in CL

### ISSUE THREAD

**Issue by sherimc** [codefori/vscode-ibmi#1627]
[Error - 8:56:56 AM] Request textDocument/documentSymbol failed.
  Message: Request getFileDefinition failed unexpectedly without providing any details.
  Code: -32603 
<hr />

![image](https://github.com/codefori/vscode-ibmi/assets/80354710/9e1dbeb3-a0b6-458a-ba04-a334c5673696)

|Context|Version|
|-|-|
|Code for IBM i version|2.4.0|
|Visual Studio Code version|1.83.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
ARCAD-CodeChecker (arcad-codechecker): 1.0.1
ARCAD-Elias (arcad-elias): 1.6.0
CL (vscode-clle): 1.1.2
COBOL (cobol): 9.10.16
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.5.1
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.15.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitHub Pull Requests and Issues (vscode-pull-request-github): 0.76.0
IBM i Debug (ibmidebug): 1.0.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
JavaScript Debugger (js-debug): 1.83.1
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.23.0
Server Ready Action (debug-server-ready): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|n/a|
|Tech Refresh|n/a|
|CCSID|?|
|SQL|Disabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|git|iconv|GETNEWLIBL.PGM|||
|ls|setccsid||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=WDWBMSSM1
CURLIB=WDWBMSSM1
HOME=/home/######
HOST=windev1
LIBLS=###### COPYLIB COOLSPV7R1 WINCUSPRP PROFOUNDUI RXS LOG4ILE QMQM GECCLIB ASCCOM1 CRYPTOKS CRYPTO QTEMP TAATOOL QGPL PGM460 PGMLPAR DTAMST SHR460 DTALPAR DTAWISE DTA350 #LIBRARY
LOGIN=######
LOGNAME=######
MAIL=/var/spool/mail/######
OLDPWD=/home/######
PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/######
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=10.99.0.88 54913 22
SSH_CONNECTION=10.99.0.88 54913 10.10.0.135 22
TZ=<EST>5<EDT>,M3.2.0,M11.1.0
USER=######
USERNAME=######
_=/QOpenSys/usr/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"QSYS/CPYTOIMPF FROMFILE(ILEDITOR/RSA5379049 RSA5379049) TOSTMF('/tmp/vscodetemp-O_XlQEb3KO') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)\"",
    "code": 255,
    "stderr": "CPF2817: Copy command ended because of error.",
    "cwd": "/home/######"
  },
  {
    "command": "system \"QSYS/CPYTOIMPF FROMFILE(ILEDITOR/RAC0621619 RAC0621619) TOSTMF('/tmp/vscodetemp-O_0Bk9oVDU') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)\"",
    "code": 255,
    "stderr": "CPF2817: Copy command ended because of error.",
    "cwd": "/home/######"
  },
  {
    "command": "system \"QSYS/CPYTOIMPF FROMFILE(ILEDITOR/RSA6816093 RSA6816093) TOSTMF('/tmp/vscodetemp-O_URZ4CIVt') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)\"",
    "code": 255,
    "stderr": "CPF2817: Copy command ended because of error.",
    "cwd": "/home/######"
  }
]
```
</details>

**Comment by worksofliam** [comment]
Please share some CL source so we can recreate this issue.

**Comment by sherimc** [comment]
> Please share some CL source so we can recreate this issue.

Does it matter where I start to copy?  When I open the source code the line that appears is this one.
`
             CHGDTAARA  DTAARA(*LDA (21 020)) VALUE('                 +
                             ')

/* LKS - SECURITY MODIFICATION - 3.90 */

             MONMSG     MSGID(WSE0003) EXEC(GOTO CMDLBL(CNCRQS))
             CALL       PGM(AC06CL) PARM('SA62A')

             CALL       PGM(CHKPRTR) PARM(&PROG &PRTF)

/*M006*/     CallSubr   GetQNTCprf
/*M006 *dlt  CALL       PGM(SA62D) PARM(&PRTF) /*Submit Monthend +  */
/*M006*/     CALL       PGM(SA62D) PARM(&PRTF &QNTCusrPrf) /*Submit Monthend +
                          Reports */
             GOTO       CMDLBL(ENDPGM)

BATCH:
    /*m007   CLRPFM     FILE(&FLIB/SA62O)  */
             CLRPFM     FILE(SA62OT) /*M007*/
    /*m007   OVRDBF     FILE(SA62O) TOFILE(&FLIB/SA62O) */

/*M003*/
/*M003 M007  CLRPFM     FILE(&FLIB/SA62EP)  */
             CLRPFM     FILE(SA62ET) /*m007*/
/*M003*/
             CHGVAR     VAR(&PREFIX) VALUE(%SST(*LDA 240 2))
             CALL       PGM(CHKPRTR) PARM(&PROG &PRTF)`

**Comment by worksofliam** [comment]
@sherimc If you update the CL extension to 1.1.4 (or 1.1.3), do you still get the issue?
