### ISSUE TITLE
Cannot delete a directory if is the `Workspace Deploy Location`

### ISSUE THREAD

**Issue by edmundreinhardt** [codefori/vscode-ibmi#1631]
Full description with images and context found here https://github.com/IBM/vscode-ibmi-projectexplorer/issues/250
In the comments Seb says he knows what the issue is (current directory needs to be changed before attempting delete)
This is true even if the deploy location has been changed but no deploy has been attempted yet.

**Describe the bug**
Set an IFS directory to be the Workspace Deploy Location via the IFS Browser

Deploy to the directory

Switch deploy to location to any other directory

Now try to delete the original directory

This delete fails
https://user-images.githubusercontent.com/11184579/280388103-9e54b3f9-e6f2-4f7c-add2-597b9afbc6ca.png

According to Seb
Hey guys, I looked at the code in Code for i and rerproduced the issue as well.
However, it's not related to .bashrc, in my opinion. Why the deletion fails is simple: when deploying, the deploy location becomes the new current directory then the deployment commands and run. After that, trying to delete the deployment directory fails because you're basically trying to cut the branch you're seating on 😅

When running a command, we can see the current directory on the left side:
![image](https://github.com/codefori/vscode-ibmi/assets/11184579/979f772d-f1a8-452b-b3ae-5dee4ea9160d)

I'll make a note to handle this case in Code for i. In the case the user deletes the current deploy location, we'll make ~ the new current directory.

**Comment by edmundreinhardt** [comment]
@sebjulliand I don't think I have sufficent access to assign you to this issue

**Comment by worksofliam** [comment]
@sebjulliand Was the PR for this already merged?

**Comment by worksofliam** [comment]
Got it!! Well silly me has been using the IFS Browser for a bit. Let me get that sorted today.

**Comment by sebjulliand** [comment]
> Got it!! Well silly me has been using the IFS Browser for a bit. Let me get that sorted today.

You're a diamond!
