### ISSUE TITLE
Specify currentLibrary for different profiles

### ISSUE THREAD

**Issue by Alastyr** [codefori/vscode-ibmi#1640]
It would be really useful if you could specify a different current library for each profile.
It happens that you work on different projects and the library list changes between projects, so current library should change between projects too.

Current settings.json
![image](https://github.com/codefori/vscode-ibmi/assets/1959505/8c6d7224-1982-4193-a3fe-07a7cf61d7d0)

settings.json would be nice to have
![image](https://github.com/codefori/vscode-ibmi/assets/1959505/0b2c113a-bb24-4767-a28b-d4867c3ce7c6)

**Comment by beckhamrryyaann** [comment]
@Alastyr I set down to try and add this feature and it seems this ability is already in place.
When creating the "Command Profile" you use the CHGLIBL command to set your library list.  You can also add the CURLIB parameter to set the current library for each profile you need to use.  Does this answer your question or was you trying to use the command profiles another way?

<img width="758" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/6051612/6a51de6d-1014-49fa-8dfb-4b5a5870db12">

**Comment by worksofliam** [comment]
@beckhamrryyaann i don't think that's what they are referring to.

When you use regular profiles (not command profiles that you spoke about) it does not store the current library with the program.

**Comment by beckhamrryyaann** [comment]
@worksofliam In the screen shot the user provided, they added the current libraries property to the object in the Command Profiles array.  (see the image he provided).  I also looked at the normal profiles as well but it seems like in my testing it also remembered the current library with "normal" profiles as well.  That is what had me confused.

**Comment by worksofliam** [comment]
Odd! Well we don't store a library list or current library with command profiles - just the command to set them, so it was an assumption on my end too.

**Comment by Alastyr** [comment]
@beckhamrryyaann your answer is good but I don't use the command "CHGLIBL". I use my own command to change library list that doesn't change the CURLIB. Yes, i should change my own command to handle CURLIB param, but I don't think this could be the right way. 
Moreover, in my example I put "currentLibrary" in command profiles array, but as @worksofliam suggested, someone should use regular profiles and would like to specify currentLibrary for each regular profile.

**Comment by beckhamrryyaann** [comment]
Thank you @Alastyr for your feedback.  I thought this might be the case where you were using your own custom command but I wanted to be sure.

@worksofliam I included a screen shot of what I was thinking.  I updated the add/edit command profile web view and added the Current Library setting.  If a user types in a library in this new field that would get saved to the settings.json and also would be used as their current library when the profile is activated?  Do you like this direction? 
<img width="589" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/6051612/32293941-a309-4a29-8f7b-6f710d037a23">

**Comment by beckhamrryyaann** [comment]
@worksofliam If you self assign the issue to yourself does that mean you will take care of the issue?  So I should no longer try to work on this issue?  Just trying to understand what that means.

**Comment by worksofliam** [comment]
@beckhamrryyaann Sorry for getting back to you so late. No, it just means I will look at it some time.

**Comment by worksofliam** [comment]
@Alastyr 

I just checked. We do store the current library in the connection profile and we do swap it out when you switch profiles. From your screenshots, it seems you were actually referring to command profiles, which will get the current library from the command you run.
