### ISSUE TITLE
New connection to allow for ssh-key content instead of path

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-ibmi#1644]
I know we had this before but changed it to use a path I think.

**Comment by worksofliam** [comment]
Okay, I just found https://github.com/codefori/vscode-ibmi/pull/1544 and it looks like we now support both these?

* `privateKey` for the SSH key content
* `privateKeyPath` for the path to it if it is local?

Perhaps we just need to add `privateKey` to the `ConnectionData` interface again?

https://github.com/codefori/vscode-ibmi/blob/master/src/typings.ts#L69

**Comment by sebjulliand** [comment]
We used to use `privateKey` as `privateKeyPath`, which was wrong.
But yes, putting back `privateKey` in `ConnectionData` will allow to put the key content in it and let node-ssh use it.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/2e6f08a6-d875-4125-9986-3fdebdf19fcd)
