### ISSUE TITLE
Pls Add Job Browser

### ISSUE THREAD

**Issue by mahesh-patel-jangili** [codefori/vscode-ibmi#1647]
No able to stop or check jobs pls add a job browser to check and stop jobs from vscode

**Comment by sebjulliand** [comment]
That was discussed here: https://github.com/codefori/vscode-ibmi/issues/304
An implementation of a Job Browser is done in a separate extension (see here https://github.com/codefori/vscode-ibmi-fs/pull/10), but its release has not been planned yet.

**Comment by mahesh-patel-jangili** [comment]
thanks for the info @sebjulliand
