### ISSUE TITLE
Ability to change batch debug JOBQ in connection settings

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-ibmi#1648]
Hard coded right here: https://github.com/codefori/vscode-ibmi/blob/master/src/api/debug/index.ts#L485

Could be a connection setting under the debug tab.

**Comment by Nathaniel-King-Navarrete** [comment]
@worksofliam is there a way to emulate a connection to an IBM i server for code changes?

**Comment by PerryRaleigh** [comment]
@worksofliam I'm looking at that line of code (https://github.com/codefori/vscode-ibmi/blob/master/src/api/debug/index.ts#L485), and don't exactly see where the JOBQ is being hard coded.

Here's what I'm seeing with a few lines before #485 and a few following:

`
    const pathKey = options.library.trim() + `/` + options.object.trim();

    const previousCommands = storage!.getDebugCommands();

    let currentCommand: string | undefined = previousCommands[pathKey] || `CALL PGM(` + pathKey + `)`;

    currentCommand = await vscode.window.showInputBox({
      ignoreFocusOut: true,
      **title: `Debug command`**,
      prompt: `Command used to start debugging the ${pathKey} program object. The command is wrapped around SBMJOB.`,
      value: currentCommand
    });
`

**Comment by PerryRaleigh** [comment]
BTW, I'm planning on picking this one up since it appears nobody is currently working on it.

**Comment by worksofliam** [comment]
@PerryRaleigh It seems like it might have been taken away already. This was created back when the debug service had first come out, so it might be defunct now.

**Comment by PerryRaleigh** [comment]
@worksofliam gracias.  I'll find another one to work on.
