### ISSUE TITLE
tn5250 encoding and keyboard problem

### ISSUE THREAD

**Issue by robinAha** [codefori/vscode-ibmi#1649]
Hi,
I have problem using swedish keyboard and displaying/writing åäö when using tn5250 in vscode.
Is it possible to change encoding to swedish and change keyboard settings?

I have tried everything on this page: [https://codefori.github.io/docs/#/pages/tips/terminals?id=terminal-startup](https://codefori.github.io/docs/#/pages/tips/terminals?id=terminal-startup)

![Capture](https://github.com/codefori/vscode-ibmi/assets/150913822/2460e0fc-2af0-4c51-be32-48a620b1a8a4)

**Comment by chrjorgensen** [comment]
Have you set the 5250 encoding to 278 in the settings for Terminals?

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/c4d9cd4c-368d-4d32-919c-7253353350c3)

Under the covers the 5250 terminal is just a call to the `tn5250` program installed via `yum`, and you can read the manual for the program with `man 5250` and see help with `tn5250 --help`.

Please note that `tn5250` is not a full replacement for ACS 5250 emulator - in my experience there are problems in `tn5250` showing non-English characters, backspace-key and more.

**Comment by robinAha** [comment]
Is it the same tn5250 Scott is referring to in https://www.scottklement.com/tn5250/windocs.html#AEN564

In that case are all settings configurable in vscode as he describes?

**Comment by chrjorgensen** [comment]
Probably - Scott is mentioned in the AUTHORS section of the man page for `tn5250`.

Only the shown settings below are exposed in Code for IBM i - but you can open a PASE terminal and run the `tn5250` program in there with your (additional) options...

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/a81e6cda-b1fe-4be1-94cb-48e2b96bcd42)

**Comment by robinAha** [comment]
Ok, thank you. Then we know :)
