### ISSUE TITLE
Use both hostname and ip address for debug service certificate

### ISSUE THREAD

**Issue by william-xiang** [codefori/vscode-ibmi#1666]
Currently the generated debug service certificate only uses the host value specified by the user, either hostname or ip address. And in the certificate this value is used as the common name. This means if this value is the hostname, then other user cannot use ip address to connect that machine and do debugging. Otherwise, the debug session will fail with this error:
<img width="538" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/24379419/7aed2d7f-08c8-4ada-9b9b-8ea7d1dbd382">

The certificate should contain both the hostname and ip address as the subject alternative names. So users can use either hostname or ip address for connection.

**Comment by worksofliam** [comment]
@william-xiang is this solved by https://github.com/codefori/vscode-ibmi/pull/1667?

**Comment by william-xiang** [comment]
> @william-xiang is this solved by #1667?

@worksofliam yes, this issue is resolved by that PR. Issue is closed.
