### ISSUE TITLE
Getting 5250 terminal is not supported. Please install TN5250 via yum on the re....

### ISSUE THREAD

**Issue by a4ginatl** [codefori/vscode-ibmi#1681]
I updated my applications using the ACS Open Source Package Management and installed TN5250 from there.

When I run the 5250 app, I get that message.

Is installing TN5250 using ACS correct, or do I need to install it another way?

What else could be wrong?

TIA, Darryl Freinkel.

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.4.0|
|Visual Studio Code version|1.84.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.5.2
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.15.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|7|
|CCSID|65535|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/usr/bin|/QOpenSys/pkgs/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|attr|bash|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|iconv|chsh|GETNEWLIBL.PGM|||
|setccsid|ls||||
|tar|md5sum||||
||sort||||
||stat||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=QGPL
CURLIB=QGPL
HOME=/home/dfreinkel
HOST=172.17.72.21
LIBLS=DPOBJLIB DPPDATA DPSRCLIB LIBHTTP YAJL QTEMP QGPL OPRUTLLIB DFREINKEL
LOGIN=dfreinkel
LOGNAME=dfreinkel
MAIL=/var/spool/mail/dfreinkel
OLDPWD=/home/DFREINKEL
PASE_USRGRP_LIMITED=N
PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/dfreinkel
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=10.27.230.56 52402 22
SSH_CONNECTION=10.27.230.56 52402 172.17.72.21 22
TZ=<EST>5<EDT>,M3.2.0,M11.1.0
USER=dfreinkel
USERNAME=dfreinkel
_=/QOpenSys/usr/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/dfreinkel"
  },
  {
    "command": "system \"DLTOBJ OBJ(ILEDITOR/O_*) OBJTYPE(*FILE)\"",
    "code": 255,
    "stderr": "CPF2125: No objects deleted.",
    "cwd": "/home/dfreinkel"
  }
]
```
</details>

**Comment by sebjulliand** [comment]
Disconnect and the reconnect once using this option:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/d5f4632b-933a-4e36-a558-d7003dbd09f5)

It will detect that TN5250 has been installed and updated the installed features cache. Then you'll be able to open a 5250 terminal.

**Comment by a4ginatl** [comment]
Thank you
