### ISSUE TITLE
Code for IBMi : Issue with object browser/source filter 

### ISSUE THREAD

**Issue by sudhiraroraCVS** [codefori/vscode-ibmi#1690]
We are trying to evaluate VS code for IBMi development in our CVS IBMi application before rolling the same out for DEV usage.
While performing the evaluation we ran into some issues, reaching out to this group to get feedback for resolving these issues.
Issue : 
Runing into issues with adding object brower/source filters. Getting error ‘CPC2957: No records copied from file O_HUS14J5O in APIDEVOBJ.
CPF2817: Copy command ended because of error.’
We have validated system temporary setting’s to ensure Temporary library(APIDEVOBJ) and Temporary IFS directory are setup correctly. This is holding many developers to evaluate Code for IBMi.

Version: 1.83.1 (system setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the list doesn't appear or when you see the error.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by sudhiraroraCVS** [comment]
Output channel has no logs at all and same thing with problems channel.

**Comment by sudhiraroraCVS** [comment]
.: echo "This should be the only text!"
{
    "code": 0,
    "signal": null,
    "stdout": "This should be the only text!",
    "stderr": ""
}

.: echo $HOME && cd && test -w $HOME
{
    "code": 0,
    "signal": null,
    "stdout": "/home/Z111567",
    "stderr": ""
}

/home/Z111567: /QOpenSys/usr/bin/qsh
liblist
{
    "code": 0,
    "signal": null,
    "stdout": "QSYS        SYS\nQSYS2       SYS\nQHLPSYS     SYS\nQUSRSYS     SYS\nISOJLIB     SYS\nCMKOUTQLIB  SYS\nRBTSYSLIB   SYS\nQSOC        SYS\nQSHELL      PRD\nQTEMP       USR\nCMKPRDGPL   USR\nAPCSGPL2    USR\nAPCSGPL     USR\nQMOD        USR\nRTOQATOBJ   USR\nRTOPRDOBJ   USR\nO_Y2GEN86   USR\nO_Y2GEN70   USR\nECLQATFIL   USR\nEZTQATFIL   USR\nELGQATFIL   USR\nMSBQATFIL   USR\nAPIQATFIL   USR\nAPIQATOBJ   USR\nAPIPRDOBJ   USR\nCOMQATFIL   USR\nCOMQATOBJ   USR\nCOMPRDOBJ   USR\nCLMQATFIL   USR\nCLMQATEXT   USR\nMSBQATEXT   USR\nCLMQATOBJ   USR\nCLMPRDOBJ   USR\nQGPL        USR\nTAATOOL     USR\nAPIUTILS    USR\nQATUTILS    USR\nUTCPRDFIL   USR\nUTCPRDOBJ   USR\nUTDPRDFIL   USR\nUTDPRDOBJ   USR\nCDAQATOBJ   USR\nCDAPRDOBJ   USR\nCDAPRDFIL   USR\nSSAPRDFIL   USR\nSSAPRDOBJ   USR\nDBU11       USR\nZMODLIB10   USR\nSOFTMENU2X  USR",
    "stderr": ""
}

/home/Z111567: system "CRTLIB LIB(APIDEVOBJ) TEXT('Code for i temporary objects. May be cleared.')"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPD0032: Not authorized to command CRTLIB in library *LIBL.\nCPF0006: Errors occurred in command."
}

/home/Z111567: system "CHKOBJ OBJ(QSYS/APIDEVOBJ) OBJTYPE(*LIB)"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/Z111567: [ -d "/home" ]
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/Z111567: echo $SHELL
{
    "code": 0,
    "signal": null,
    "stdout": "/QOpenSys/usr/bin/bsh",
    "stderr": ""
}

/home/Z111567: ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx not found"
}

/home/Z111567: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select job_name, authorization_name from qsys2.netstat_job_info j where local_port = 8005 group by job_name, authorization_name
{
    "code": 1,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\nJOB_NAME                     AUTHORIZATION_NAME \n---------------------------- -------------------\n\n  0 RECORD(S) SELECTED.",
    "stderr": ""
}

/home/Z111567: system "DSPFD FILE(CLMPRDSRC/QRPGSRC) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(APIDEVOBJ/O_hZPFi1KI)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_HZPFI1KI created in library APIDEVOBJ.\nCPF9862: Member O_HZPFI1KI added to output file O_HZPFI1KI in library APIDEVOBJ.\nCPF3030: 1 records added to member O_HZPFI1KI in file O_HZPFI1KI in APIDEVOBJ.",
    "stderr": ""
}

/home/Z111567: system "QSYS/CPYTOIMPF FROMFILE(APIDEVOBJ/O_hZPFi1KI O_hZPFi1KI) TOSTMF('/home/vscodetemp-O_kclid8sB') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPC2957: No records copied from file O_HZPFI1KI in APIDEVOBJ.\nCPF2817: Copy command ended because of error."
}

/home/Z111567: system "DSPFD FILE(CLMPRDSRC/QRPGSRC) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(APIDEVOBJ/O_YJNy7dap)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_YJNY7DAP created in library APIDEVOBJ.\nCPF9862: Member O_YJNY7DAP added to output file O_YJNY7DAP in library APIDEVOBJ.\nCPF3030: 1 records added to member O_YJNY7DAP in file O_YJNY7DAP in APIDEVOBJ.",
    "stderr": ""
}

/home/Z111567: system "QSYS/CPYTOIMPF FROMFILE(APIDEVOBJ/O_YJNy7dap O_YJNy7dap) TOSTMF('/home/vscodetemp-O_jcUzycna') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPC2957: No records copied from file O_YJNY7DAP in APIDEVOBJ.\nCPF2817: Copy command ended because of error."
}

**Comment by worksofliam** [comment]
@sudhiraroraCVS 

Couple of things: 

I do not recommend using `/home` as your temp library. This is for user storage and not for Code for IBM i temporary files. Please use something other, like `/tmp`.

What happens when you run these commands from 5250?

* `DSPFD FILE(CLMPRDSRC/QRPGSRC) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(APIDEVOBJ/XXX)`
* `QSYS/CPYTOIMPF FROMFILE(APIDEVOBJ/XXX XXX) TOSTMF('/home/vscodetemp-O_jcUzycna') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)`

**Comment by sudhiraroraCVS** [comment]
DSPFD command executed fine and added 1 record in APIDEVOBJ/XXX(XXX)
CPYTOIMPF command ended in error related to authority (see log below) :
QSYS/CPYTOIMPF FROMFILE(APIDEVOBJ/XXX XXX) TOSTMF('/tmp/vscodetemp-O_jcUzy 
cna') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK 
(*TRAILING) FLDDLM(',') DECPNT(*PERIOD) ADDCOLNAM(*SQL)                    
Ownership of object QCPEXTEMPS in QTEMP type *USRSPC changed.              
Ownership of object QACP856952 in QTEMP type *USRSPC changed.              
Ownership of object QACEXFLD12 in QTEMP type *USRSPC changed.              
Not authorized to CREATE ALIAS.                                            
Q0T372 in QTEMP type *FILE not found.                                      
Error occurred in SQL Call Level Interface                                 
Not authorized to CREATE ALIAS.                                            
Q0T372 in QTEMP type *FILE not found.                                      
Error occurred in SQL Call Level Interface                                 
No records copied from file XXX in APIDEVOBJ.                              
Copy command ended because of error.

**Comment by worksofliam** [comment]
@sudhiraroraCVS If you are not able to run these commands from a 5250, then this issue is a little bit out of our hands. We write a lot of temporary data to our temporary library and junk IFS folder.

Have you tried another library perhaps? One that you might have more authority to?

**Comment by sebjulliand** [comment]
@sudhiraroraCVS check your authorities as Liam suggested and also if there are any exit programs that could interfere here.

**Comment by worksofliam** [comment]
Closing as stale.
