### ISSUE TITLE
Make bash files automatically 

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-ibmi#1691]
A majority of our users don't even have `.bash_profile` or `.bashrc` setup.

I think if the user has bash as their default shell, and those files don't exist, we should create them with the following content:

```
# Generated by Code for IBM i
export PATH=/QOpenSys/pkgs/bin/:$PATH
```

@codefori/core @ThePrez What do you think?

**Comment by ThePrez** [comment]
That could potentially break people that have valuable things in `.profile` if I recall correctly. Doing env setup seems like an easy task but is way more complicated than it should be 😞

**Comment by worksofliam** [comment]
@ThePrez If that is the case, then maybe we only create those files if `.profile` doesn't exist also.

**Comment by edmundreinhardt** [comment]
I think we have something analogous, when a connection is connected we check for other things and prompt the user.  It would be a good time to check if pkgs/bin is in the path, and if not, offer to append it
