### ISSUE TITLE
Delete Member - New User

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-ibmi#1698]
### Discussed in https://github.com/orgs/codefori/discussions/1697

<div type='discussions-op-text'>

<sup>Originally posted by **jswidorski** December  7, 2023</sup>
I just installed Code for IBM i v2.5.0.

When I attempt to right-click on a source member and Delete Member it just doesn't do anything. No prompt of any kind.

I can Copy, Rename, Update text.</div>

**Comment by worksofliam** [comment]
@jswidorski

Is it protected?

Please share the contents of your Code for IBM i output channel after you try to use the right click option.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by jswidorski** [comment]
It shouldn't be. I just added it and then just deleted. I am on a test lpar where I have all authority. How do I get the console?

**Comment by worksofliam** [comment]
@jswidorski Will you share a screenshot of your empty Output view?

**Comment by worksofliam** [comment]
Can you confirm that your output is showing the Code for IBM i output channel, as chosen in the dropdown box on the right?

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by sebjulliand** [comment]
Is your VSCode running in English?
If not (and even if it does, actually) would you mind changing the `Code for IBM i` locale to `en` here?
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/50d9f67c-4a49-4f4d-bf41-63315c348c58)

Then restart VSCode and see if it changes anything.

Otherwise, after the command does nothing, is there anything in VSCode developer console?
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/1eefc3da-4b56-488c-a5d7-ca2780d6d539)
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/cd8828ec-63b6-455d-8f82-398368fd4470)

**Comment by jswidorski** [comment]
I did change language from inherit.

![image](https://github.com/codefori/vscode-ibmi/assets/586998/e4e6c09d-2a9f-4a94-b642-2bdd66f3e70e)

**Comment by jswidorski** [comment]
Any other thoughts on this? Looks like DELETE MEMBER is the only option not working for me. It throws no text to the Output tab.

**Comment by worksofliam** [comment]
@jswidorski I think we had four members of the core team try it out and not produce the same result. You mentioned you changed the locale - what did you change it to from inherit?

**Comment by jswidorski** [comment]
So I cheated. I went in and edited the JSON to create a RMVM command. It deletes the member. It doesn't refresh the list, but manually refreshing removed it from there.

I know it's not the solution of choice. I also assume, I will have to add it any time my extension gets loaded.

    {
        "type": "member",
        "extensions": [
            "CBLLE",
            "CBL",
            "CLP",
            "CLLE",
            "CMD",
            "PF",
            "LF",                
            "RPGLE",
            "RPG",
            "SQLRPGLE",
            "SQL" 
        ],
        "name": "Remove member (RMVM)",
        "command": "?RMVM FILE(&OPENLIB/&OPENSPF) MBR(&OPENMBR)"
    },

**Comment by sebjulliand** [comment]
> So I cheated. I went in and edited the JSON to create a RMVM command. It deletes the member. It doesn't refresh the list, but manually refreshing removed it from there.
> 
> I know it's not the solution of choice. I also assume, I will have to add it any time my extension gets loaded.
> 
> ```
> {
>     "type": "member",
>     "extensions": [
>         "CBLLE",
>         "CBL",
>         "CLP",
>         "CLLE",
>         "CMD",
>         "PF",
>         "LF",                
>         "RPGLE",
>         "RPG",
>         "SQLRPGLE",
>         "SQL" 
>     ],
>     "name": "Remove member (RMVM)",
>     "command": "?RMVM FILE(&OPENLIB/&OPENSPF) MBR(&OPENMBR)"
> },   
> ```

If you add `"refresh": "parent"` to your command definition, it will refresh the parent item (the SPF in your case).

**Comment by jswidorski** [comment]
Thanks!

**Comment by sebjulliand** [comment]
@jswidorski I just want to check something with you. Would it be that your VSCode notifications are in `Do not disturb` mode?
Is the bell at the bottom right barred? Like below:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/d676c85f-15e4-4436-a711-d7c4b0e41f67)

If so then please click on the bell and turn off do not disturb:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/9742c813-6f7e-4755-b980-eb2f43418812)

Then the warning notification when you delete a member should show up.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/df19e9d5-8faf-4443-9bff-60c096481e2a)

**Comment by jswidorski** [comment]
@sebjulliand Thank you. That was it.

Appreciate the research. I can't image that I ever turned that on.

**Comment by sebjulliand** [comment]
> @sebjulliand Thank you. That was it.
> 
> Appreciate the research. I can't image that I ever turned that on.

You're welcome! I'm glad we sorted this one out 😄
