### ISSUE TITLE
Upon start of the debug getting CRRDG1121E tag type 45 

### ISSUE THREAD

**Issue by egrabski** [codefori/vscode-ibmi#1699]
Getting error 
Illegal base64 character 5f
EQARD1007I The Remote Debug Service daemon started on port 8001.
CRRDG1121E Debug Secure Daemon failed to start. Reason: toDerInputStream rejects tag type 45
Opened case with IBM to verify its not a problem with the system. Re-created all the steps from the walkthrough.
IBM support said type 45 means expired certificates but they were just created .
We are on OS 7.4 and PTF SI83683 and SI81031 are applied.
@
![2023-12-07_16-39-17](https://github.com/codefori/vscode-ibmi/assets/11429248/ef60b403-082a-4099-8665-4e0a14e1f982)

![2023-12-07_16-16-02](https://github.com/codefori/vscode-ibmi/assets/11429248/bf6fe4c0-36f5-472d-8194-271885176a6d)

**Comment by ToshBimbra** [comment]
Is this still being worked on?

**Comment by egrabski** [comment]
I still have the problem.

**Comment by ToshBimbra** [comment]
@worksofliam any thoughts on what is failing here

**Comment by worksofliam** [comment]
@mkwan01 any ideas here?

**Comment by mkwan01** [comment]
This message normally means that the certificate is not valid. The certificate creation is not done in the debugger itself. It is handled by code for i.

@worksofliam Do you know which file in the screen capture is set as the DEBUG_SERVICE_KEYSTORE_FILE environment variable value?

**Comment by mkwan01** [comment]
On my system, I can see that if the client certificate (the .crt file) is used on the host, then it would generate the "toDerInputStream rejects tag type 45" message. Please make sure that the .pfx file is used as the host keystore.

**Comment by mkwan01** [comment]
Code for IBM i 2.9.0 contains a number of fixes for certificate generation. Please reopen the issue if you can still reproduce the problem in 2.9.0.
