### ISSUE TITLE
Possible loop

### ISSUE THREAD

**Issue by pabloto** [codefori/vscode-ibmi#1704]
Hi, I attach my codefori output log, there's a possible issue.

we work in local, and we have an iasp, I don't know why in a certain moment codefori try to:

.: system "CPYTOSTMF FROMMBR('/QSYS.lib/AL400MNUV2.lib/QRPGLESRC.file/UMIFUNC_H.mbr') TOSTMF('/tmp/vscodetemp-O_iXrqBaLz') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPFA0A9: L'oggetto non è stato trovato. L'oggetto è /QSYS.lib/AL400MNUV2.lib/QRPGLESRC.file/UMIFUNC_H.mbr.\nCPFA097: Oggetto non copiato. L'oggetto è /QSYS.lib/AL400MNUV2.lib/QRPGLESRC.file/UMIFUNC_H.mbr."

this object really doesn't exists, it is on /DIRECTA1/QSYS.lib/AL400MNUV2.lib/QRPGLESRC.file/UMIFUNC_H.mbr

DIRECTA1 is the name of my iasp.

I try to downgrade to the previous version but the problem seems to be the same.

Could you check??

I try to clrlib vscode.

Today I have more then 160.000 jobs on my system, deleting the jobs QP0ZSPWT  it remains only 5.000. changing my qdftsrv jobd to log (4 00 *nolist) the joblog doesn't remain on the system.

Thank you
[Codefori_output.txt](https://github.com/codefori/vscode-ibmi/files/13638666/Codefori_output.txt)

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.5.0|
|Visual Studio Code version|1.85.0|
|Operating System|darwin_arm64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 9.11.22
Code Spell Checker (code-spell-checker): 3.0.1
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.6.0
Dev Containers (remote-containers): 0.327.0
ESLint (vscode-eslint): 2.4.2
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.15.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
Git Graph (git-graph): 1.30.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitLab Workflow (gitlab-workflow): 3.92.0
GitLens — Git supercharged (gitlens): 14.5.2
IBM i Project Explorer (vscode-ibmi-projectexplorer): 1.2.6
JSON Language Features (json-language-features): 1.0.0
Live Share (vsliveshare): 1.0.5900
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Postman (postman-for-vscode): 0.15.0
RPGLE (vscode-rpgle): 0.24.0
Rainbow CSV (rainbow-csv): 3.9.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL (remote-wsl): 0.81.8
vscode-icons (vscode-icons): 12.6.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|8|
|CCSID|280|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|vscode.GETNEWLIBL|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv||||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=JDET
CURLIB=JDET
HOME=/home/paolos
HOST=directa1
LANG=IT_IT.UTF-8
LIBLS=EMIR YAJLNEW YAJL DIRSAMPLE DEMODAT DEMOSYS ROBERTO PAOLOS CONTRADAT AL400 AL400SYS AL400MNUV2 FIBLIB BETALIB QGPL GESTSIMDAF GESTSIMDAT JDET QTEMP
LOGIN=paolos
LOGNAME=paolos
LS_COLORS=
MAIL=/var/spool/mail/paolos
OLDPWD=/DIRECTA1/home/paolos
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PS1=\u@\h@\W$
PWD=/home/paolos
QIBM_PASE_CCSID=1208
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=192.168.0.141 54702 22
SSH_CONNECTION=192.168.0.141 54702 192.168.0.11 22
SSL_CERT_FILE=/home/cacert.pem
TZ=<CET>-1<CEST>,M3.5.0,M10.5.0
USER=paolos
USERNAME=paolos
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "£§$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CPYTOSTMF FROMMBR('/QSYS.lib/AL400MNUV2.lib/QRPGLESRC.file/UMIFUNC_H.mbr') TOSTMF('/tmp/vscodetemp-O_iXrqBaLz') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)\"",
    "code": 255,
    "stderr": "CPFA0A9: L'oggetto non è stato trovato. L'oggetto è /QSYS.lib/AL400MNUV2.lib/QRPGLESRC.file/UMIFUNC_H.mbr.\nCPFA097: Oggetto non copiato. L'oggetto è /QSYS.lib/AL400MNUV2.lib/QRPGLESRC.file/UMIFUNC_H.mbr.",
    "cwd": "."
  },
  {
    "command": "system \"CPYTOSTMF FROMMBR('/QSYS.lib/AL400MNUV2.lib/QRPGLESRC.file/UMIFUNC_H.mbr') TOSTMF('/tmp/vscodetemp-O_iXrqBaLz') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)\"",
    "code": 255,
    "stderr": "CPFA0A9: L'oggetto non è stato trovato. L'oggetto è /QSYS.lib/AL400MNUV2.lib/QRPGLESRC.file/UMIFUNC_H.mbr.\nCPFA097: Oggetto non copiato. L'oggetto è /QSYS.lib/AL400MNUV2.lib/QRPGLESRC.file/UMIFUNC_H.mbr.",
    "cwd": "."
  },
  {
    "command": "system \"CPYTOSTMF FROMMBR('/QSYS.lib/AL400MNUV2.lib/QRPGLESRC.file/UMIFUNC_H.mbr') TOSTMF('/tmp/vscodetemp-O_iXrqBaLz') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)\"",
    "code": 255,
    "stderr": "CPFA0A9: L'oggetto non è stato trovato. L'oggetto è /QSYS.lib/AL400MNUV2.lib/QRPGLESRC.file/UMIFUNC_H.mbr.\nCPFA097: Oggetto non copiato. L'oggetto è /QSYS.lib/AL400MNUV2.lib/QRPGLESRC.file/UMIFUNC_H.mbr.",
    "cwd": "."
  }
]
```
</details>

**Comment by worksofliam** [comment]
This is coming from vscode-rpgle for sure - looks like the include resolver. Right now, I am aware the include resolver does not look at ASP, but I do have an issue open for this: #1684.

I am going to copy your issue text to that issue and close this one.
