### ISSUE TITLE
Outline view

### ISSUE THREAD

**Issue by pabloto** [codefori/vscode-ibmi#1718]
Hi,

from command palette if I search for outline view this is the output:

<img width="759" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/9719313/2c0b2617-3c08-4656-95fd-fd0f380d2297">

by clicking on the first one it open the outline view, but there's no the voice in command palette.

Thank you

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.5.0|
|Visual Studio Code version|1.85.0|
|Operating System|darwin_arm64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 9.11.22
Code Spell Checker (code-spell-checker): 3.0.1
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.6.0
Dev Containers (remote-containers): 0.327.0
ESLint (vscode-eslint): 2.4.2
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.15.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
Git Graph (git-graph): 1.30.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitLab Workflow (gitlab-workflow): 3.92.0
GitLens — Git supercharged (gitlens): 14.5.2
IBM i Project Explorer (vscode-ibmi-projectexplorer): 1.2.6
JSON Language Features (json-language-features): 1.0.0
Live Share (vsliveshare): 1.0.5900
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Postman (postman-for-vscode): 0.15.0
RPGLE (vscode-rpgle): 0.24.0
Rainbow CSV (rainbow-csv): 3.9.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL (remote-wsl): 0.81.8
vscode-icons (vscode-icons): 12.6.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|8|
|CCSID|280|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|vscode.GETNEWLIBL|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv||||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=JDET
CURLIB=JDET
HOME=/home/paolos
HOST=directa1
LANG=IT_IT.UTF-8
LIBLS=EMIR YAJLNEW YAJL DIRSAMPLE DEMODAT DEMOSYS ROBERTO PAOLOS CONTRADAT AL400 AL400SYS AL400MNUV2 FIBLIB BETALIB QGPL GESTSIMDAF GESTSIMDAT JDET QTEMP
LOGIN=paolos
LOGNAME=paolos
LS_COLORS=
MAIL=/var/spool/mail/paolos
OLDPWD=/DIRECTA1/home/paolos
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PS1=\u@\h@\W$
PWD=/home/paolos
QIBM_PASE_CCSID=1208
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=192.168.0.141 50381 22
SSH_CONNECTION=192.168.0.141 50381 192.168.0.11 22
SSL_CERT_FILE=/home/cacert.pem
TZ=<CET>-1<CEST>,M3.5.0,M10.5.0
USER=paolos
USERNAME=paolos
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "£§$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(VSCODE) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2158: La libreria VSCODE esiste nell'unità ASP DIRECTA1.\nCPF2111: La libreria VSCODE esiste già.",
    "cwd": "/home/paolos"
  },
  {
    "command": "system \"DLTOBJ OBJ(VSCODE/O_*) OBJTYPE(*FILE)\"",
    "code": 255,
    "stderr": "CPF2125: Non è stato cancellato alcun oggetto.",
    "cwd": "/home/paolos"
  }
]
```
</details>

**Comment by chrjorgensen** [comment]
@pabloto 

You find the outline view in menu `View` > `Open View`:

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/87ab36cb-2e0b-4d5a-98f5-1c59693edf19)

In the list type `Outline` and select:

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/2730f4b8-1b3e-47fe-aa50-a1eb634c8fd5)

As you can see, I have the Outline view in the secondary sidebar - you can drag it to any sidebar as needed.

**Comment by sebjulliand** [comment]
He he, I've got the same display here in VSCode:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/ed82776c-f516-4561-b722-b0724fe20842)

But the outline view is provided and managed by VSCode and not by Code for IBM i anyway, so there may be an actual problem in VSCode 😅.
