### ISSUE TITLE
All dates updated on already existing source members

### ISSUE THREAD

**Issue by FerrPaola** [codefori/vscode-ibmi#1720]
Hi,
i've got a problem with the dates of an already existing source member.
After working on a source member:
- press CTRL + E
- CRTSQLRPGI
- If it gives me back an error, i can go to "Problems".
![image](https://github.com/codefori/vscode-ibmi/assets/153718388/2c5acd01-0105-4f92-a8d1-9f0c573e4d95)
- In the moment i press on this line, all the dates of the source member are updated and overwritten with today's date.
![image](https://github.com/codefori/vscode-ibmi/assets/153718388/42637b2b-8037-452e-90ba-4d9b1ab014fb)

Sometimes it happens even if i don't touch these buttons, and it seems to happen without any real motivation.

Let me know if i can give you other information to help you.

Thank you

**Comment by worksofliam** [comment]
Hi

I tried to recreate this bug. Please see this video where I attempted to recreate your steps. As you can see, as I click on different items in the Problems view the source dates are not changing. Am I doing something wrong?

https://www.youtube.com/watch?v=rGd48QpMvnU
