### ISSUE TITLE
CPYTOSTMF not working after upgrading past 2.5.0

### ISSUE THREAD

**Issue by petterjohansson** [codefori/vscode-ibmi#1735]
Hi!

This might be a issue on our end, but after upgrading past v2.5.0 we are not able to open source members. Downgrading to 2.5.0 solves the issue. 

Log latest version:

```
/home/username: /QOpenSys/usr/bin/qsh
system  "CPYTOSTMF FROMMBR('/QSYS.LIB/NICD_99.LIB/QRPGLESRC.FILE/TEST123.MBR') TOSTMF('/tmp/vscodetemp-O_IQoHKC36') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"; if [[ $? -ne 0 ]]; then exit 1; fi
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}
```

Log from 2.5.0 (working):

```
.: system "CPYTOSTMF FROMMBR('/QSYS.lib/NICD_99.lib/QRPGLESRC.file/TEST123.mbr') TOSTMF('/tmp/vscodetemp-O_W5W6Olzz') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPCA082: Objekt ble kopiert.",
    "stderr": ""
}
```

**Comment by worksofliam** [comment]
What error do you receive in VS Code?

@sebjulliand another possible thing from the API change?

**Comment by worksofliam** [comment]
Did some validation. Looks fetching members with `CPYTOSTMF` works as expected in our test cases.

```
/home/LINUX: /QOpenSys/usr/bin/qsh
system  "CPYTOSTMF FROMMBR('/QSYS.LIB/LIAMA.LIB/QRPGLESRC.FILE/ABCD.MBR') TOSTMF('/tmp/vscodetemp-O_0k0tPX7a') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"; if [[ $? -ne 0 ]]; then exit 1; fi
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": "CPCA082:  Object copied."
}

```

**Comment by petterjohansson** [comment]
So i deleted all my extensions (primarly use Arcad-skipper in vscode), reinstalled only the ibm i development pack. Then created a new connection and a new object filter which should list some sources:

<img width="1429" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/12429224/3cd79b90-714b-49ee-81d5-bc59643d3271">

It seems like the DSPOBJD didn't work as expected and there was nothing to fetch in the following select statement.

I rolled back to the 2.5.0 version:
<img width="1646" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/12429224/57567d0d-6508-48da-8271-bc0dd5d26dc8">

This time the DSPOBJD worked correctly and a file was created, but the following SQL statement didn't run correctly. I can see the content through ACS. 

Not sure if this helps at all. Is there any specific log I can provide? 

When using code for ibm i 2.5.0 - the arcad skipper plugin is able to open source members.

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the issue occurs. I think we're going to need the entire look to further diagnose.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by worksofliam** [comment]
@sebjulliand note about the ARCAD issue here.

**Comment by petterjohansson** [comment]
I both examples I have restarted VSCode connectet to the ibm i and tried to expand the filter which should list members.


<details>
<summary>Complete log using v2.5.0</summary>
.: echo "This should be the only text!"
{
    "code": 0,
    "signal": null,
    "stdout": "This should be the only text!",
    "stderr": ""
}

.: echo $HOME && cd && test -w $HOME
{
    "code": 0,
    "signal": null,
    "stdout": "/home/PETHACK",
    "stderr": ""
}

/home/PETHACK: /QOpenSys/usr/bin/qsh
liblist
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/PETHACK: system "CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF2111: Library ILEDITOR already exists."
}

/home/PETHACK: [ -d "/tmp" ]
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/PETHACK: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
select CHARACTER_CODE_SET_ID from table( QSYS2.QSYUSRINFO( USERNAME => upper('PETHACK') ) )
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/PETHACK: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
with VARIANTS ( HASH, AT, DOLLARSIGN ) as (  values ( cast( x'7B' as varchar(1) )         , cast( x'7C' as varchar(1) )         , cast( x'5B' as varchar(1) ) ))select HASH concat AT concat DOLLARSIGN as LOCAL  from VARIANTS; 
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/PETHACK: echo $SHELL
{
    "code": 0,
    "signal": null,
    "stdout": "/QOpenSys/pkgs/bin/bash",
    "stderr": ""
}

/home/PETHACK: ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx
/home/PETHACK: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select OS_VERSION || '.' || OS_RELEASE as VERSION from sysibmadm.env_sys_info
/home/PETHACK: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select max(ptf_group_level) as HIGHEST_DB2_PTF_GROUP_LEVEL from qsys2.group_ptf_info where PTF_GROUP_DESCRIPTION like 'DB2 FOR IBM I%' and ptf_group_status = 'INSTALLED';
/home/PETHACK: ls $HOME/.vscode/codeforiserver-1.4.5.jar
{
    "code": 0,
    "signal": null,
    "stdout": "/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "/home/PETHACK/.vscode/codeforiserver-1.4.5.jar",
    "stderr": ""
}

/home/PETHACK: echo $SHELL
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "/QOpenSys/pkgs/bin/bash",
    "stderr": ""
}

/home/PETHACK: system "DSPOBJD OBJ(SBT1OBJ/*ALL) OBJTYPE(*PGM) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_cs57pIq2)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Utdatafil O_CS57PIQ2 ble laget i bibliotek ILEDITOR.\nCPF9862: Komponent O_CS57PIQ2 ble føyd til utdatafil O_CS57PIQ2 i bibliotek ILEDITOR.",
    "stderr": ""
}

/home/PETHACK: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT * FROM ILEDITOR.O_cs57pIq2
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

</details>


<details>
<summary>Complete log using v2.6.1</summary>
.: echo "This should be the only text!"
{
    "code": 0,
    "signal": null,
    "stdout": "This should be the only text!",
    "stderr": ""
}

.: echo $HOME && cd && test -w $HOME
{
    "code": 0,
    "signal": null,
    "stdout": "/home/PETHACK",
    "stderr": ""
}

/home/PETHACK: /QOpenSys/usr/bin/qsh
liblist
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/PETHACK: /QOpenSys/usr/bin/qsh
system  "CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')"; if [[ $? -ne 0 ]]; then exit 1; fi
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/PETHACK: [ -d "/tmp" ]
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/PETHACK: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
select CHARACTER_CODE_SET_ID from table( QSYS2.QSYUSRINFO( USERNAME => upper('PETHACK') ) )
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/PETHACK: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
with VARIANTS ( HASH, AT, DOLLARSIGN ) as (  values ( cast( x'7B' as varchar(1) )         , cast( x'7C' as varchar(1) )         , cast( x'5B' as varchar(1) ) ))select HASH concat AT concat DOLLARSIGN as LOCAL  from VARIANTS; 
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/PETHACK: echo $SHELL
{
    "code": 0,
    "signal": null,
    "stdout": "/QOpenSys/pkgs/bin/bash",
    "stderr": ""
}

/home/PETHACK: echo $PATH
{
    "code": 0,
    "signal": null,
    "stdout": "/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin",
    "stderr": ""
}

/home/PETHACK: test -e /home/PETHACK/.bashrc
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/PETHACK: ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx
/home/PETHACK: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select OS_VERSION || '.' || OS_RELEASE as VERSION from sysibmadm.env_sys_info
/home/PETHACK: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select max(ptf_group_level) as HIGHEST_DB2_PTF_GROUP_LEVEL from qsys2.group_ptf_info where PTF_GROUP_DESCRIPTION like 'DB2 FOR IBM I%' and ptf_group_status = 'INSTALLED';
/home/PETHACK: ls $HOME/.vscode/codeforiserver-1.4.5.jar
{
    "code": 0,
    "signal": null,
    "stdout": "/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "/home/PETHACK/.vscode/codeforiserver-1.4.5.jar",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/PETHACK: echo $SHELL
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "/QOpenSys/pkgs/bin/bash",
    "stderr": ""
}

/home/PETHACK: /QOpenSys/usr/bin/qsh
system  "DSPOBJD OBJ(SBT1OBJ/*ALL) OBJTYPE(*PGM) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_cMJOIUrj)"; if [[ $? -ne 0 ]]; then exit 1; fi
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/PETHACK: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT * FROM ILEDITOR.O_cMJOIUrj
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

</details>

Its been a while since i've worked inside the code for ibm i extension, but last time I used it i was able list members from filters and edit them. I know we have upgraded to V7R5M0 with TR level: 2 since then. As mentioned, with v2.5.0 im able to use the Arcad skipper extension so its no hurry - with christmas holiday going on. :)

**Comment by worksofliam** [comment]
@petterjohansson i have two suggestions for you:

1. Try turning off SQL mode in the connection settings and see if that helps
2. Check out this: [No Results from SQL execution](https://codefori.github.io/docs/#/pages/tips/setup?id=no-results-from-sql-execution)

**Comment by petterjohansson** [comment]
So here are the results:

**Option 1** with with SQLmode turned off in connection settings:
It worked for v2.5.0, not with v2.6.1 (latter got the message "no file found" as the CPYTOSTMF didn't run correctly).

**Option 2** with restart of the SSHD server:
Now everything works with v2.6.1. Woho! 

Thanks for the amazing support, and I applogize for not reading the manual in regard to troubleshooting. ^^

**Comment by worksofliam** [comment]
@petterjohansson That's great to hear! For option 1, I suspect PR #1741 might solve it.
