### ISSUE TITLE
EQAVS1007E ************* on port 8015 could not be connected. Message received: unable to verify the first certificate

### ISSUE THREAD

**Issue by amine-boujemaaoui** [codefori/vscode-ibmi#1738]
I started the debug service and imported the certificates, but I have this error:
 EQAVS1007E ************* on port 8015 could not be connected. Message received: unable to verify the first certificate.
 
<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.6.1|
|Visual Studio Code version|1.85.1|
|Operating System|linux_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.6.0
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Debug (ibmidebug): 1.0.0
IBM i Project Explorer (vscode-ibmi-projectexplorer): 2.6.0
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.24.0
Server Ready Action (debug-server-ready): 1.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R3M0|
|Tech Refresh|13|
|CCSID|297|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|ls|setccsid||||
|md5sum|tar||||
|sort|||||
|stat|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=QGPL
CURLIB=QGPL
HOME=/home/AB
HOST=***********
LIBLS=QGPL QTEMP PERSO_AB
LOGIN=ab
LOGNAME=ab
MAIL=/var/spool/mail/ab
OLDPWD=/home/AB
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/AB
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=***********
SSH_CONNECTION=**************
TZ=<CET>-1<CEST>,M3.5.0,M10.5.0
USER=ab
USERNAME=AB
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "£à$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF2111:  La bibliothèque ILEDITOR existe déjà.\nCPC2206:  Propriété de l'objet QZSHSYSTEM de QTEMP, type *USRSPC modifiée.",
    "cwd": "/home/AB"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF9801:  Objet QCPTOIMPF non trouvé dans la bibliothèque QSYS.\nCPC2206:  Propriété de l'objet QZSHSYSTEM de QTEMP, type *USRSPC modifiée.",
    "cwd": "/home/AB"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF9801:  Objet QCPFRMIMPF non trouvé dans la bibliothèque QSYS.\nCPC2206:  Propriété de l'objet QZSHSYSTEM de QTEMP, type *USRSPC modifiée.",
    "cwd": "/home/AB"
  }
]
```
</details>

**Comment by guilhem** [comment]
In our context, machine fqdn isn't in DNS.
So we end up putting it in /etc/hosts

To reproduce:
- in a wsl environment
- setup port to 8015
- change secure port in .env to 8015
- setup certificate
- launch debug on a full

**Comment by mkwan01** [comment]
This message normally indicates that the client certificate does not match the host certificate. How did you start the debug service? From the vscode client, or from a green screen session?

**Comment by mkwan01** [comment]
Code for IBM i 2.9.0 contains a number of fixes for certificate generation. Please reopen the issue if you can still reproduce the problem in 2.9.0.
