### ISSUE TITLE
Strange message about temp library when connecting to power server

### ISSUE THREAD

**Issue by lgiammattei** [codefori/vscode-ibmi#1739]
👉🏻 After latest update few days ago I keep receiving this warning when connecting to one of my power server
**Code for IBM i will not function correctly until the temporary library has been corrected in the settings.**
In my settings temporary tab i have 
![immagine](https://github.com/codefori/vscode-ibmi/assets/54810977/58f99dca-742f-42b4-a3b4-0a237adc4138)
what's wrong with this?
<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.6.1|
|Visual Studio Code version|1.85.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 9.12.14
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.6.0
ESLint (vscode-eslint): 2.4.2
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.16.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
HTML CSS Support (vscode-html-css): 1.13.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
IBM i Project Explorer (vscode-ibmi-projectexplorer): 2.6.0
IntelliSense for CSS class names in HTML (html-css-class-completion): 1.20.0
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R3M0|
|Tech Refresh|12|
|CCSID|65535|
|SQL|Disabled
|Source dates|Disabled

### Enabled features

|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|
|-|-|-|
|attr|GENCMDXML.PGM|QZDFMDB2.PGM|
|iconv|GETNEWLIBL.PGM||
|ls|||
|setccsid|||
|tar|||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "��$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPC9801:  Oggetto MXCMD2RUN di tipo *DTAQ creato nella libreria QTEMP.\nCPC9801:  Oggetto MXRSNDMG di tipo *DTAQ creato nella libreria QTEMP.\nCPF2111:  La libreria ILEDITOR esiste gi�.",
    "cwd": "/home/userx"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"USERX\" && export HOST=\"PowerServerLND\" && export HOME=\"/home/USERX\" && export LIBLS=\"MY_LIBRARY_LIST\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/userx"
  }
]
```
</details>

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after connecting to the system where you get this message.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by lgiammattei** [comment]
.: echo "This should be the only text!"
{
    "code": 0,
    "signal": null,
    "stdout": "This should be the only text!",
    "stderr": ""
}

.: echo $HOME && cd && test -w $HOME
{
    "code": 0,
    "signal": null,
    "stdout": "/home/USERX",
    "stderr": ""
}

/home/USERX: /QOpenSys/usr/bin/qsh
liblist
{
    "code": 0,
    "signal": null,
    "stdout": "MAXSYS      SYS\nQSYS        SYS\nQSYS2       SYS\nQHLPSYS     SYS\nQUSRSYS     SYS\nQSHELL      PRD\nQGPL        USR\nQTEMP       USR\nJGPL        USR\nACGGAA      USR",
    "stderr": ""
}

/home/USERX: /QOpenSys/usr/bin/qsh
system  "CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')"; if [[ $? -ne 0 ]]; then exit 1; fi
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "CPC9801:  Oggetto MXCMD2RUN di tipo *DTAQ creato nella libreria QTEMP.\nCPC9801:  Oggetto MXRSNDMG di tipo *DTAQ creato nella libreria QTEMP.\nCPF2111:  La libreria ILEDITOR esiste gi�."
}

/home/USERX: [ -d "/tmp" ]
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/USERX: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select OS_VERSION || '.' || OS_RELEASE as VERSION from sysibmadm.env_sys_info
/home/USERX: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select max(ptf_group_level) as HIGHEST_DB2_PTF_GROUP_LEVEL from qsys2.group_ptf_info where PTF_GROUP_DESCRIPTION like 'DB2 FOR IBM I%' and ptf_group_status = 'INSTALLED';
/home/USERX: ls $HOME/.vscode/codeforiserver-1.4.5.jar
{
    "code": 4,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\n **** CLI ERROR *****\n         SQLSTATE: 42601\nNATIVE ERROR CODE: -104\nToken | non valido. Token validi: + - AS <IDENTIFIER>.",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "/home/USERX/.vscode/codeforiserver-1.4.5.jar",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n\nHIGHEST_DB2_PTF_GROUP_LEVEL \n----------------------------\n                          29\n\n  1 RECORD(S) SELECTED.\n\nDB2>",
    "stderr": ""
}

**Comment by sebjulliand** [comment]
@worksofliam I know why. Look at `stderr` from `CRTLIB`:
```
"stderr": "CPC9801: Oggetto MXCMD2RUN di tipo *DTAQ creato nella libreria QTEMP.\nCPC9801: Oggetto MXRSNDMG di tipo *DTAQ creato nella libreria QTEMP.\nCPF2111: La libreria ILEDITOR esiste gi�."
```

@lgiammattei 's system must have either a custom CRTLIB or an exit program that creates these two DTAQ before the library creation gets attempted. This adds more messages in stderr and our logic here is flawed: https://github.com/codefori/vscode-ibmi/blob/7c7dfb42d6cbf7cf7cb43c36072a206ed32dbf33/src/api/IBMi.ts#L356

I'll fix that 😉

**Comment by lgiammattei** [comment]
@sebjulliand this system works in a disaster recovery scenario, every time a library is created it is replicated on the secondary site

**Comment by sebjulliand** [comment]
@lgiammattei Thanks for the info, that makes sense. The PR mentioned above will fix this issue.
