### ISSUE TITLE
When editing source code on an IBM i, upon saving the code the change date on every line of code changes to zeros.  This renders the editor un-useable.  Is there a configuration option to adopt the change date behavior de facto to ALL previous editors?

### ISSUE THREAD

**Issue by StephenMWest** [codefori/vscode-ibmi#1742]
👉🏻 Issue text goes here.

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.6.1|
|Visual Studio Code version|1.83.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 9.11.8
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.6.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.15.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

**_Not connected_** 🔌

**Comment by worksofliam** [comment]
@StephenMWest you likely need to turn on source date support in the connection settings.

I am going to close this because the issue format is incorrect (please don't put the issue content into the title)

**Comment by StephenMWest** [comment]
First time submitting an issue.  I will re-submit it with a brief title.

Thanks.
