### ISSUE TITLE
Start Debug Service fails

### ISSUE THREAD

**Issue by SJLennon** [codefori/vscode-ibmi#1761]
I issue the IBM i Debug: Start Debug Service.  It runs without error, but doesn't start the service.

In the OUTPUT for Code for IBM i: Pub400 is see "**/bin/sh: bad interpreter: Permission denied**".

I have bash installed:
![image](https://github.com/codefori/vscode-ibmi/assets/67484051/33ec7c58-8759-4c22-afe2-07b715716b07)
And bash is also in my path:
![image](https://github.com/codefori/vscode-ibmi/assets/67484051/c0e3d5d7-494f-4f05-8305-a05c6fffc103)

I have seen similar /bin/sh issue with bob, but with no resolution: https://github.com/IBM/ibmi-bob/issues/271

Any suggestions?
```

/home/LENNONS: ls -p /home/lennons/certs/debug_service.pfx
{
    "code": 0,
    "signal": null,
    "stdout": "/home/lennons/certs/debug_service.pfx",
    "stderr": ""
}

/home/LENNONS: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select job_name, authorization_name from qsys2.netstat_job_info j where local_port = 8005 group by job_name, authorization_name
{
    "code": 1,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\nJOB_NAME                     AUTHORIZATION_NAME \n---------------------------- -------------------\n\n  0 RECORD(S) SELECTED.",
    "stderr": ""
}

/home/LENNONS: MY_JAVA_HOME="/QOpenSys/QIBM/ProdData/JavaVM/jdk80/64bit" DEBUG_SERVICE_KEYSTORE_PASSWORD="pub400.com" /QIBM/ProdData/IBMiDebugService/bin/encryptKeystorePassword.sh | /usr/bin/tail -n 1
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": "bash: /QIBM/ProdData/IBMiDebugService/bin/encryptKeystorePassword.sh: /bin/sh: bad interpreter: Permission denied"
}

/home/LENNONS: MY_JAVA_HOME="/QOpenSys/QIBM/ProdData/JavaVM/jdk80/64bit" DEBUG_SERVICE_KEYSTORE_PASSWORD="" DEBUG_SERVICE_KEYSTORE_FILE="/home/lennons/certs/debug_service.pfx" /QOpenSys/usr/bin/nohup "/QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh"
{
    "code": 126,
    "signal": null,
    "stdout": "",
    "stderr": ""
}
```

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.6.2|
|Visual Studio Code version|1.85.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Bash Debug (bash-debug): 0.3.9
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.6.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.16.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Debug (ibmidebug): 1.0.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
IBM i Project Explorer (vscode-ibmi-projectexplorer): 2.6.0
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
RPGLE (vscode-rpgle): 0.24.0
Server Ready Action (debug-server-ready): 1.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|n/a|
|CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/LENNONS2.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=LENNONS1
CURLIB=LENNONS1
HOME=/home/LENNONS
HOST=pub400.com
IFS_LIB=LENNONSB
IFS_SRCPF=VSCODE
LIB1=LENNONSB
LIBLS=LENNONSB LENNONS1 QGPL QTEMP QIWS
LOGIN=lennons
LOGNAME=lennons
MAIL=/var/spool/mail/lennons
OLDPWD=/home/LENNONS
PASE_USRGRP_LIMITED=N
PATH=/QOpenSys/pkgs/bin:/:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/LENNONS
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=71.63.120.199 63720 2222
SSH_CONNECTION=71.63.120.199 63720 185.113.5.134 2222
TZ=<UTC>0
USER=lennons
USERNAME=lennons
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#§$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPD0032:  Not authorized to command CRTLIB in library *LIBL.\nCPF0001:  Error found on CRTLIB command.",
    "cwd": "/home/LENNONS"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF2125:  No objects deleted.",
    "cwd": "/home/LENNONS"
  },
  {
    "command": "/QIBM/ProdData/IBMiDebugService/bin/stopDebugService.sh",
    "code": 126,
    "stderr": "bash: /QIBM/ProdData/IBMiDebugService/bin/stopDebugService.sh: /bin/sh: bad interpreter: Permission denied",
    "cwd": "/home/LENNONS"
  }
]
```
</details>

**Comment by SJLennon** [comment]
@worksofliam 
Seems like the same result ( using PuTTY):

```
Using username "lennons".
Pre-authentication banner message from server:
| *********************************************
| * WELCOME TO PUB400.COM - your public IBM i *
| * ----------------------------------------- *
| * Please take note of the following:        *
| * - all access is logged                    *
| * - please be polite and do not disturb     *
| *   other users!                            *
| * - this system is of limited support       *
| * - see https://pub400.com                  *
| *********************************************
|
| -> Enter your password for Logon below:
End of banner message from server
Authenticating with public key "rsa-key-20231122"
-bash-5.1$ MY_JAVA_HOME="/QOpenSys/QIBM/ProdData/JavaVM/jdk80/64bit" DEBUG_SERVICE_KEYSTORE_PASSWORD="pub400.com" /QIBM/ProdData/IBMiDebugService/bin/encryptKeystorePassword.sh | /usr/bin/tail -n 1
-bash: /QIBM/ProdData/IBMiDebugService/bin/encryptKeystorePassword.sh: /bin/sh: bad interpreter: Permission denied
-bash-5.1$

```
Maybe something strange about PUB400, but I have no idea how to track it down.

**Comment by sebjulliand** [comment]
I dug a bit and found a partial answer.

Since the shebang in those script is `/bin/sh`, the command interpreter will run the script with whatever `/bin/sh` is pointing at.
It points to this:
```shell
-bash-5.1$ ls -l /bin/sh
lrwxrwxrwx    1 qsys     0                62 Apr 23 2016  /bin/sh -> /QSYS.LIB/QSHELL.LIB/QZSHSH.PGM
```

On pub400, calling `/bin/sh` returns @SJLennon's error:
```shell
-bash-5.1$ /bin/sh
-bash: /bin/sh: Permission denied
```

I check the authority on the QSHELL/QZSHSH program and it looks OK:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/9ce5fcd8-9453-470e-9608-8bcfd4093ebe)
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/8cfc51a1-3daf-42c3-9dfd-7040f106fa02)

However, if we call the command with `sh`, it runs fine - like that:
```shell
MY_JAVA_HOME="/QOpenSys/QIBM/ProdData/JavaVM/jdk80/64bit" DEBUG_SERVICE_KEYSTORE_PASSWORD="pub400.com" sh /QIBM/ProdData/IBMiDebugService/bin/encryptKeystorePassword.sh | /usr/bin/tail -n 1
```

So maybe we can make a change in our code and add `sh` when we invoke these scripts from Code for IBM i. What do you think @worksofliam ?

**Comment by worksofliam** [comment]
@sebjulliand you're welcome to make that change, though I still suspect this issue may persist on pub400 due to how locked down it is and I believe that folder might be locked completely from users.

**Comment by SJLennon** [comment]
@worksofliam @sebjulliand 
I have access only to PUB400 so I can't compare how it is configured with any other machine. I have a similar problem trying to run bob on PUB400 (https://github.com/IBM/ibmi-bob/issues/271). is it possible for someone to compare the settings on another machine? Maybe we can convince Holger to make a change.

**Comment by worksofliam** [comment]
@SJLennon Ideally Holger would be the one to setup the certs, then make the `certs` directory readonly for all users.

**Comment by SJLennon** [comment]
@worksofliam @sebjulliand 
Update, in case this info is useful. 
After a long discussion on Ryver, this is a comment from Kevin Adler:
> Sam_L said:
> bin/sh') Object not found. Object is /QOpenSys/bin/sh.
> Sam_L
> 
> Well that's the problem. PASE has a quirky behavior for compatibility with stuff like this (which is barely documented). If the execution fails, it retries the execution with the path prefixed by /QOpenSys. So because /bin/sh is a symlink to QSH and can't be executed by PASE, /bin/sh shebangs would normally fail (rendering lots of extant scripts broken in PASE). So after the failure it retries with /QOpenSys/bin/sh.
> 
> For some reason on PUB400 this file doesn't exist, so that's why your script fails.

And his suggestion to Holger:

> @holgerscherer yeah, you could do CHKPRDOPT for PASE (SS1 opt 33 IIRC). /QOpenSys/bin should be a symlink to /QOpenSys/usr/bin (using relative link to usr/bin)
> 
> You can recreate with ln -s usr/bin /QOpenSys/bin

So feel free to close this if you wish, since it seems peculiar to PUB400.
