### ISSUE TITLE
Can't get debug certificates to generate after update?

### ISSUE THREAD

**Issue by alexlarouche** [codefori/vscode-ibmi#1772]
👉🏻 Failed to create certificate directory: /QIBM/ProdData/IBMiDebugService/bin/certs

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.6.4|
|Visual Studio Code version|1.85.1|
|Operating System|darwin_arm64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 10.1.1
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.6.1
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.16.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitHub Codespaces (codespaces): 1.16.5
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|n/a|
|CCSID|37|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|grep|iconv|GETNEWLIBL.PGM|||
|ls|setccsid||||
|md5sum|tar||||
|sort|||||
|stat|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "mkdir -p /QIBM/ProdData/IBMiDebugService/bin/certs",
    "code": 2,
    "stderr": "mkdir: cannot access directory /QIBM/ProdData/IBMiDebugService/bin.\n/QIBM/ProdData/IBMiDebugService/bin: Permission denied",
    "cwd": "/home/ABSALEXL"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"ABSALEXL\" && export HOST=\"absp1.apparelbusiness.com\" && export HOME=\"/home/ABSALEXL\" && export LIBLS=\"AML EDI5XXPGM EDI5XXDTA VALABSV60 MRKMAG KULIB KMDATA KMLIB ABSMAINT QGPL QTEMP ABSHELP DEV400S DEV400F DEV400O DEV400D ABSUPS\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/ABSALEXL"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"ABSALEXL\" && export HOST=\"absp1.apparelbusiness.com\" && export HOME=\"/home/ABSALEXL\" && export LIBLS=\"AML EDI5XXPGM EDI5XXDTA VALABSV60 MRKMAG KULIB KMDATA KMLIB ABSMAINT QGPL QTEMP ABSHELP DEV400S DEV400F DEV400O DEV400D ABSUPS\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/ABSALEXL"
  }
]
```
</details>

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the error appears.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by SravanDeep** [comment]
Having similar issue, content in output reads..

.: echo "This should be the only text!"
{
    "code": 0,
    "signal": null,
    "stdout": "This should be the only text!",
    "stderr": ""
}

.: echo $HOME && cd && test -w $HOME
{
    "code": 0,
    "signal": null,
    "stdout": "/home/SPOTULA",
    "stderr": ""
}

/home/SPOTULA: /QOpenSys/usr/bin/qsh
liblist
{
    "code": 0,
    "signal": null,
    "stdout": "QSYS        SYS\nQSYS2       SYS\nQUSRSYS     SYS\nQHLPSYS     SYS\nEDFIXES     SYS\nQSHELL      PRD\nQGPL        USR\nQTEMP       USR",
    "stderr": ""
}

/home/SPOTULA: /QOpenSys/usr/bin/qsh
system  "CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')"
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "CPF2111:  Library ILEDITOR already exists.\nCPC2206:  Ownership of object QZSHSYSTEM in QTEMP type *USRSPC changed."
}

/home/SPOTULA: [ -d "/tmp" ]
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/SPOTULA: ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx
/home/SPOTULA: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select OS_VERSION concat '.' concat OS_RELEASE as VERSION from sysibmadm.env_sys_info
/home/SPOTULA: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select max(ptf_group_level) as HIGHEST_DB2_PTF_GROUP_LEVEL from qsys2.group_ptf_info where PTF_GROUP_DESCRIPTION like 'DB2 FOR IBM I%' and ptf_group_status = 'INSTALLED';
/home/SPOTULA: ls $HOME/.vscode/codeforiserver-1.4.6.jar
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx not found"
}

/home/SPOTULA: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select job_name, authorization_name from qsys2.netstat_job_info j where local_port = 8005 group by job_name, authorization_name
{
    "code": 0,
    "signal": null,
    "stdout": "/home/SPOTULA/.vscode/codeforiserver-1.4.6.jar",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\nVERSION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \n---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n7.3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \n\n  1 RECORD(S) SELECTED.",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n\nHIGHEST_DB2_PTF_GROUP_LEVEL \n----------------------------\n                          33\n\n  1 RECORD(S) SELECTED.\n\nDB2>",
    "stderr": ""
}

{
    "code": 1,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\nJOB_NAME                     AUTHORIZATION_NAME \n---------------------------- -------------------\n\n  0 RECORD(S) SELECTED.",
    "stderr": ""
}

/home/SPOTULA: ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx not found"
}

/home/SPOTULA: mkdir -p /QIBM/ProdData/IBMiDebugService/bin/certs
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/QIBM/ProdData/IBMiDebugService/bin/certs: openssl genrsa -out debug_service_ca.key 2048 && openssl req -x509 -new -nodes -key debug_service_ca.key -sha256 -days 1825 -out debug_service_ca.pem -subj '/CN=XXXXXXX' && openssl genrsa -out debug_service.key 2048 && openssl req -new -key debug_service.key -out debug_service.csr -subj '/CN=XXXXXXX' && openssl x509 -req -in debug_service.csr -CA debug_service_ca.pem -CAkey debug_service_ca.key -CAcreateserial -out debug_service.crt -days 1095 -sha256 -sha256 -req -extfile <(printf "subjectAltName=DNS:XXXXXXX,IP:00.00.00.00") && openssl pkcs12 -export -out debug_service.pfx -inkey debug_service.key -in debug_service.crt -password pass:XXXXXXX
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "bsh: syntax error at line 1: `(' unexpected"
}

**Comment by sebjulliand** [comment]
Is bash your default shell?
Does it fail too if you run the command from within a terminal (in a directory of your choice)?
```shell
openssl genrsa -out debug_service_ca.key 2048 && openssl req -x509 -new -nodes -key debug_service_ca.key -sha256 -days 1825 -out debug_service_ca.pem -subj '/CN=XXXXXXX' && openssl genrsa -out debug_service.key 2048 && openssl req -new -key debug_service.key -out debug_service.csr -subj '/CN=XXXXXXX' && openssl x509 -req -in debug_service.csr -CA debug_service_ca.pem -CAkey debug_service_ca.key -CAcreateserial -out debug_service.crt -days 1095 -sha256 -sha256 -req -extfile <(printf "subjectAltName=DNS:XXXXXXX,IP:00.00.00.00") && openssl pkcs12 -export -out debug_service.pfx -inkey debug_service.key -in debug_service.crt -password pass:XXXXXXX
```

**Comment by sebjulliand** [comment]
I strongly suspect this has to do with the default shell.
When I run the command from bash, it runs fine.
If I run it from bsh, it crashes with the same error message.

I guess setting your default shell to bash should help: https://ibmi-oss-docs.readthedocs.io/en/latest/troubleshooting/SETTING_BASH.html

**Comment by mkwan01** [comment]
Only QSECOFR users can write to the path /QIBM/ProdData/IBMiDebugService/bin. If your user profile does not have QSECOFR authority, the behavior might be expected. Code for i can be changed to either only allow the QSECOFR users to generate the certificate, or save the certificate under a different path that is publicly writable.

**Comment by mkwan01** [comment]
Code for IBM i 2.9.0 contains a number of fixes for certificate generation. Please reopen the issue if you can still reproduce the problem in 2.9.0.
