### ISSUE TITLE
Object Browser doesn't view my sources

### ISSUE THREAD

**Issue by ghitti** [codefori/vscode-ibmi#1773]
👉🏻 Issue text goes here.

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.6.4|
|Visual Studio Code version|1.85.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 10.1.1
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.6.0
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
HTML Language Features (html-language-features): 1.0.0
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL (remote-wsl): 0.81.8
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R3M0|
|Tech Refresh|10|
|CCSID|65535|
|SQL|Disabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|
|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|
|git|iconv|GETNEWLIBL.PGM||
||ls|||
||setccsid|||
||tar|||
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "��$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF2111:  La libreria ILEDITOR esiste gi�.\nCPC2206:  � stata modificata la propriet� dell'oggetto QZSHSYSTEM in QTEMP di tipo *USRSPC.",
    "cwd": "/home/UFGHITTI"
  }
]
```
</details>

**Comment by ghitti** [comment]
This is my config

![image](https://github.com/codefori/vscode-ibmi/assets/5135428/5cc5fab4-58d3-4f22-9c6d-92d55862a4f5)

**Comment by sebjulliand** [comment]
Hi @ghitti ,
Please share the contents of your Code for IBM i output channel after you expand one of your source file and nothing shows up.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

If you're working on an IASP, make sure you defined it in your connection settings as well as in jour JOBD.

**Comment by ghitti** [comment]
Hi @sebjulliand, please find attached the info requested. Thanks in advance.

/home/UFGHITTI: /QOpenSys/usr/bin/qsh
system  "CHKOBJ OBJ(QSYS/UFGHITTI) OBJTYPE(*LIB) AUT()"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": "CPC2206:  � stata modificata la propriet� dell'oggetto QZSHSYSTEM in QTEMP di tipo *USRSPC."
}

/home/UFGHITTI: /QOpenSys/usr/bin/qsh
system  "DSPFD FILE(UFGHITTI/*ALL) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_t1wMAhcY)"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": "CPF9861:  Il file di emissione O_T1WMAHCY � stato creato nella libreria ILEDITOR.\nCPF9862:  Il membro O_T1WMAHCY � stato aggiunto al file di emissione O_T1WMAHCY nella libreria ILEDITOR.\nCPF3030:  558 record sono stati aggiunti al membro O_T1WMAHCY nel file O_T1WMAHCY in ILEDITOR.\nCPC2206:  � stata modificata la propriet� dell'oggetto QZSHSYSTEM in QTEMP di tipo *USRSPC."
}

/home/UFGHITTI: /QOpenSys/usr/bin/qsh
system  "QSYS/CPYTOIMPF FROMFILE(ILEDITOR/O_t1wMAhcY O_t1wMAhcY) TOSTMF('/tmp/vscodetemp-O_Tvj0aodx') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": "CPC2206:  � stata modificata la propriet� dell'oggetto QCPEXTEMPS in QTEMP di tipo *USRSPC.\nCPC7301:  File QACP848091 creato nella libreria QTEMP.\nCPC7305:  Membro QACP848091 aggiunto al file QACP848091 in QTEMP.\nCPC2206:  � stata modificata la propriet� dell'oggetto QACP848091 in QTEMP di tipo *USRSPC.\nCPC2206:  � stata modificata la propriet� dell'oggetto QACEXFLD12 in QTEMP di tipo *USRSPC.\nCPC2206:  � stata modificata la propriet� dell'oggetto QCP_I00001 in ILEDITOR di tipo *FILE.\nCPCA082:  Oggetto copiato.\nCPC2958:  Tutti i record copiati dal file O_T1WMAHCY in ILEDITOR\nCPC2191:  � stato cancellato l'oggetto QACP848091 in QTEMP di tipo *FILE.\nCPC2206:  � stata modificata la propriet� dell'oggetto QZSHSYSTEM in QTEMP di tipo *USRSPC."
}

**Comment by sebjulliand** [comment]
Thank you. These are the commands executed when you expand a library. It lists the source physical files. I assume that works since I see no error. What happens next in the output when you try to expand one of those source physical files?

**Comment by ghitti** [comment]
Nothing happens nor any output message.

![image](https://github.com/codefori/vscode-ibmi/assets/5135428/42a44bf8-8bd7-4a21-a6f4-542b24a506df)

**Comment by ghitti** [comment]
Hi @sebjulliand, this is the content after CPYTOIMPF command using IFS browser integrated in VS Code and Code For IBM i plugin. It seems a CCSID problem.

![image](https://github.com/codefori/vscode-ibmi/assets/5135428/754db87e-e266-45af-8242-cfcae6c1379e)

**Comment by ghitti** [comment]
If I manually launch the command CPYTOIMPF with this parameter " STMFCODPAG(*PCASCII) ", the stream file generated is readable.

**Comment by ghitti** [comment]
If i launch the original command with STMFCCSID(1208), it doesn't work (not readable as above).

                                                        
QSYS/CPYTOIMPF FROMFILE(ILEDITOR/O_U4IFTI5A O_U4IFTI5A) 
               TOSTMF('/tmp/vscodetemp-test')           
               MBROPT(*REPLACE)                         
               STMFCCSID(1208)                          
               RCDDLM(*CRLF)                            
               DTAFMT(*DLM)                             
               RMVBLANK(*TRAILING)                      
               FLDDLM(',')                              
               DECPNT(*PERIOD)                          
               ADDCOLNAM(*SQL)                          
                                                        
![image](https://github.com/codefori/vscode-ibmi/assets/5135428/8815d5bf-2c0a-4c1f-8d7e-c56455f0a1cf)

**Comment by ghitti** [comment]
maybe our system QCCSID is set to 65535

**Comment by ghitti** [comment]
If I enable "Enable SQL" parameter inside "features" tab I can now view the list of my source files as below
![image](https://github.com/codefori/vscode-ibmi/assets/5135428/847fd65e-b229-4218-a2cf-ecdb23a4e43a)

but now I'm not able to view the members inside source file due to this error:

![image](https://github.com/codefori/vscode-ibmi/assets/5135428/cf549bd1-d531-40f5-a4d1-18302eda58e3)

**Comment by worksofliam** [comment]
@ghitti Right, SQL mode won't work for you because your CCSID is 65535.

**Comment by worksofliam** [comment]
If you are getting that issue with `CPYTOSTMF` with `1208` outside of Code for IBM i, it's likely a system issue. I am doing some research to see what might cause that.

**Comment by chrjorgensen** [comment]
@ghitti Even with system value QCCSID set to 65535, you should be able to make it work - provided your userprofile has a correct CCSID (not 65535!) and the SSH server is configured correctly. Please follow the guidelines described in the docs:
https://codefori.github.io/docs/#/pages/tips/ccsid
https://codefori.github.io/docs/#/pages/tips/ccsid?id=setting-environment-variables

If your sourcefiles have CCSID 65535, you may be able to set your desired CCSID in `Source file CCSID` in the settings for the connection in Code for IBM i:

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/4d89a839-5bf2-4736-81cb-407f8093e75b)

However, we strongly advice to get your CCSID and SSH configurations right, so you can enable and use SQL to read your source file and member information - this would the best solution.

**Comment by ghitti** [comment]
Thanks @chrjorgensen, it works. 
My userprofile CCSID value was set as "*SYSVAL" (so 65535).
