### ISSUE TITLE
`checkObject` API should also accept a member property

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-ibmi#1792]

**Comment by krethan** [comment]
@worksofliam I got solution for this one done.

**Comment by krethan** [comment]
@worksofliam You can try this way too: 

async checkObject(object: { library: string, name: string, type: string, member?: string }, authorities: Authority[] = [`*NONE`]) {
    return (await this.ibmi.runCommand({
      command: `CHKOBJ OBJ(${object.library.toLocaleUpperCase()}/${object.name.toLocaleUpperCase()}) OBJTYPE(${object.type.toLocaleUpperCase()})${object.member?' MBR(' + object.member.toLocaleUpperCase() + ')':''} AUT(${authorities.join(" ")})`,
      noLibList: true
    })).code === 0;
  }
