### ISSUE TITLE
Locating Errors in SQLRPGLE compiles

### ISSUE THREAD

**Issue by SJLennon** [codefori/vscode-ibmi#1800]
I compile an SQLRPGLE program and have errors:
![image](https://github.com/codefori/vscode-ibmi/assets/67484051/039ccb3c-35c8-4575-b60e-d5ff1cd4739a)
When I click on the error a second tab is opened to highlight the error:
![image](https://github.com/codefori/vscode-ibmi/assets/67484051/97b2fb81-f599-4134-a859-4b26a7d10ce4)
I understand the issue with the SQL pre-compiler. My problem is that I tend to make the changes in the wrong tab. Would it be possible to make the second tab read only to protect me from myself?

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.6.5|
|Visual Studio Code version|1.85.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.6.1
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.16.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
RPGLE (vscode-rpgle): 0.25.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|n/a|
|CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/LENNONS2.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=LENNONS1
CURLIB=LENNONS1
HOME=/home/LENNONS
HOST=pub400.com
IFS_LIB=LENNONSB
IFS_SRCPF=VSCODE
LIB1=LENNONSB
LIBLS=LENNONSB LENNONS1 QGPL QTEMP QIWS
LOGIN=lennons
LOGNAME=lennons
MAIL=/var/spool/mail/lennons
OLDPWD=/home/LENNONS
PASE_USRGRP_LIMITED=N
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/LENNONS
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=71.63.120.199 50092 2222
SSH_CONNECTION=71.63.120.199 50092 185.113.5.134 2222
TZ=<UTC>0
USER=lennons
USERNAME=lennons
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#§$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx",
    "code": 2,
    "stderr": "ls: cannot access '/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx': No such file or directory",
    "cwd": "/home/LENNONS"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "RNS9308:  Compilation stopped. Severity 30 errors found in program.\nCPC0904:  Data area RETURNCODE created in library QTEMP.\nRNS9310:  Compilation failed. Program AR1E not created in library LENNONS1.",
    "cwd": "/home/LENNONS"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPC7301:  File QSQLPRE created in library QTEMP.\nCPC7305:  Member C added to file QSQLPRE in QTEMP.\nCPC3201:  Member C file QSQLPRE in QTEMP changed.\nRNS9307:  Diagnostic check of source is complete. Highest severity is 00.\nCPC0904:  Data area RETURNCODE created in library QTEMP.\nCPC7301:  File QSQLTEMP1 created in library QTEMP.\nCPC7305:  Member C added to file QSQLTEMP1 in QTEMP.\nRNS9308:  Compilation stopped. Severity 30 errors found in program.\nRNS9310:  Compilation failed. Program C not created in library LENNONS1.",
    "cwd": "/home/LENNONS"
  }
]
```
</details>

**Comment by worksofliam** [comment]
Actually this is likely an issue with case sensitivity in the tab you have open verses the path the errors return.

**Comment by SJLennon** [comment]
@worksofliam "case sensitivity in the tab you have open"
Don't I understand what you mean by this.

**Comment by worksofliam** [comment]
@SJLennon I am referring to the internal URL to the files that the users do not see.

**Comment by worksofliam** [comment]
Per our internal chat:

> Or we could search the editors to see if the file is opened already, and use that URI...
