### ISSUE TITLE
Filters returning nothing in object browser

### ISSUE THREAD

**Issue by RobMKH** [codefori/vscode-ibmi#1806]
Hi

Using 2.6.0 to 2.6.5 results in not being able to see source file members in the filters - they try to expand and I see nothing.  Rolled back to 2.5 and it works fine (hence why below it says we are using 2.5.0) - hope that helps isolate when the issue started.

I have enableSQL off in both versions.

OUTPUT from 2.5:
```
/home/HORTONR: system "DSPFD FILE(HORTONR/*ALL) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_5fAtfa9J)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_5FATFA9J created in library ILEDITOR.\nCPF9862: Member O_5FATFA9J added to output file O_5FATFA9J in library ILEDITOR.\nCPF3030: 41 records added to member O_5FATFA9J in file O_5FATFA9J in ILEDITOR.",
    "stderr": ""
}

/home/HORTONR: system "QSYS/CPYTOIMPF FROMFILE(ILEDITOR/O_5fAtfa9J O_5fAtfa9J) TOSTMF('/tmp/vscodetemp-O_Ri3XMcxl') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPC2958: All records copied from file O_5FATFA9J in ILEDITOR.",
    "stderr": ""
}
```

OUTPUT from 2.6.5
```
/home/HORTONR: /QOpenSys/usr/bin/qsh
system  "CHKOBJ OBJ(QSYS/HORTONR) OBJTYPE(*LIB) AUT()"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/HORTONR: /QOpenSys/usr/bin/qsh
system  "DSPFD FILE(HORTONR/*ALL) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_LOmvQmsN)"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/HORTONR: /QOpenSys/usr/bin/qsh
system  "QSYS/CPYTOIMPF FROMFILE(ILEDITOR/O_LOmvQmsN O_LOmvQmsN) TOSTMF('/tmp/vscodetemp-O_ulOS4Zrl') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}
```
<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.5.0|
|Visual Studio Code version|1.85.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Emmet (emmet): 1.0.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|n/a|
|Tech Refresh|n/a|
|CCSID|?|
|SQL|Disabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv||||
|git|setccsid||||
|grep|tar||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=HORTONR
CURLIB=HORTONR
HOME=/home/HORTONR
HOST=as400dvp
LIBLS=
LOGIN=hortonr
LOGNAME=hortonr
MAIL=/var/spool/mail/hortonr
OLDPWD=/home/HORTONR
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/HORTONR
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=10.255.67.37 58332 22
SSH_CONNECTION=10.255.67.37 58332 10.113.65.20 22
TZ=<GMT>0<BST>,M3.5.0/03:00:00,M10.5.0/03:00:00
USER=hortonr
USERNAME=hortonr
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/HORTONR"
  }
]
```
</details>

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the list doesn't appear in the version that does not work.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by RobMKH** [comment]
Cheers Liam

![image](https://github.com/codefori/vscode-ibmi/assets/157825025/0d328f1f-5ca9-4345-a69b-c67500b25b6b)

**Comment by worksofliam** [comment]
@RobMKH So you're able to switch between these versions **on the same system** and it's easy to recreate that one version works and one doesn't?

**Comment by RobMKH** [comment]
@worksofliam 

Yep - If I have 2.6.5 installed it doesn't work, roll back to 2.5.0 in the extensions, re-load and it works.

**Comment by worksofliam** [comment]
Okay. Can you get us full output (not screenshots) from both 2.6.5 and 2.5.0?

**Comment by RobMKH** [comment]
@worksofliam 

Apologies - I'm probably being a bit dense here.  The complete output was in the 2 code sections in the original post.  If I'm missing anything or a way to make it more verbose the please advise and I'll do it.

**Comment by worksofliam** [comment]
@RobMKH Yes, we also need all the initial logs from when the connection is made. Simply selecting all and copying will grab it all.

**Comment by RobMKH** [comment]
@worksofliam 

[output 2.5.0.txt](https://github.com/codefori/vscode-ibmi/files/14068332/output.2.5.0.txt)
[output 2.6.5.txt](https://github.com/codefori/vscode-ibmi/files/14068333/output.2.6.5.txt)

**Comment by worksofliam** [comment]
@RobMKH With 2.6.5, before connecting, would you mind right clicking on your connection and selecting 'Reload and Connect'? Please also collect all the output again. Thanks!

**Comment by RobMKH** [comment]
@worksofliam 

[output 2.6.5 reload and connect.txt](https://github.com/codefori/vscode-ibmi/files/14068466/output.2.6.5.reload.and.connect.txt)

**Comment by RobMKH** [comment]
@worksofliam 

 WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-python.python' wants API proposal 'registerIssueDataProvider' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:421  INFO Started local extension host with pid 107308.
log.ts:431  WARN [cmake-tools]: Couldn't find message for key cmake-tools.configuration.cmake.options.advanced.statusBarVisibility.variant.description.
log.ts:431  WARN [redhat.vscode-xml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
log.ts:431  WARN [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
console.ts:137 [Extension Host] Git installation not found.
w @ console.ts:137
console.ts:137 [Extension Host] Congratulations, your extension "vscode-ibmi-walkthroughs" is now active!
console.ts:137 [Extension Host] Congratulations, your extension "code-for-ibmi" is now active!
console.ts:137 [Extension Host] Developer environment: false
log.ts:421  INFO [perf] Render performance baseline is 48ms
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/8b3775030ed1a69b13e4f4c628c612102e30a681/node_modules/@vscode/vscode-languagedetection/dist/lib/index.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error

**Comment by worksofliam** [comment]
@RobMKH What method would you use the check to see if the SSHD is running/auth'ing as expected? Some SQL method perhaps?
