### ISSUE TITLE
CCSID Error when opening members in source physical files

### ISSUE THREAD

**Issue by micemen46** [codefori/vscode-ibmi#1814]
👉🏻Recently updated to version 2.6.5 and found that I could not open programs source members to view/edit. I tried to uncheck Enable SQL and this always reverted back. I have rolled back to 2.6.4 and this option is now unchecked by default. I am able to use VS Code to edit source physical members.

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.6.4|
|Visual Studio Code version|1.85.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitHub Copilot (copilot): 1.156.0
GitHub Copilot Chat (copilot-chat): 0.11.1
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|7|
|CCSID|65535|
|SQL|Disabled
|Source dates|Disabled

### Enabled features

|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|
|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|iconv|GETNEWLIBL.PGM|||
|ls||||
|setccsid||||
|tar||||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@£"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF2111:  Library ILEDITOR already exists.\nCPC2206:  Ownership of object QZSHSYSTEM in QTEMP type *USRSPC changed.",
    "cwd": "/home/WEBPGMR"
  },
  {
    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx",
    "code": 2,
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx not found",
    "cwd": "/home/WEBPGMR"
  }
  
]
```
</details>

**Comment by sebjulliand** [comment]
Hi @micemen46 !
Please share the contents of your Code for IBM i output channel after the member fails to open. Thanks!

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by micemen46** [comment]
I have updated to current version 2.6.5 and the enable SQL option remains unchecked and now is working fine
