### ISSUE TITLE
STRTCPSVR *DBG starts job but no ports are opened

### ISSUE THREAD

**Issue by jwoehr** [codefori/vscode-ibmi#1816]
**Describe the bug**
STRTCPSVR *DBG starts job but no ports are opened. netstat shows that 8001 and 8005 are not active. The debugger in Code for i won't connect.

- All the certs are there.
- The directory structures under /QIBM/ProdData and /QIBM/UserData look good
- No error message in the job log.
- No error message in the history log.
- No port restrictions.
- I changed the .env file on the server to 59001/59005 and restarted the debug server for an experiment, but those ports do not open either.

**To Reproduce**

- Normal configuration of Code for i debug
- Start debugger & debug server
- Attempt to connect

**Expected behavior**
Debugging works

**Screenshots**
![image](https://github.com/codefori/vscode-ibmi/assets/4604036/7cd1b960-66db-4677-8e28-3113e9e33e4c)

**Environment (please complete the following information):**
 - ![image](https://github.com/codefori/vscode-ibmi/assets/4604036/f51fa033-6af0-488c-b8e7-80e15ac11cc2)
 - IBM i OS 7.5

**Additional context**
LGTM but no go. What are we missing?

**Comment by mkwan01** [comment]
To use debug in code for i, you need to start the IBM i Debug Service first. IBM i Debug Service is NOT started using "STRTCPSVR *DBG". It is started using the "Start Debug Service" task provided by code-for-i. You can select the task from View > Command Palette..., and then select "IBM i Debug: Start Debug Service".

**Comment by sebjulliand** [comment]
Hi @jwoehr ,
if you switch to the latest prerelease , you'll have access to the IBM i debugger view that will help you with setting up and starting the debug service (as well as the debug server).

Clicking on the Debugger item after hovering over your connection in the status bar will take you there:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/64a7ded3-7db8-48e5-a5dd-163614feb79a)

![image](https://github.com/codefori/vscode-ibmi/assets/11096890/23f63a0a-8cc8-4534-8a73-51cd80165527)
