### ISSUE TITLE
Fix gencmlxml authority

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-ibmi#1817]
The `GENCMDXML` CL program needs to add a final call to `CHGAUT` to make it so the IFS object created can be update/deleted by any user (`*PUBLIC`)

https://github.com/codefori/vscode-ibmi/blob/master/src/languages/clle/gencmdxml.ts#L23

**Comment by krethan** [comment]
@worksofliam How is the IFS object created by GENCMDXML? I only see logic in there calling the API to get the command defaults.

**Comment by krethan** [comment]
I can tackle this one.

**Comment by krethan** [comment]
Branch 1817 is ready for this on my fork.

**Comment by sebjulliand** [comment]
@krethan feel free to open a PR from your fork, using a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for this issue so it get linked automatically.

**Comment by worksofliam** [comment]
Did this in vscode-clle.
