### ISSUE TITLE
Debug v2 - add subType attribute in launch configuration

### ISSUE THREAD

**Issue by mkwan01** [codefori/vscode-ibmi#1823]
The debug service v2 driver requires a new attribute "subType" in the launch configuration.
Possible values: batch | sep
batch: for batch debug
sep: for service entry point

For the current batch debug implementation, the change is to pass in a "subType" attribute with the value set to "batch".

Here is what a batch debug launch configuration looks like:

        {
            "type": "IBMiDebug",
            "request": "launch",
            "subType": "batch",

         .......
        }

**Comment by worksofliam** [comment]
Need detail from Morris about whether to pass in the SEP daemon port from the connection settings.
