### ISSUE TITLE
DSPFD fails for FILE(WDSCTEST/"%QUOTEST")

### ISSUE THREAD

**Issue by jonnyz32** [codefori/vscode-ibmi#1825]
Save us time! Click 'Report an Issue' from the Help and Support panel inside of VS Code after you have connected to a system.

**Describe the bug**
When trying to expand the file WDSCTEST/"%QUOTEST", no members are shown and there is an error notification thrown 
![image](https://github.com/codefori/vscode-ibmi/assets/42983653/410bc699-d1ef-4b67-b418-14e5c51e6b8e)

I see the following in the output log
```
/home/WDSCTEST: /QOpenSys/usr/bin/qsh
system  "DSPFD FILE(WDSCTEST/"%QUOTEST") TYPE(*MBR) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_cX5Gu5eK)"
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "CPD0105:  Built-in function not allowed for parameter FILE.\nCPF0001:  Error found on DSPFD command."
}

/home/WDSCTEST: /QOpenSys/usr/bin/qsh
system  "QSYS/CPYTOIMPF FROMFILE(ILEDITOR/O_cX5Gu5eK O_cX5Gu5eK) TOSTMF('/tmp/vscodetemp-O_1MRfXCUB') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "CPF5715:  File O_CX5GU5EK in library ILEDITOR not found.\nCPF2817:  Copy command ended because of error."
}

```

**To Reproduce**
1. Connect to roma system, with user WDSCTEST
2. Add WDSCTEST, to library list
3. Click on "%QUOTEST".FILE to expand it

**Expected behavior**
It should show the two members of this file.
![image](https://github.com/codefori/vscode-ibmi/assets/42983653/e2404af6-7d3d-4046-b88a-34f525e53d2c)

**Environment (please complete the following information):**
 - Extension version 2.6.5
 - IBM i OS version 7.4

**Additional context**

**Comment by worksofliam** [comment]
@jonnyz32 SQL enabled or disabled?

**Comment by sebjulliand** [comment]
@worksofliam this is partially fixed by https://github.com/codefori/vscode-ibmi/pull/1780; but then this happens.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/bde3e6da-dcd3-4841-bd32-58e05e1845f0)

**Comment by worksofliam** [comment]
@sebjulliand Was just recreating this on main myself. 

@jonnyz32 What CCSID is your user profile? `DSPUSRPRF` to find out. Thanks!

**Comment by sebjulliand** [comment]
This is the member text causing the issue.
It's VARGRAPHIC in UTF-16.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/245d4332-c7d6-40d6-b2de-84fc6c0bd59b)

**Comment by worksofliam** [comment]
@sebjulliand I am thinking this will be closed since of the CCSID work you've put in. Thoughts?

**Comment by sebjulliand** [comment]
@worksofliam agreed

**Comment by sebjulliand** [comment]
Even though opening the member may not work, I think.
