### ISSUE TITLE
Issue with User Library List and Object Browser

### ISSUE THREAD

**Issue by zalmang** [codefori/vscode-ibmi#1832]
The User Library List and Object browser aren't working.

The Library is list saying *** Not found *** and my filter in the object browser isn't showing any files or objects.Any help is greatly appreciated!! Logging into a different machine does NOT reproduce the issue. Obviously, I've tried reinstalling Code for i.

 Screenshot attached. 
UPDATE: logs attached:
 
[DB2ForIComponent.txt](https://github.com/codefori/vscode-ibmi/files/14211393/DB2ForIComponent.txt)
[CodeForIBMiLog.txt](https://github.com/codefori/vscode-ibmi/files/14211396/CodeForIBMiLog.txt)

[CodeForIBMi (1).pdf](https://github.com/codefori/vscode-ibmi/files/14200786/CodeForIBMi.1.pdf)

<hr />

 

 

|Context|Version|

|-|-|

|Code for IBM i version|2.6.5|

|Visual Studio Code version|1.86.0|

|Operating System|linux_x64|

 

 

<details>

<summary>Active extensions</summary>

 

```

Beautify (beautify): 1.5.0

COBOL (cobol): 10.2.5

Code Spell Checker (code-spell-checker): 3.0.1

Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0

Comment Anchors (comment-anchors): 1.10.4

Db2 for IBM i (vscode-db2i): 0.6.1

ESLint (vscode-eslint): 2.4.4

Emmet (emmet): 1.0.0

Eradani Extension (ec-generators): 0.11.6

Extension Authoring (extension-editing): 1.0.0

Git (git): 1.0.0

Git Base (git-base): 1.0.0

Git Graph (git-graph): 1.30.0

GitHub (github): 0.0.1

GitHub Copilot (copilot): 1.157.0

GitHub Copilot Chat (copilot-chat): 0.12.0

GitLens — Git supercharged (gitlens): 14.7.0

IBM i Debug (ibmidebug): 1.0.0

JSON Language Features (json-language-features): 1.0.0

JavaScript Debugger (js-debug): 1.86.1

Local Tunnel Port Forwarding (tunnel-forwarding): 1.0.0

Markdown All in One (markdown-all-in-one): 3.6.2

Markdown Math (markdown-math): 1.0.0

Merge Conflict (merge-conflict): 1.0.0

NPM support for VS Code (npm): 1.0.1

Node Debug Auto-attach (debug-auto-launch): 1.0.0

Server Ready Action (debug-server-ready): 1.0.0

TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0

```

</details>

 

 

<hr />

 

 

<details>

<summary>Remote system</summary>

 

|Setting|Value|

|-|-|

|IBM i OS|n/a|

|Tech Refresh|n/a|

|CCSID|?|

|SQL|Enabled

|Source dates|Disabled

 

### Enabled features

 

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|

|-|-|-|-|-|

|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|

|git|iconv|GETNEWLIBL.PGM|||

|grep|setccsid||||

|ls|||||

|md5sum|||||

|sort|||||

|stat|||||

|tar|||||

|tn5250|||||

</details>

 

 

 

<details>

<summary>Shell env</summary>

 

```bash

BUILDLIB=RAMIRO

CURLIB=RAMIRO

HOME=/home/RAMIRO

HOST=blue.*******.com

LIBLS=

LOGIN=ramiro

LOGNAME=ramiro

MAIL=/var/spool/mail/ramiro

OLDPWD=/home/ramiro

PASE_USRGRP_LIMITED=N

PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin

PWD=/home/RAMIRO

SHELL=/QOpenSys/pkgs/bin/bash

SHLVL=1

SSH_CLIENT=**************

SSH_CONNECTION=******************

TZ=<EST>5<EDT>,M3.2.0,M11.1.0

USER=ramiro

USERNAME=ramiro

_=/QOpenSys/usr/bin/env

```

</details>

 

 

 

<details>

<summary>Variants</summary>

 

```json

{

  "american": "#@$",

  "local": "#@$"

}

```

</details>

 

 

 

<details>

<summary>Errors</summary>

 

```json

[

  {

    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx",

    "code": 2,

    "stderr": "CPF2103: Library ECNCT37 already exists in library list.\n/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx not found",

    "cwd": "/home/RAMIRO"

  }

]

```

</details>

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the list doesn't appear or error appears.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by zalmang** [comment]
[CodeForIBMiLog.txt](https://github.com/codefori/vscode-ibmi/files/14211401/CodeForIBMiLog.txt)
[DB2ForIComponent.txt](https://github.com/codefori/vscode-ibmi/files/14211402/DB2ForIComponent.txt)

**Comment by worksofliam** [comment]
@zalmang Something is very odd indeed.

I am seeing `Generated from Blue` a lot in your output. Do you know where that would come from?

```
/home/RAMIRO: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"

        select os.OBJNAME as ODOBNM
             , coalesce(os.OBJTEXT, '') as ODOBTX
             , os.OBJATTRIBUTE as ODOBAT
          from table( SYSTOOLS.SPLIT( INPUT_LIST => 'RAMIRO', DELIMITER => ',' ) ) libs
             , table( QSYS2.OBJECT_STATISTICS( OBJECT_SCHEMA => 'QSYS', OBJTYPELIST => '*LIB', OBJECT_NAME => libs.ELEMENT ) ) os
      
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n                                                   **** Generated from Blue *****",
    "stderr": ""
}
```

**Comment by zalmang** [comment]
> @zalmang Something is very odd indeed.
> 
> I am seeing `Generated from Blue` a lot in your output. Do you know where that would come from?
> 
> ```
> /home/RAMIRO: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
> 
>         select os.OBJNAME as ODOBNM
>              , coalesce(os.OBJTEXT, '') as ODOBTX
>              , os.OBJATTRIBUTE as ODOBAT
>           from table( SYSTOOLS.SPLIT( INPUT_LIST => 'RAMIRO', DELIMITER => ',' ) ) libs
>              , table( QSYS2.OBJECT_STATISTICS( OBJECT_SCHEMA => 'QSYS', OBJTYPELIST => '*LIB', OBJECT_NAME => libs.ELEMENT ) ) os
>       
> {
>     "code": 0,
>     "signal": null,
>     "stdout": "DB2>\n                                                   **** Generated from Blue *****",
>     "stderr": ""
> }
> ```

That's the name of the machine.

**Comment by zalmang** [comment]
@worksofliam any ideas? Thanks

**Comment by chrjorgensen** [comment]
@zalmang It could be an issue with the library list defined in your connection... Please try and create a new connection for the same system and see if the new connection works for the same system...

**Comment by worksofliam** [comment]
@zalmang Looks like it could be:

'No results from SQL execution': https://codefori.github.io/docs/#/pages/tips/setup?id=no-results-from-sql-execution

**Comment by zalmang** [comment]
@worksofliam that's it! I'm trying to mark your last comment as an answer, but it's not letting me. All the best!
