### ISSUE TITLE
Cannot upload single file with IFS Browser

### ISSUE THREAD

**Issue by jhollon-jh** [codefori/vscode-ibmi#1833]
Version 2.6.3 introduced a bug that only allows uploading a folder to the IFS using IFS Browser. Single files such as .jar cannot be selected. 

Single file selection was working in prior versions.  Commit f332734 might be the culprit. 

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.6.3|
|Visual Studio Code version|1.86.0|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 10.2.5
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.6.1
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.16.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
SonarLint (sonarlint-vscode): 4.3.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
Veracode Greenlight for VS Code (veracode-greenlight-for-vs-code): 1.6.5272135
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|6|
|CCSID|65535|
|SQL|Disabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|
|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|
|chsh|iconv|GETNEWLIBL.PGM||
|git|setccsid|||
|grep|tar|||
|ls||||
|md5sum||||
|sort||||
|stat||||
|tn5250||||
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

**To Reproduce**
1. Go to 'IFS Browser'
2. Right click and select 'Upload'
3. Browse for a single file such as a JAR file
4. Only 'Select Folder' is available

**Expected behavior**
I need to be able to select a single file to upload to the IFS.

**Screenshots**
![image](https://github.com/codefori/vscode-ibmi/assets/154638371/455c614d-2bfa-43c4-a2f9-9b2aac0f2269)

![image](https://github.com/codefori/vscode-ibmi/assets/154638371/9b7568f9-e5d8-4e28-b774-1db0fe3456ad)

**Comment by sebjulliand** [comment]
Good catch @jhollon-jh , I'll fix that.
In the meantime, you can still upload a single file by drag and dropping it in the IFS browser.

**Comment by sebjulliand** [comment]
In it's current state, the API used only allows to select both files and folders on Mac.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/cf766180-c53b-4cba-bee8-effc3a01ed16)

I'll split the upload action in two.
