### ISSUE TITLE
No error messages

### ISSUE THREAD

**Issue by JonFP** [codefori/vscode-ibmi#1836]
👉🏻 Recent updates have resulted in loss of error messages. When I get compile errors I now have to resort to looking at the compile listing <shudder> as no problems appear.

Not exactly sure which update caused this as I only just noticed it.

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.6.5|
|Visual Studio Code version|1.86.1|
|Operating System|darwin_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 10.2.5
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.6.1
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.16.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
HTML CSS Support (vscode-html-css): 2.0.9
IBM i Debug (ibmidebug): 1.0.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
IntelliCode (vscodeintellicode): 1.2.30
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Edge Tools for VS Code (vscode-edge-devtools): 2.1.4
Node Debug Auto-attach (debug-auto-launch): 1.0.0
PHP Debug (php-debug): 1.34.0
PHP Intelephense (vscode-intelephense-client): 1.10.2
PHP IntelliSense (php-intellisense): 1.3.3
PHP IntelliSense (php-intellisense): 2.3.14
PHP Language Features (php-language-features): 1.0.0
Prettier SQL VSCode (prettier-sql-vscode): 1.6.0
RPGLE (vscode-rpgle): 0.26.0
Server Ready Action (debug-server-ready): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
ftp-simple (ftp-simple): 0.7.6
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|8|
|CCSID|37|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|grep|setccsid||||
|ls|tar||||
|md5sum|||||
|sort|||||
|stat|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=PARTNER400
CURLIB=PARTNER400
HOME=/home/PARIS
HOST=sidconf.idevcloud.com
LIBLS=LIBHTTP YAJL PARTNER400 QTEMP QGPL
LOGIN=paris
LOGNAME=paris
MAIL=/var/spool/mail/paris
OLDPWD=/home/PARIS
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/PARIS
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=10.29.5.48 51067 22
SSH_CONNECTION=10.29.5.48 51067 172.29.5.51 22
TZ=<EST>5<EDT>,M3.2.0,M11.1.0
USER=paris
USERNAME=paris
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF2111:  Library ILEDITOR already exists.",
    "cwd": "/home/PARIS"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF3232:  File RANI696957 in library ILEDITOR already exists.\nCPF3066:  Error creating output file RANI696957 in ILEDITOR.",
    "cwd": "/home/PARIS"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPC7301:  File QSQLTEMP1 created in library QTEMP.\nCPC7305:  Member PLAY added to file QSQLTEMP1 in QTEMP.\nCPD4090:  Printer device PRT01 not found. Output queue changed to QPRINT in library QGPL.\nSQL9001:  SQL precompile failed.",
    "cwd": "/home/PARIS"
  }
]
```
</details>

**Comment by JonFP** [comment]
I just found #1799 and it appears to be related. If I deselect "Show Active File Only" then the error messages reappear. 

BUT when I click on one of the error messages a second copy of the source is opened and the messages show up there - which is weird and confusing.

**Comment by worksofliam** [comment]
@JonFP we're working on a fix for that second file issue.

I will close this as we are tracking that already and your initial issue has been reviled.

**Comment by JonFP** [comment]
Gothcha - thanks.


Jon Paris

***@***.***

**Comment by SJLennon** [comment]
@JonFP 
You might also look at#1800.  Second window opens on SQLRPGLE for me.
