### ISSUE TITLE
Debug v2: debug service requires Java 11

### ISSUE THREAD

**Issue by mkwan01** [codefori/vscode-ibmi#1841]
Debug service v2 requires Java 11 to run. The following path need to be updated:
```ts
const MY_JAVA_HOME = `MY_JAVA_HOME="/QOpenSys/QIBM/ProdData/JavaVM/jdk80/64bit"`
```

The default path for Java 11 is:
`/QOpenSys/QIBM/ProdData/JavaVM/jdk11/64bit`

**Comment by worksofliam** [comment]
The plan is that future debug service versions will include a JSON file which will have a `version` property. This means we don't need to potentially add the logic to determine OS versions and PTFs. There is also the possibly a Java version which we may be able to use.

```json
{
  "version": 2,
  "java": 11
}
```
