### ISSUE TITLE
I can't access a /include service program

### ISSUE THREAD

**Issue by hn000246** [codefori/vscode-ibmi#1873]
Hello,
I'm trying to show the information of an /include sentence but I can't.
I press the right click of the mouse but i can't get the members Info.

I don't know what I'm missing..
I sending an image.
Best Regards,

![image](https://github.com/codefori/vscode-ibmi/assets/50391179/36791aa2-d81b-4831-9352-34120bdcbf2c)

**Comment by worksofliam** [comment]
Do you see anything when you just hover on the include statement?

**Comment by hn000246** [comment]
I don't know if I'm missing something in the configuration or settings for code for ibmi.

**Comment by worksofliam** [comment]
@hn000246 do you have the RPGLE extension installed?

**Comment by hn000246** [comment]
Yes, maybe i just want to know how to configure the outline view.
Maybe is that the problem.

**Comment by worksofliam** [comment]
@hn000246 to confirm, you have this extension, right?

https://marketplace.visualstudio.com/items?itemName=HalcyonTechLtd.vscode-rpgle

**Comment by hn000246** [comment]
Yes Barry I got it.

**Comment by hn000246** [comment]
Do you know some guide to know the correct way to see the /include or /copy member inside a program rpgile or sqlrpgle.?

**Comment by worksofliam** [comment]
@hn000246 When you hover over the include, do you see a message that the member is not found?

**Comment by hn000246** [comment]
Nothing happens, I click inside the /include member but nothing happens.

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after hovering your cursor over the include/copy directive.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by hn000246** [comment]
Hello @worksofliam 
I'm sending to you the Info yo ask me:
![image](https://github.com/codefori/vscode-ibmi/assets/50391179/8f46ce61-8060-421f-b361-e15ad54f9c59)

Tell me if you need more Info.

Best Regards,

**Comment by hn000246** [comment]
Hi @worksofliam did you find something wrong in the Source ?

**Comment by worksofliam** [comment]
@hn000246 No. I need the output pasted here directly from VS Code - not a photo. Thank you!

**Comment by hn000246** [comment]
@worksofliam I found the error 😬 ![image](https://github.com/codefori/vscode-ibmi/assets/50391179/2d38a45f-7d4e-45c0-a971-b363ba0d81d0)

The type of source was wrong, i got RPG Instead RPGLE , that was the solution.

Thanks and sorry. 🙌🏻
