### ISSUE TITLE
Unable to setup debug service

### ISSUE THREAD

**Issue by BrianGarland** [codefori/vscode-ibmi#1889]
I'm encountering issues when setting up the debug service in Code for i.

The first error was not being able to create the "certs" folder.  Developers don't have write access to the /QIBM path so VS Code wasn't able to create the folder.  

We do have a tool that gives us sudo-like capabilities so using that in an ACS session I manually created the /QIBM/ProdData/IBMiDebugService/bin/certs folder and gave myself access.  

After that Generate Certificates fails with "Failed to create certificates."  There is no additional information in the error message. 

Are there steps I can do manually to get this to work?

**Comment by worksofliam** [comment]
@BrianGarland regarding that directory: I have a PR coming that changes the default to a writable directory and also makes it configurable. This will solve that issue.

For the commands. I will pull them from the code and get back to you.

**Comment by worksofliam** [comment]
Should be fixed by #1895
