### ISSUE TITLE
Debug v2: new debug setting for Service Entry Point Daemon Port

### ISSUE THREAD

**Issue by mkwan01** [codefori/vscode-ibmi#1893]
Debug v2 has a new global setting called Service Entry Point Daemon Port. This is the host port that the client will connect to in order to retrieve SEP hit information. When a program run hits an SEP, we will use this port to send the program hit information back to the client.

![image](https://github.com/codefori/vscode-ibmi/assets/44405167/2efd4d08-6fbc-4334-ab31-639f871e638a)

Code for i may want to add this one to its connection settings for debug.

**Comment by worksofliam** [comment]
Simply add a new connection prop and add it to the debug settings in the connection settings.

This connection property will need to be passed into the `launch.json` when SEP is used.
