### ISSUE TITLE
Be able to compare active editor to another path

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-ibmi#1902]
So we don't have to navigate to the member in the UI

**Comment by chrjorgensen** [comment]
Maybe an context menu item for members in the Go To file list?

**Comment by worksofliam** [comment]
@chrjorgensen Beautiful idea. Perhaps a button that says "compare with active editor" on each of the files in the list!

**Comment by julesyan** [comment]
Building on this (not sure how feasible it is), maybe being able to compare with a local file? VSCode has a built in way to show local file to local file, and we show remote to remote, but there is no way to compare remote with local. Not sure how often of a situation this would be, but I always manually have to compare system files with my local files when debugging issues with inconsistent behaviour. 

I am going to try looking into comparing the active editor with another path. It would be very useful

**Comment by worksofliam** [comment]
@julesyan We were also thinking of adding a button to our 'Go To File' implementation (see `code-for-ibmi.goToFile`) to say something like 'Compare with Active File'.

**Comment by julesyan** [comment]
@worksofliam For clarification, would do you mean a button like this
<img width="543" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/20149481/39b51006-6ea9-4b83-957f-b8e292fc04f0">

**Comment by chrjorgensen** [comment]
@worksofliam Can we close this after PR #2049 being merged?

**Comment by worksofliam** [comment]
@chrjorgensen Absolutely!
