### ISSUE TITLE
Enhance CL API to provide help text

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-ibmi#1904]
https://www.ibm.com/docs/en/i/7.3?topic=ssw_ibm_i_73/apis/quhrhlpt.html

**Comment by chrjorgensen** [comment]
I'm a bit confused what should be in this extension and the IBM ILE CL extension - I would think help text should be in the latter?

**Comment by worksofliam** [comment]
@chrjorgensen yep should likely be in the CL extension. I'm thinking about moving all the CL logic from the base over there as part of this issue. The base currently installs all the requirements for the CL extension.

**Comment by worksofliam** [comment]
Closing as dupe
