### ISSUE TITLE
Need to be able to unselect/reset private key on Login Settings Panel so I can revert back to user/password login

### ISSUE THREAD

**Issue by richardschoen** [codefori/vscode-ibmi#1908]
**Is your feature request related to a problem? Please describe.**

Cannot remove private key from a Login Setting without going into the VS Code settings JSON file.  I needed to revert back to user/password login.

**Describe the solution you'd like**

Allow a button or other option on the login setting screen to "Remove Private Key" or "Reset Private Key". 

**Describe alternatives you've considered**

I can resolve by updating settings.json file via VS Code so not hypercritical, but this would make the Login Settings panel more consistent.

**Comment by worksofliam** [comment]
I believe that right clicking on the connection before connection, and either providing a new key or password should clear out the old auth method. I will double check this logic.

**Comment by richardschoen** [comment]
It didn't seem to remove anything when I provided a password. Let me know what you find.
