### ISSUE TITLE
Store translations as JSON

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-ibmi#1912]
Would love to get some thoughts on this idea I had:

Right now, we store our translation files as TypeScript and have an object for each language.

I'd like to keep this style, but instead of storing as TS, I'd like to store each language file as JSON instead in the same format.

Ideally this would make it simpler for us to:

1. Determine what IDs are missing from each language file compared to each other
2. Export in our docs what percentage of the extension is translated from English (since we can compare two JSON files)
3. Make it easier for people to contribute to translation if we can actually move away from editing the JSON manually in PRs and in a nifty translation tool or free spreadsheet software. We could export the French column from the spreadsheet right into JSON and import it into the codebase.

<img width="625" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/3708366/6359edce-82c7-4724-9314-57b78617842c">

**Comment by sebjulliand** [comment]
I'm all for it!
But it makes me think, at this point, shouldn't we go back using VSCode's i18n standard support? 😅

**Comment by chrjorgensen** [comment]
>I'm all for it!

What?! From TypeScript back to **_JavaScript_** Object Notation? 😉 

Count me in - would be nice to have context menu item etc. also the language pack...
