### ISSUE TITLE
Line truncation when x'00' encountered in source member

### ISSUE THREAD

**Issue by AndrewIBMi** [codefori/vscode-ibmi#1917]
**Describe the bug**
When a line contains the x'00' hexadecimal character (null), it will result in line truncation in VSCode.

**To Reproduce**
1. Replace a space in the middle of any line of code with x'00' (this could be done with the RDi Hex Edit Line action)
2. Save the source member
3. Open the source member in VSCode
4. All contents of the line following that hexadecimal character will be truncated

**Expected behavior**
RDi and SEU interprets these characters as spaces. It would be nice if VSCode did the same, as I've found a number of source members on my company's development system that contain these characters (not sure how they got there, though).

**Screenshots**
RDi Hex Editor with x'00' hexadecimal:
![image](https://github.com/codefori/vscode-ibmi/assets/161512398/13e05f80-4394-4c70-8f8a-b9cf315a7831)

VSCode's interpretation of the line:
![image](https://github.com/codefori/vscode-ibmi/assets/161512398/d6cfff3b-bf65-4404-9df4-e9db305543c2)

**Environment (please complete the following information):**
 - Extension version: v2.8.0
 - IBM i OS version: 7.4

**Comment by worksofliam** [comment]
@AndrewIBMi Thanks for this interesting issue!

Some initial thoughts from me:

1. I don't think we have any control over how the null character [specifically] gets rendered in VS Code. We've had more luck with source colors from SEU, but null is an entirely new beast.
2. I think if we were to support this, we would actually replace the null character with a space and then the nulls would be gone from any future saves. I believe @chrjorgensen would agree with me on this.
3. I believe if we support this kind of behavior, which is not normal, then it would go against what we are striving for (to be the best modern editor) and would, in-theory, continue to allow this kind of practice in the future. I think the entire core team would agree with me here.

If we do one of these, then it will be option 2. Let me get back to you!
