### ISSUE TITLE
Experiencing connection's configuration loss

### ISSUE THREAD

**Issue by mlstoppa** [codefori/vscode-ibmi#1924]
👉🏻 I use the extension daily, and what happens is that sometimes (possibly after an automatic update of the extension?) the connection's settings are lost. I mean, the connection definition still exists but all its features and characteristics are set to their default value. I usually realize it because I don't see the physical file source dates anymore, which is a must for me.
How can I check what happens more accurately to further investigate the issue?
When does the extension clean the existing settings for whatever reason?
Thank for any hints or suggestions

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.8.0|
|Visual Studio Code version|1.87.0|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
ARCAD-Elias (arcad-elias): 2.0.0-SNAPSHOT
COBOL (cobol): 10.2.21
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.8.0
ESLint (vscode-eslint): 2.4.4
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.16.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
Git Graph (git-graph): 1.30.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
IBM i Project Explorer (vscode-ibmi-projectexplorer): 2.6.5
JSON Language Features (json-language-features): 1.0.0
Live Server (LiveServer): 5.7.9
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
Prettier - Code formatter (prettier-vscode): 10.1.0
Prettier SQL VSCode (prettier-sql-vscode): 1.6.0
RPGLE (vscode-rpgle): 0.26.2
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|8|
|CCSID|65535|
|Default CCSID|37|
|SQL|Disabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=QGPL
CURLIB=QGPL
HOME=/home/LSTOPPA
HOST=<customer's system name>
LIBLS=QGPL QRPG LIBEXPAT ZMODLIB10 ZMODEDIIP <customer's libraries> QTEMP
LOGIN=lstoppa
LOGNAME=lstoppa
MAIL=/var/spool/mail/lstoppa
OLDPWD=/home/LSTOPPA
PASE_USRGRP_LIMITED=N
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/LSTOPPA
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=10.12.200.7 55389 22
SSH_CONNECTION=10.12.200.7 55389 172.27.150.12 22
TZ=<PST>8<PDT>,M3.2.0,M11.1.0
USER=lstoppa
USERNAME=lstoppa
WORKDIR=/home/LSTOPPA
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
]
```
</details>

**Comment by worksofliam** [comment]
@mlstoppa Are you able to recreate this if you switch between versions manually? You can do this on the extension page inside of VS Code?

**Comment by mlstoppa** [comment]
Hi @worksofliam As per Murphy's law, it hasn't happened anymore. I close the issue and I will open it again in case of need.
