### ISSUE TITLE
Debug v2: Rearrange two debug actions under the top level

### ISSUE THREAD

**Issue by mkwan01** [codefori/vscode-ibmi#1932]
We currently have two menu actions under the "Start Debugging" cascade menu:
- Batch
- Service Entry Point

![image](https://github.com/codefori/vscode-ibmi/assets/44405167/b55cda93-dd19-43cc-a66e-ba0225978131)

Putting the "Service Entry Point" action under "Starting Debugging" could be a little confusing, because this action only sets a service entry point. It does not bring up a debug session. 

We prefer to put the two menu actions as top level actions as follows:
Debug As Batch...
Set Service Entry Point...

These two menu items are in their own group and next to each other.

**Comment by Wright4i** [comment]
What if instead of `Start Debugging` it was just `Debug Menu`? Clear and to the point while keeping debug related actions grouped.

**Comment by mkwan01** [comment]
@Wright4i I think it is better to get rid of the cascade menu and use two top level actions "Debug As Batch..." and "Set Service Entry Point..." instead. In RDi, the "Set SEP" action is also in a different group than the batch debug action.
