### ISSUE TITLE
Ability to Connect to Multiple LPAR's at one time

### ISSUE THREAD

**Issue by grubster8** [codefori/vscode-ibmi#1933]
**Is your feature request related to a problem? Please describe.**
If I am in charge of managing Objects across multiple LPARS, each time I want to look at another box, I have to disconnect from LPAR 1, connect to LPAR 2.  If I want to go back, I have to repeate.  

**Describe the solution you'd like**
I would like to have multiple versions of the Object Browser Available and connected at the same time to for example, LPAR 1, LPAR 2, LPAR 3.  Then I can quickly navigate and look at multiple LPAR's without having to continuously login and out of each.  

**Describe alternatives you've considered**
As an alternative, continue doing what I am doing, disconnect\reconnect.  OR Open a second instance of VS Code.

**Additional context**
N/A

**Comment by chrjorgensen** [comment]
@grubster8 You should simply open a new instance of VS Code (`Shift-Ctrl-N`) and connect to the second LPAR from there. It only takes a few seconds, and you can have as many connections you like running simultaneously.

There are currently no plans to allow multiple connections in the same instance of VS Code.

**Comment by grubster8** [comment]
Thanks Christian!  I thought it was worth a shot!

________________________________
From: Christian Jorgensen ***@***.***>
Sent: Friday, March 15, 2024 9:07 AM
To: codefori/vscode-ibmi ***@***.***>
Cc: Gruby, Michael ***@***.***>; Mention ***@***.***>
Subject: *EXTERNAL* Re: [codefori/vscode-ibmi] Ability to Connect to Multiple LPAR's at one time (Issue #1933)


[Caution] This message appears to come from an external source. Be careful with links and attachments.

@grubster8<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_grubster8&d=DwMCaQ&c=4rszk0tbDAaZY6O0d-Pfs1TuN1jGE2SbgEMq3RG9IgA&r=tw2L5-8fKf1YYIHzg5d4OiY2muPmtDc_hJrInBudXpo&m=b4gngJcJgjfMGyW0a-yj5yDT9yuqguP_1K6L2z6exFWlBwyZn5DeHgSb6nvfUr3p&s=p-gpgEZctTFJSLNW-m_WBhiGilSSKVCvZfL-FUwRcso&e=> You should simply open a new instance of VS Code (Shift-Ctrl-N) and connect to the second LPAR from there. It only takes a few seconds, and you can have as many connections you like running simultaneously.

There are currently no plans to allow multiple connections in the same instance of VS Code.

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_codefori_vscode-2Dibmi_issues_1933-23issuecomment-2D1999746646&d=DwMCaQ&c=4rszk0tbDAaZY6O0d-Pfs1TuN1jGE2SbgEMq3RG9IgA&r=tw2L5-8fKf1YYIHzg5d4OiY2muPmtDc_hJrInBudXpo&m=b4gngJcJgjfMGyW0a-yj5yDT9yuqguP_1K6L2z6exFWlBwyZn5DeHgSb6nvfUr3p&s=-QuJGcTIE_y37gsm6HhTrpftX-uxW-e-6O_BiRTndiw&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANTV4MKYPWNGRF3Z7J47YJLYYL6CZAVCNFSM6AAAAABEU5UAAKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOJZG42DMNRUGY&d=DwMCaQ&c=4rszk0tbDAaZY6O0d-Pfs1TuN1jGE2SbgEMq3RG9IgA&r=tw2L5-8fKf1YYIHzg5d4OiY2muPmtDc_hJrInBudXpo&m=b4gngJcJgjfMGyW0a-yj5yDT9yuqguP_1K6L2z6exFWlBwyZn5DeHgSb6nvfUr3p&s=ZVeKTjjqr8vyPne2RkEhNWc4EFfH_ViuJ0tU6SAJanw&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

----------------------------------------------------------------------
Confidentiality Notice: This e-mail communication and any attachments may contain confidential and privileged information for the use of the designated recipients named above. If you are not the intended recipient, you are hereby notified that you have received this communication in error and that any review, disclosure, dissemination, distribution or copying of it or its contents is prohibited. If you have received this communication in error, please notify me immediately by replying to this message and deleting it from your computer. Thank you.

**Comment by grubster8** [comment]
@chrjorgensen  I wanted to add, this really would be a valuable feature.  The workaround to do a Code Compare using a Code compare extension in VS Code is not really viable with this solution. You have to Connect to LPAR 1, Save the source or copy to your local library or a text file, then re-connect to LPAR 2, save that source off, or maybe then you can have it open in a tab to compare then to your local copy.  By comparison, RDi does support this, so while maybe it shouldn't be a High Priority enhancement, to me there is value in adding this  Just like I can have a workspace with multiple GIT repo's Open on different tabs and easily do file compares.  I guess once we integrate  GIT, maybe this becomes a moot point and is easier to see all this.

**Comment by grubster8** [comment]
@chrjorgensen  This is great workflow, thank you, it worked! Exactly what i needed!    

We are moving to use a ARCAD for DevOps, we are implementing it now and working closely with ARCAD on it and should have it fully implemented by the end of the year... course this uses GIT.  We have had some challenges with our DB complexity that we are working through with them right now.
