### ISSUE TITLE
Failed to create certificates - IBM i debug service

### ISSUE THREAD

**Issue by cervantesandres** [codefori/vscode-ibmi#1942]
I'm encountering an issue with the debug service on IBM i. Whenever it attempts to generate certificates, it fails and displays an error message stating, "failed to create certificates". Interestingly, it does successfully create the directory IBMiDebugService/bin/certs. 

It's worth noting that required PTFs are installed and the user executing this operation possesses admin rights. 

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.8.0|
|Visual Studio Code version|1.87.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|8|
|CCSID|37|
|Default CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|ILEDITOR.GETNEWLIBL|QZDFMDB2.PGM|startDebugService.sh|
|git|iconv|||||
|grep|setccsid|||||
|ls|tar|||||
|md5sum||||||
|sort||||||
|stat||||||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

**Comment by cervantesandres** [comment]
I see this on output terminal

/QIBM/ProdData/IBMiDebugService/bin/certs: openssl genrsa -out debug_service_ca.key 2048 && openssl req -x509 -new -nodes -key debug_service_ca.key -sha256 -days 1825 -out debug_service_ca.pem -subj '/CN=h1tst.hatcocorp.com' && openssl genrsa -out debug_service.key 2048 && openssl req -new -key debug_service.key -out debug_service.csr -subj '/CN=h1tst.hatcocorp.com' && openssl x509 -req -in debug_service.csr -CA debug_service_ca.pem -CAkey debug_service_ca.key -CAcreateserial -out debug_service.crt -days 1095 -sha256 -sha256 -req -extfile <(printf "subjectAltName=DNS:h1tst.hatcocorp.com,IP:10.20.16.22") && openssl pkcs12 -export -out debug_service.pfx -inkey debug_service.key -in debug_service.crt -password pass:
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "bsh: syntax error at line 1: `(' unexpected"
}

**Comment by worksofliam** [comment]
@cervantesandres I would recommend setting your default shell to bash to solve this. We add better warnings about this in an upcoming release.

**Comment by cervantesandres** [comment]
![Visual Studio Code](https://github.com/codefori/vscode-ibmi/assets/50704403/414b29e5-4fde-4864-9456-ec0bd3128904)
VSCode Terminal was set to bash and error is still there.

**Comment by worksofliam** [comment]
@cervantesandres Not the VS Code terminal. You need to set bash as your default shell on your user profile.

**Comment by cervantesandres** [comment]
@worksofliam This is the content of my .profile in the home directory.
![image](https://github.com/codefori/vscode-ibmi/assets/50704403/6b05334e-ea36-4de2-9a1b-fb99132fda00)

**Comment by cervantesandres** [comment]
![image](https://github.com/codefori/vscode-ibmi/assets/50704403/fb24757b-68c8-4cf9-96a7-198ce10b637c)

I tried to set the default shell with the above command, but it error out. I can't seem to find any reference on how to set the default shell.

**Comment by SJLennon** [comment]
@cervantesandres 
This may help: https://ibmi-oss-docs.readthedocs.io/en/latest/troubleshooting/SETTING_PATH.html#highly-recommended-adjust-your-path-permanently

**Comment by cervantesandres** [comment]
@SJLennon thank you for the reference document. I follow every step defined on the document but I'm still unable to create the certificates. 
![image](https://github.com/codefori/vscode-ibmi/assets/50704403/36d73a0b-706d-4599-b44d-92d290b87ff2)

vscode output log
![image](https://github.com/codefori/vscode-ibmi/assets/50704403/510f8727-19ec-42bf-bfb2-a4151e58400f)

**Comment by cervantesandres** [comment]
@SJLennon @worksofliam I got it working. Thank you for your assistance.
