### ISSUE TITLE
In creating an action be able to make extension *ALL or *ANY or use a pattern when specifying extension

### ISSUE THREAD

**Issue by alcampin** [codefori/vscode-ibmi#1943]
Type: <b>Feature Request</b>

When creating an Action, I would like to be able to specify *ALL or *ANY for the extension type and have the Action work for any source type. 

What, also, might be good is if you had a way to specify the beginning of a name and have it pattern match against the name like CRT* would only show actions for Create extenrsions so if put a name pattern of iB* it would only show the iBuild extension. Does the ability to do a pattern match on extension already exist maybe? 

I am requesting this because my iBuild tool (www.sourceforge.net/projects/iBuild) works with any source type and I want a user to not have to edit the action for a new source type. 

Extension version: 2.8.0
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by worksofliam** [comment]
Hi @alcampin 

You can try `GLOBAL` in place of an extension. Let me know if that works.

**Comment by alcampin** [comment]
Yes that does seem to work. Not sure how it works because it brings up
other extensions. Is there documentation on GLOBAL works?

**Comment by worksofliam** [comment]
@alcampin no docs really for it. It's a special flag that means this action applies to any member/source no matter the extension.

**Comment by alcampin** [comment]
I still like the idea of a pattern. Something like @P *RPG* would pick
anything with RPG in name or @P IB* would pick anything starting with IB.
