### ISSUE TITLE
Unable to connect to IBMi

### ISSUE THREAD

**Issue by jstillman01** [codefori/vscode-ibmi#1950]
Every time I try to connect it gives a ECONNRESET error, the SSH port is open.

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.8.0|
|Visual Studio Code version|1.87.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
JSON Language Features (json-language-features): 1.0.0
MDOpen for MDCMS 8.6.x (mdopen-8-6): 0.0.26
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

**_Not connected_** 🔌

**Comment by chrjorgensen** [comment]
@jstillman01 Please try using another SSH client, e.g. [PuTTY](https://www.putty.org/), and verify that you have SSH access from your workstation and your user. Post the results here...

**Comment by jstillman01** [comment]
Thank you for your time, this issue has been solved on our end.

**Comment by sebjulliand** [comment]
@lancenapier-cloud yes, unless your sshd service runs on another port.

Run `STRTCPSVR *SSH`D to start sshd.
