### ISSUE TITLE
IBM i extension icon disappeared and cannot get it back.

### ISSUE THREAD

**Issue by alcampin** [codefori/vscode-ibmi#1952]
Type: <b>Bug</b>

Was using VS Code with IBM i extension and suddenlly the IBM i extension icon disappeared and I did not have a connection to the IBM i any longer. 

Tried uninstalling extension and uninstalled VS Code and reinstalling but when you install the Code for IBM i extension IBM i does not appear. 

Any idea how to get this back. Is there something we can delete to clear out any configurations? Help

Extension version: 2.8.0
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 6850U with Radeon Graphics      (16 x 2695)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|14.77GB (4.66GB free)|
|Process Argv|--crash-reporter-id c36b22a8-af9c-4735-915b-181553629e17|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30992800
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonaic:30996667
7ghi1836:30988842
dsvsc021:30996838

```

</details>

**Comment by worksofliam** [comment]
If you press F1 and search for 'Focus Connection Browser' does the item come up?

**Comment by alcampin** [comment]
No it does not.

**Comment by alcampin** [comment]
Is there someplace that VS Code stores configuration information beside "C:\Users\<User Name>\.vscode"?

**Comment by worksofliam** [comment]
@alcampin can you share a screenshot that shows the extension is installed?

**Comment by alcampin** [comment]
![image](https://github.com/codefori/vscode-ibmi/assets/24906219/5d0fdad6-6390-4fc0-b1b8-0d15f0e44272)

Here is screen image.

**Comment by sebjulliand** [comment]
Hi @alcampin ,
looks like this is your problem:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/1c0bd4eb-89dd-4ef8-94fe-0db4406576de)

Code for IBM i is disabled because another extension it depends on is disabled.
Luckily, it doesn't depend on a lot of other extensions. If you click on the `Dependencies` tab, you'll see the list of extensions it depends on:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/2c9db1ce-4e1d-4d3c-b76f-d3979c3b839c)

Make sure all three extensions are installed and enabled.

Hope this helps!
