### ISSUE TITLE
All IBM i connections disappeared

### ISSUE THREAD

**Issue by JonFP** [codefori/vscode-ibmi#1955]
Last week my settings json got corrupted somehow and as a result (and under guidance from Liam) I removed the offending item that was causing the json to be invalid.  The file is now valid json. After the edit all was working.

Today I opened up VS code to do some work and all of my IBM i connections have disappeared.  

settings.json is attached.

P.S. At one point last week just prior to the corruption issue, when I tried to view settings.json VS Code kept showing me an empty file. But the real file was there in the usual spot.
 
<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.8.0|
|Visual Studio Code version|1.87.2|
|Operating System|darwin_x64|

<details>
<summary>Active extensions</summary>

```
[settings.json](https://github.com/codefori/vscode-ibmi/files/14747160/settings.json)

COBOL (cobol): 10.3.10
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.8.2
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.16.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
HTML CSS Support (vscode-html-css): 2.0.9
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
Merge Conflict (merge-conflict): 1.0.0
Microsoft Edge Tools for VS Code (vscode-edge-devtools): 2.1.5
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
Prettier SQL VSCode (prettier-sql-vscode): 1.6.0
RPGLE (vscode-rpgle): 0.26.3
TODO Highlight (vscode-todo-highlight): 1.0.5
ftp-simple (ftp-simple): 0.7.6
```
</details>

<hr />

**_Not connected_** 🔌
[settings.json](https://github.com/codefori/vscode-ibmi/files/14747171/settings.json)

**Comment by worksofliam** [comment]
@JonFP What changes happen if you try and make a new connection?

**Comment by JonFP** [comment]
I hadn't dared try but here goes ...

OK - it connects just fine and adds the data to the settings.json (I had it open in the editor at the time).  Connection works fine, I can add filters etc. BUT ...

As soon as I disconnect, the connection is not added to the list and I have to build a new one again.  It did however add the config to the settings.json _but_ not in the same place as the others.

Here's the relevant part of the file:
```
{
    "sshfs.configs": [
        {
            "host": "sidconf.idevcloud.com",
            "label": "SiD Conf SSH",
            "name": "sidconf",
            "username": "paris",
            "root": "/home/paris"
                   },
        {
            "host": "ideveloper",
            "name": "sid-p400",
            "root": "/www/partner400",
            "username": "paris",
            "privateKeyPath": "/Users/jonparis/.ssh/id_rsa"
        },
        {
            "name": "sidmainsite",
            "host": "ideveloper",
            "root": "/www/sidcss/htdocs",
            "privateKeyPath": "/Users/jonparis/.ssh/id_rsa"
        },
        {
            "name": "SIDMainWeb",
            "host": "ideveloper",
            "root": "/www/sidcss/htdocs",
            "username": "paris"
        },
        {
            "name": "jons_home_dir",
            "host": "ideveloper",
            "root": "/Home/Paris",
            "privateKeyPath": "/Users/jonparis/.ssh/id_rsa",
            "username": "paris"
        }
    ],
    "sshfs.configpaths": [],
    "editor.accessibilitySupport": "off",
    "code-for-ibmi.connections": [
        {
            "name": "Test",
            "host": "sidconf.idevcloud.com",
            "port": 22,
            "username": "paris"
        }
~~~
The new connection is called Test and is at the end in a new group.  The original connections are still at the top.

**Comment by worksofliam** [comment]
@JonFP I believe there is some confusion here.

`sshfs.configs` is not used by Code for IBM i. That is used by another connection. We use `code-for-ibmi.connections` for the connections only. This might be why you see it 'appearing at the bottom'

**Comment by jkyeung** [comment]
I don't have a `"sshfs.configs"` block. My connections are in `"code-for-ibmi.connections"` (as shown in Jon's excerpt above), with the actual nitty-gritty details in `"code-for-ibmi.connectionSettings"`.

**Comment by SJLennon** [comment]
@JonFP Since your setting.json show connections for me on Win 10, is this possibly something Mac related? Can the Mac cache files, or set sym-links, or something else?  Know nothing about Macs...

**Comment by sebjulliand** [comment]
@JonFP maybe this has something to do with settings synchronization?
You can check out the Sync Data using this command from the palette:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/9639485b-d706-43b9-af96-4605f285985e)

Think in the Sync Activity panel, look out for a `Settings` change that may have erase your connections:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/e609f11b-caf8-44d3-8e76-b484733e748a)

You can click on `settings.json` to compare before and after sync:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/19871267-7ddb-48b2-88dd-70b039988dc5)

It's a least worth having a look at a sync that may have happened between yesterday and today 🤔

**Comment by JonFP** [comment]
Thanks @sebjulliand but that option does not appear for me. As far as I know I have never turned on sync and so all I see are these options:
![2024-03-27_16-45-50](https://github.com/codefori/vscode-ibmi/assets/13474625/90a58708-304c-4f59-84bb-649e1bef9c2a)

**Comment by JonFP** [comment]
Decided to give up and revert to a settings.json copy from 4 weeks ago.  No difference - still no IBM i connections even though they are there in the file.

I really don't know what to try next - total reload and do everything over ??

**Comment by SJLennon** [comment]
@JonFP Is it possible that you have some other extension that is now interfering? Maybe a long shot, but disable all other extensions and see if it makes any difference?
