### ISSUE TITLE
Passwords in Cleartext

### ISSUE THREAD

**Issue by AARPETERSON** [codefori/vscode-ibmi#1967]
Hello,

Writing to inform of a security vulnerability I have discovered. 

"C:\Users\username\AppData\Roaming\Code\User\settings.json" 

This json file contains all of the code for IBM i connections such as host, port, user and password. **The password is stored in cleartext** format which is a major security concern, especially if organizations want to use this extension for VS Code.

**Comment by worksofliam** [comment]
@AARPETERSON You can safely remove the passwords from the configuration file. This used to be the case a long time ago when extension development was first starting out, but we now store passwords securely in the OS keystore, outside of user space.
