### ISSUE TITLE
Error message - "EQAVS1008E - No active socket connection to the Remote Debug Service"

### ISSUE THREAD

**Issue by blhowie66** [codefori/vscode-ibmi#1974]
Description of problem :

I'm trying to begin using the IBM i Debug extension to debug code.  I created the sample program that Liam created in his instructional video for debugging, compiled it and was attempting to debug it for the first time.  I was having the following issue, and Liam suggested creating an Issue here on Github.

I am receiving a  "EQAVS1008E - No active socket connection to the Remote Debug Service" error when trying to debug a program in VS Code for IBM i.

**To Reproduce**
1.  Connect to the IBM i partition - works fine
2.  Navigate through the filter in the object browser to the source member to debug - works fine
3.  Click to open the source member - works fine
4.  Identify breakpoints - works fine
5.  Click on icon to "Start Debugging Active Source" - works fine
6.  Enter password for my user profile as required - works fine
7.  Command is presented to call the program, press Enter to confirm - works fine
8.  I'm presented with a Visual Studio Code dialog box that says that "<Our IBM I partition> on port <specifies port> could not be connected.  Message received:  connect ECONNREFUSED <IP address of system>:<port number>".  Also in the status area in lower right-hand corner of window the EQAVS1008E message is shown.

**Expected behavior**
After steps 1-7 I expected the program to begin executing and stop at the breakpoint

**Screenshots**

Screenshots added

![image_2024-04-04_095645105](https://github.com/codefori/vscode-ibmi/assets/75441937/56b8be74-7967-449e-925e-5031d39acfe5)
![image](https://github.com/codefori/vscode-ibmi/assets/75441937/b341659f-2388-4cb5-a243-894d1584e075)

**Environment (please complete the following information):**
 - Extension version IBM i Debug extension version 1.0.0
 - IBM i OS version 7.4
 - Visual Studio Code version 1.87.2

**Additional context**
I went through the IBM i Debug walkthrough in VS Code and completed all the steps, including clicking to start the debug service.

Any help on this would be most appreciated.  Thanks!

**Comment by sebjulliand** [comment]
Hi @blhowie66 ,
can you run the following SQL query and see if any result shows up?
```
select * from qsys2.netstat_job_info where local_port = 8005
```
Replace `8005` but the correct port number in case your debug service uses another port.

**Comment by sebjulliand** [comment]
OK so the debug service is not running, even though you tried to start it.

First, check that the service certificate has been correctly generated in the location defined in your settings:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/3427aa37-4a63-4f5f-a65d-471105b2c26b)

Then, if the `debug_service.pfx` file is found in there, try strting the service again. Press F1 and run this command:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/95bab601-043c-42f7-aebd-b9ed9fdfb011)

If no error message shows up after a few seconds, run the query above to check if there is a job listening on port 8005. If there is, you'll be good to try to debug again.
If not, check out any error message under the `Code for IBM i` output and paste its content here.
![code for i output](https://github.com/codefori/vscode-ibmi/assets/11096890/88bc7363-2402-419f-b173-309358b914b9)

**Comment by SJLennon** [comment]
FWIW: I have the same problem/error messages on PUB400.COM. Port is 8005, the default I believe.

**Comment by blhowie66** [comment]
@sebjulliand ,

That did the trick!  It's now working!  I guess I assumed that the button in the walkthrough to start the service started it up, but maybe not?  Thanks SO MUCH!

@worksofliam , thanks again SO MUCH for your help getting this working.  I'm excited to dig in and play around more with VS Code for IBM i!

**Comment by sebjulliand** [comment]
You're welcome @blhowie66 , glad it works now!
FYI, we're working on an enhancement that should help with this kind of issues: https://github.com/codefori/vscode-ibmi/pull/1954


Happy debugging! 😁

**Comment by SJLennon** [comment]
I tried the Start Debug Server on PUB400 and then got this error message when I tried to debug:

![image](https://github.com/codefori/vscode-ibmi/assets/67484051/c9f62135-cbac-49f1-98a9-d9cc250c11d0)

Something needed on PUB400?

**Comment by sebjulliand** [comment]
> I tried the Start Debug Server on PUB400 and then got this error message when I tried to debug:
> 
> ![image](https://private-user-images.githubusercontent.com/67484051/319680606-c9f62135-cbac-49f1-98a9-d9cc250c11d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNDg3MDUsIm5iZiI6MTcxMjI0ODQwNSwicGF0aCI6Ii82NzQ4NDA1MS8zMTk2ODA2MDYtYzlmNjIxMzUtY2JhYy00OWYxLTk4YTktZDljYzI1MGMxMWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE2MzMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NzI0ZjFjNzg4YTc3ZTgzZTllY2JhYmE0N2M2YzM4MGY1N2YzOWI1YTE4NzAxZDQyNjJkY2FiMzk4MjNlYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L7zERudQ9MUxJkCDgCsNKs_p8hGRRJTb_iCpE_6z4T4)
> 
> Something needed on PUB400?

First, it seems that the debug server is down (if anyone here has enough authority to run `STRDBGSVR`, that would be great).
Second, that error looks like there is a mismatch between the service certificate and your local client certificate.
The service certificate seems to have been generated under `/QIBM/UserData/IBMiDebugService/bin/certs` on PUB400. Make sure you have this path in your settings and click on `Import new certificate`. That also implies that `Debug securely` is enabled in your settings, but I'm not sure it is required. Disabling it may help avoiding this issue (unless secured debug is required on PUB400...I don't know).

Hope this helps!
