### ISSUE TITLE
Updates to VSCode are making my IBM i connections disappear

### ISSUE THREAD

**Issue by amurphy-lp** [codefori/vscode-ibmi#1982]
👉🏻 Whenever VSCode does an update the IBM i connections disappear

I setup my IBM i connections, filters, library list, etc. and everything works fine.

Then after a few days, I see this popup when starting VSCode:
![image](https://github.com/codefori/vscode-ibmi/assets/166630780/dac5f537-6ffd-4712-b69e-2d2c3bcddbf3)

Then when VSCode opens my connections are gone:
![image](https://github.com/codefori/vscode-ibmi/assets/166630780/bea01810-2d6d-4059-9c00-ad870e31a35f)

Please can you investigate.

Thanks,
Andrew

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.8.0|
|Visual Studio Code version|1.87.0|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 10.3.25
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.10.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.16.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.5
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
anycode (anycode): 0.0.73
```
</details>

<hr />

**_Not connected_** 🔌

**Comment by worksofliam** [comment]
@amurphy-lp Did all your VS Code setting get changed as well? I already looked into this and I think it's a VS Code issue and not Code for IBM i.

**Comment by amurphy-lp** [comment]
@worksofliam How can I check this?

The 'Thunder Client' extension did not lose it's settings, but 'SSH FS' does.

**Comment by amurphy-lp** [comment]
Just checked the properties of the settings.json file and even though I created IBM i connections a few days ago, it shows the Date modified as:
10 ‎March ‎2024, ‏‎21:54:06

![image](https://github.com/codefori/vscode-ibmi/assets/166630780/dc6ff043-0ca8-4e0c-999c-787841ec4be3)

**Comment by worksofliam** [comment]
Possible dupe of #1952

**Comment by amurphy-lp** [comment]
Hmmm, I am not sure as I still have the Code for IBM i icon on the left, it is just my connections are gone due to settings/json being replaced.

**Comment by amurphy-lp** [comment]
This appears to be due to a missing file from the installation. After removing and reinstalling a couple of times, it seems to be functioning correctly now.

**Comment by amurphy-lp** [comment]
The issue has not occurred since the reinstallation, so I am closing the ticket.
