### ISSUE TITLE
Guarantee UTF8 encode for source that is deployed, even if to V7R3

### ISSUE THREAD

**Issue by edmundreinhardt** [codefori/vscode-ibmi#1995]
**Is your feature request related to a problem? Please describe.**
When deploying source and the default PASE CCSID for the SSH daemon is not 1208. (It is typically 819 in V7R3 and sometimes in newer release as well).  In this case all stream files created in the IFs are tagged with the wrong CCSID (e.g. 819) instead of 1208.  Then the compiles of source containing NLS characters will fail even if the TGTCCSID is correctly specified. For example the source in https://github.com/IBM/bob-recursive-example/tree/master/globalization

**Describe the solution you'd like**
For all new files uploaded to the IFS call `setccsid 1208 file1 ... filen`

**Describe alternatives you've considered**
The alternative is to ensure that the CCSID of the SSH daemon is 1208.  Perhaps restarting the daemon if it is not (would be very disruptive to others on the host and would require elevated authority.  THere would be version specific prerequisites and strategies.

**Additional context**
Long discussion with the platform experts https://ibmidevelopment.slack.com/archives/CA4EFUUGM/p1713459136139049

**Comment by worksofliam** [comment]
@edmundreinhardt We are thinking about your issue but if you'd like it done faster I would recommend working on a PR.

Also, please do not share links that are unavailable to those that might work on this. Cheers!

**Comment by sebjulliand** [comment]
@edmundreinhardt , could you run this command through SSH on a system where files deployed by Code for IBM i are created with CCSID 819, please? Then give me the output. I'd like to check something.
```bash
touch codeforiccsidtest && attr codeforiccsidtest CCSID && rm codeforiccsidtest
```
I need to find a reliable way to check if files deployed will need `setccsid`.

**Comment by edmundreinhardt** [comment]
-bash-5.2$ 
Terminal started. Thanks for using Code for IBM i
-bash-5.2$ touch codeforiccsidtest && attr codeforiccsidtest CCSID && rm codeforiccsidtest
819
-bash-5.2$

**Comment by sebjulliand** [comment]
Perfect! Thank you @edmundreinhardt !

**Comment by sebjulliand** [comment]
@edmundreinhardt PR #2015 is in 😉

**Comment by edmundreinhardt** [comment]
Tested PR https://github.com/codefori/vscode-ibmi/pull/2015 and it solves this problem.
