### ISSUE TITLE
Cannot use "Save As..." to create new member or stream file

### ISSUE THREAD

**Issue by jkyeung** [codefori/vscode-ibmi#2004]
If you attempt to use "Save As..." to make a renamed copy of the member or stream file that is already open, VS Code will tell you that the target already exists, even though it doesn't, and ask you to confirm the "overwrite". If you confirm, it gives you the error "Failed to save {name of the _existing_ file}: No such file".

The only way I know to make it work is to create the target using some other means, and _then_ do the overwrite.
<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.9.0|
|Visual Studio Code version|1.88.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Debug (ibmidebug): 1.0.0
JSON Language Features (json-language-features): 1.0.0
Jupyter (jupyter): 2024.3.1
Jupyter Notebook Renderers (jupyter-renderers): 1.0.17
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
Pylance (vscode-pylance): 2024.4.1
Python (python): 2024.4.1
Python Debugger (debugpy): 2024.4.0
Python Indent (vsc-python-indent): 1.18.0
RPGLE (vscode-rpgle): 0.26.5
Rainbow CSV (rainbow-csv): 3.11.0
Rewrap (rewrap): 1.16.3
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|9|
|CCSID|37|
|Default CCSID|37|
|SQL|Disabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|QZDFMDB2.PGM|startDebugService.sh|
|git|iconv||||
|grep|setccsid||||
|ls|tar||||
|md5sum|||||
|sort|||||
|stat|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=*CRTDFT
CURLIB=*CRTDFT
HOME=/home/JYEUNG
HOST=SYSIDEV.ALLIEDBEVERAGE.COM
LIBLS=ABGTSTLIB JYEUNG CWLIB FANDA QS36F ABGDTALIB ABGPGMLIB QGPL QTEMP
LOGIN=jyeung
LOGNAME=jyeung
MAIL=/var/spool/mail/jyeung
OLDPWD=/home/JYEUNG
PASE_USRGRP_LIMITED=N
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/JYEUNG
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=10.12.16.41 57671 22
SSH_CONNECTION=10.12.16.41 57671 10.30.11.100 22
TZ=<EST>5<EDT>,M3.2.0,M11.1.0
USER=jyeung
USERNAME=jyeung
WORKDIR=/home/JYEUNG
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF2111:  Library ILEDITOR already exists.",
    "cwd": "/home/JYEUNG"
  },
  {
    "command": "ls -p /QIBM/UserData/IBMiDebugService/certs/debug_service.pfx",
    "code": 2,
    "stderr": "ls: cannot access '/QIBM/UserData/IBMiDebugService/certs/debug_service.pfx': No such file or directory",
    "cwd": "/home/JYEUNG"
  },
  {
    "command": "ls -p /QIBM/UserData/IBMiDebugService/certs/debug_service.pfx",
    "code": 2,
    "stderr": "ls: cannot access '/QIBM/UserData/IBMiDebugService/certs/debug_service.pfx': No such file or directory",
    "cwd": "/home/JYEUNG"
  }
]
```
</details>

**Comment by JonFP** [comment]
I was just about to write up this same problem. So it is not just you.

**Comment by worksofliam** [comment]
I don't believe there is an easy way for us to make save as work for streamfiles or members. I tried many months ago with much failure due to some API limitations. I will take a look again.

**Comment by JonFP** [comment]
If it proves impossible to implement, then at least it shouldn't even show the dialog. That is what is really confusing about the current situation.


Jon Paris

***@***.***
