### ISSUE TITLE
German special characters wrong format

### ISSUE THREAD

**Issue by MiaHub** [codefori/vscode-ibmi#2016]
My system ccsid: dspsysval qccsid = 65535

My Job ccsid = 1141:
Sprachen-ID . . . . . . . . . . . . . . . . . . . :   DEU    
Landes- oder Regions-ID . . . . . . . . . . . . . :   DE     
ID des codierten Zeichensatzes (CCSID)  . . . . . :   1141   
Standard-ID des codierten Zeichensatzes . . . . . :   1141   

When i check files: wrkf some_file: 273
ID des codierten Zeichensatzes  . . . . . . : CCSID        273     

I tried to change the Source file CCSID in the settings to 1141 and 273 and 65535 and *FILE but none works.
How can i solve the issue ? 

The characters that cannot be displayed are ä ö ü.

**Comment by SJLennon** [comment]
Does this info from the documentation help?
https://codefori.github.io/docs/tips/ccsid/

**Comment by MiaHub** [comment]
I set everything as suggested and now i works. 
But when i change everything back to how it was before it still works. 
Even after reconnecting and restarting the ssh daemon. 
Not sure why but i will keep the changes i guess, when we will upgrade to 7.4 it will be like this anyway i guess.

Thank you.
