### ISSUE TITLE
IBMi Object browser- Getting Token EPOCH was not valid error.

### ISSUE THREAD

**Issue by sali5678** [codefori/vscode-ibmi#2017]
I am able to connect to IBMi in VS Code
I am able to create a filter for my library in Object Browser
When I expand on the library I can see all my Source Physical Files
When I expand on any of the source physical files, it does not retrieve any of the members.  On the bottom right I get an error notification with the following error:

Token EPOCH was not valid. Valid tokens: DAY HOUR YEAR MONTH MINUTE SECOND. (42601)

Any help would be appreciated.

**Comment by sebjulliand** [comment]
Hi @sali5678 ,
check out this discussion: https://github.com/orgs/codefori/discussions/1885
`EPOCH` is a keyword that was added back in 7.2, it seems. What's your IBM i OS version?

**Comment by sebjulliand** [comment]
> Thanks @sebjulliand. Its 7.1. That might just be the problem. I will research the discussion link that you posted.

It sure is as Code for i doesn't support IBM i OS < 7.3.

**Comment by alanseiden** [comment]
@sebjulliand Would you say the minimum requirement is Technology Refresh 5 (TR5) on IBM i 7.3? It seems TR5 added enhancements to the `EXTRACT` scalar function. I assume `EPOCH` was part of TR5. Do you think I'm correct? (I am advising a 7.3 client and next step would be to ask about their TR level.)

**Comment by sebjulliand** [comment]
@alanseiden yes, your assumption is correct. There's a mention of `EXTRACT()` being enhanced to support more values on the 7.3 TR5 changelog: https://www.ibm.com/support/pages/node/1164652
This is probably where the support for `epoch` was added. 👍🏻

**Comment by chrjorgensen** [comment]
@alanseiden I think you're right about EPOCH arriving in TR5 - back in 2018...!

I hope you will advice the client to upgrade to a supported version of IBM i 🙏 - it hurts my IBM i admin heart to see so many outdated versions of IBM i still out there... 😢 

IBM i needs just as much TLC as the Windoze and Linux servers - nobody would ever stop updating these servers, it simply doesn't make sense. Keeping the server software updated minimizes security issues and provides more and modern functionality - this is a no-brainer in my mind.

And finally, the older the version of IBM i, the harder it is to use modern tools like Code for IBM i and other OSS...

Thanks for working so hard for the IBM i community! 👏
