### ISSUE TITLE
Check license key for feature 5101 of product 5770WDS is valid after connection is established

### ISSUE THREAD

**Issue by william-xiang** [codefori/vscode-ibmi#2018]
If license key for feature 5101 of product 5770WDS is expired, compile/build command will show the error below.

```
 *  Executing task: IBM i: Compile with CRTBNDRPG 🔨 

Running Action: Compile with CRTBNDRPG 🔨 (11:06:04 AM)
Current library: TESTLIB
Library list: QGPL QTEMP
Working directory: /home/qsecofr/builds/ibmi-company_system
Commands:
                CRTBNDRPG PGM(TESTLIB/mypgm) SRCSTMF('qrpglesrc/mypgm.pgm.rpgle') OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT) TGTCCSID(*JOB)

CPF9E78:  The license key for product 5770WDS, license term V7R5M0, feature 5101 is no longer valid.
RNS9310:  Compilation failed. Program MYPGM not created in library TESTLIB.
RNS9310:  Compilation failed. Program MYPGM not created in library TESTLIB.
```

Give the users a notification of the expired license key when the connection is created.

**Comment by william-xiang** [comment]
@SJLennon You are right, it's part of the product 5770WDS for RDS, and feature 5101 is `ILE COMPILERS: RPG, COBOL, C/C++ `. 

Not sure if there is a command to show the license key info of a product.

**Comment by sebjulliand** [comment]
@william-xiang sinec the error logged by the action is quite clear, why should Code for i check for this feature validity?
Is there an actual use case or a third-party tool that would require this to be checked? (in which case this should be implemented in this third-party tool/extension).
Besides, if there is a command/SAL service that can check this, it may require special authorities that common users may not have.

**Comment by william-xiang** [comment]
@sebjulliand Thanks for the advice. I will close this issue.
