### ISSUE TITLE
Create a page on setting up bash

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-ibmi#2021]
Under Tips, we should create a page solely for the sake of setting bash as the default shell

Under this folder: https://github.com/codefori/docs/tree/main/src/content/docs/tips

* Mention that if you connect and reload, Code for IBM i will ensure bash is the default
* Mention the other methods: SQL function, `chsh`, etc

Link to this new page from the Debugger docs, as bash is required for the debugger to be configured

**Comment by SJLennon** [comment]
Would including a [SETTING_BASH link](https://ibmi-oss-docs.readthedocs.io/en/latest/troubleshooting/SETTING_BASH.html) which also links to [SETTING_PATH](https://ibmi-oss-docs.readthedocs.io/en/latest/troubleshooting/SETTING_PATH.html) be sufficient,  or would you want to split out some of the steps included in these links?

**Comment by worksofliam** [comment]
@SJLennon I believe that would be sufficient. I'd rather that than have us keep another page on it.

**Comment by SJLennon** [comment]
Let me see what  I can come up, but I'm new to  Astro, so probably next week.

**Comment by SJLennon** [comment]
Learning Astro.  At first blush, it seems more complicated, though the results are certainly prettier.

We have .MDX files.  But VS Code seems to have no association for .MSX and thinks it is a text file. I set it to Markdown to get some highlighting. Is there any way to get better color coding?

CardGrids are nice, but I find the source is hard to read with the current style of usage. With all the  blank lines I had trouble figuring out where cards began and ended..

Current approach:
```
<CardGrid>

<Card>

Click the IBM i icon and then on 'Connect to an IBM i'.

</Card><Card>

![](../../assets/connect_02.png)

</Card></CardGrid>

---
```
I think I'd prefer something like this:
```
### Logout (Disconnect)
<CardGrid>
<Card>
To close a connection and logout out, press <kbd>F1</kbd> and search for `IBM i: Disconnect`

 Or use <kbd>Ctrl(Cmd)</kbd> + <kbd>Alt</kbd > +<kbd>D</kbd>
</Card>
<Card>
![Search Disconnect](../../assets/connect_07.png)
</Card>
<Card>
Or click the `Disconnect from system` icon in the status bar... 
</Card>
<Card>
![Dicconnect icon](../../assets/connect_08.png)
</Card>
</CardGrid>
```
I guess I miss the color coding and lack of indentation. But I will work with whatever you all suggest. And I couldn't find any extension to pretty up the source.

Are there any other extensions to help with detecting errors early?  There are a couple of Astro extensions but they don't seem to work on .MDX files.

Snippets:
1) I notice an error flagged in docs\.vscode\snippets.code-snippets:
![image](https://github.com/codefori/vscode-ibmi/assets/67484051/9f9e7de4-5147-4fc0-b419-0d79fdaff43a)
 2) What the `---` snippet for and/or what does is do in Astro?

**Comment by SJLennon** [comment]
Can you clarify:  Is using the bash shell a hard requirement, or will the extension work with limited function without it? Just wondering it bash should also be listed in the "Requirements" on the first page.

**Comment by SJLennon** [comment]
@worksofliam 
Created codefori/doc pull request #31 for this.
