### ISSUE TITLE
CRTSQLRPGI  error

### ISSUE THREAD

**Issue by egriffitt** [codefori/vscode-ibmi#2022]
CRTSQLRPGI shows in the terminal as requested. The command string appears to be correct with the library, member, etc. The "Action Create SQL ILE RPG Program (CRTSQLRPGI) for &OPENLIB/&OPENMBR was not successful." message is displayed. The terminal shows "Fetching errors for &OPENLIB/&OPENMBR".
<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.9.2|
|Visual Studio Code version|1.88.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 10.4.11
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.10.1
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.17.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitHub Copilot (copilot): 1.184.0
GitHub Copilot Chat (copilot-chat): 0.14.1
IBM i Debug (ibmidebug): 1.0.0
JSON Language Features (json-language-features): 1.0.0
Jira and Bitbucket (Atlassian Labs) (atlascode): 3.0.10
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.26.6
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
YAML (vscode-yaml): 1.14.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|n/a|
|Tech Refresh|n/a|
|CCSID Origin|system|
|Runtime CCSID|37|
|Default CCSID|37|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|ILEDITOR.GETMBRINFO|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|||||
|grep|setccsid|||||
|ls|tar|||||
|md5sum||||||
|sort||||||
|stat||||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=QGPL
CURLIB=QGPL
HOME=/home/KCGRIFFE
HOST=devlinc
LIBLS=HAWKEYE DBU11 QMQM MMAIL AVPTAX ALLAES100 AVPZIP TAATOOL ASTDTA ASTOBJ ASTPTFOBJ ASTPRLOBJ ASTOSOBJ ASST.TEST VAR35A VARMOD35A VAR35F LINC.MAST LINC.TEST LINC.ELG QGPL QTEMP

PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/KCGRIFFE
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=10.8.36.90 49272 22
SSH_CONNECTION=10.8.36.90 49272 10.97.144.27 22
TZ=<CST>6<CDT>,M3.2.0,M11.1.0
USER=kcgriffe
USERNAME=kcgriffe
WORKDIR=/home/KCGRIFFE
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "ls -p /QIBM/UserData/IBMiDebugService/certs/debug_service.pfx",
    "code": 2,
    "stderr": "ls: cannot access '/QIBM/UserData/IBMiDebugService/certs/debug_service.pfx': No such file or directory",
    "cwd": "/home/KCGRIFFE"
  },
  {
    "command": "ls -p /QIBM/UserData/IBMiDebugService/certs/debug_service.pfx",
    "code": 2,
    "stderr": "ls: cannot access '/QIBM/UserData/IBMiDebugService/certs/debug_service.pfx': No such file or directory",
    "cwd": "/home/KCGRIFFE"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPD0103:  Variable &OPENLIB not allowed for parameter FROMFILE.\nCPD0103:  Variable &OPENMBR not allowed for parameter FROMFILE.\nCPF0001:  Error found on CPYTOIMPF command.\nCPC2206:  Ownership of object QZSHSYSTEM in QTEMP type *USRSPC changed.",
    "cwd": "/home/KCGRIFFE"
  }
]
```
</details>

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the list doesn't appear.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by egriffitt** [comment]
The Output tab is empty, but these messages appear for the terminal
***@***.***


Thanks,
Erica Griffitt
Sr Software Engineer I

(913) 319-4717
***@***.******@***.***>

***@***.***

StaplesPromo.com<https://staplespromo.com/>

***@***.***<https://staplespromo.com/?utm_source=Signatures&utm_medium=Email_Banner&utm_campaign=Q3_2019>

This message (including any attachments) may contain confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message and are hereby notified that any disclosure, copying, or distribution of this message, or the taking of any action based on it, is strictly prohibited.

From: LJ ***@***.***>
Sent: Wednesday, May 1, 2024 6:24 PM
To: codefori/vscode-ibmi ***@***.***>
Cc: Griffitt, Erica ***@***.***>; Author ***@***.***>
Subject: [EXT]:Re: [codefori/vscode-ibmi] CRTSQLRPGI error (Issue #2022)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Please share the contents of your Code for IBM i output channel after the list doesn't appear.

[image]<https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png>

**Comment by worksofliam** [comment]
@egriffitt Attached do not get uploaded via email, so please reply in GitHub. The Output tab cannot be empty after you've connected to a system, since we write everything to it.
