### ISSUE TITLE
Issue with Object Filters

### ISSUE THREAD

**Issue by MarkBoyer** [codefori/vscode-ibmi#2024]
I don't know if this is an issue related to the new release that installed when I launched this morning or is it's an issue with our IBM i, I'm hoping someone here can shed some light.  When I expand a filter that I have used for quite a while, it just hangs.  The filter is defined to show objects with the name SRCFILE, our default, in one of my development libraries.  If I remove the object name filter and make it "*", it works fine.  If I open output panel, the statement it says is being executed is:
select 
  t.SYSTEM_TABLE_NAME as NAME,
  '*FILE'             as TYPE,
  'PF'                as ATTRIBUTE,
  t.TABLE_TEXT        as TEXT,
  1                   as IS_SOURCE,
  p.NUMBER_PARTITIONS as NB_MBR,
  t.ROW_LENGTH        as SOURCE_LENGTH,
  c.CCSID             as CCSID
from QSYS2.SYSTABLES as t
     join QSYS2.SYSTABLESTAT as p on ( t.SYSTEM_TABLE_SCHEMA, t.SYSTEM_TABLE_NAME ) = ( p.SYSTEM_TABLE_SCHEMA, p.SYSTEM_TABLE_NAME )
     join QSYS2.SYSCOLUMNS as c on ( t.SYSTEM_TABLE_SCHEMA, t.SYSTEM_TABLE_NAME, 3 ) = ( c.SYSTEM_TABLE_SCHEMA, c.SYSTEM_TABLE_NAME, c.ORDINAL_POSITION )
where t.table_schema = 'RM12P446B' and t.file_type = 'S' and t.SYSTEM_TABLE_NAME  =  'SRCFILE';

If I copy and paste that into either ACS Run SQL it seems to hang as well.  If I copy it into STRSQL on the box, it executes, however the counts at the bottom outgrow my patience, hundreds of thousands of records selected and processed so I abort it.  It's as if it's being optimized to ignore the table_schema.  Removing the system_table_name from the where clause and the return is almost immediate.

So I seem to think it's something going on with our box, but we have not installed any new PTFs since I used the without problem.  I at least wanted to share this in case anyone else experiences it, but I'd also appreciate any thoughts anyone might have.

**Comment by worksofliam** [comment]
@MarkBoyer might I recommend switching back to 2.9.0 and seeing if the issue persists? Also compare the statements used.

**Comment by hall8000** [comment]
It´s a bug, the same thing happened to me and i had to go back to version 2.9.0.

**Comment by sebjulliand** [comment]
> I don't know if this is an issue related to the new release that installed when I launched this morning or is it's an issue with our IBM i, I'm hoping someone here can shed some light. When I expand a filter that I have used for quite a while, it just hangs. The filter is defined to show objects with the name SRCFILE, our default, in one of my development libraries. If I remove the object name filter and make it "*", it works fine. If I open output panel, the statement it says is being executed is: select t.SYSTEM_TABLE_NAME as NAME, '*FILE' as TYPE, 'PF' as ATTRIBUTE, t.TABLE_TEXT as TEXT, 1 as IS_SOURCE, p.NUMBER_PARTITIONS as NB_MBR, t.ROW_LENGTH as SOURCE_LENGTH, c.CCSID as CCSID from QSYS2.SYSTABLES as t join QSYS2.SYSTABLESTAT as p on ( t.SYSTEM_TABLE_SCHEMA, t.SYSTEM_TABLE_NAME ) = ( p.SYSTEM_TABLE_SCHEMA, p.SYSTEM_TABLE_NAME ) join QSYS2.SYSCOLUMNS as c on ( t.SYSTEM_TABLE_SCHEMA, t.SYSTEM_TABLE_NAME, 3 ) = ( c.SYSTEM_TABLE_SCHEMA, c.SYSTEM_TABLE_NAME, c.ORDINAL_POSITION ) where t.table_schema = 'RM12P446B' and t.file_type = 'S' and t.SYSTEM_TABLE_NAME = 'SRCFILE';
> 
> If I copy and paste that into either ACS Run SQL it seems to hang as well. If I copy it into STRSQL on the box, it executes, however the counts at the bottom outgrow my patience, hundreds of thousands of records selected and processed so I abort it. It's as if it's being optimized to ignore the table_schema. Removing the system_table_name from the where clause and the return is almost immediate.
> 
> So I seem to think it's something going on with our box, but we have not installed any new PTFs since I used the without problem. I at least wanted to share this in case anyone else experiences it, but I'd also appreciate any thoughts anyone might have.

@MarkBoyer what if you keep the where clause as it is but remove the two joins and the `NUMBER_PARTITIONS` and `CCSID` fields from the select? How does it perform?

**Comment by MarkBoyer** [comment]
@sebjulliand you've got it!  If I take the two columns out of the select and remove the two joins, it returns immediately.

**Comment by sebjulliand** [comment]
> @sebjulliand you've got it! If I take the two columns out of the select and remove the two joins, it returns immediately.

Excellent, thanks for confirming that @MarkBoyer ! We are working on a fix now.

**Comment by worksofliam** [comment]
Fix is being released in 2.10.1, coming out right now!
