### ISSUE TITLE
Search in Object Browser

### ISSUE THREAD

**Issue by ttognazzini** [codefori/vscode-ibmi#2027]
**Describe the bug**
After todays update to VS Code I can no longer search in the object browser.  I used to click inside the object browser so it is selected, then press CTRL + f  to open a search box. It opened at the top of the object browser.  The search box allowed me to filter a long lists of source members quickly. I use it extensively when working with groups of members. 

Now it opens the search box in open source member tab instead.

This started happening on 5/2/2024. My current VS Code version is 1.89.0. My Code for IBM i version is 2.10.0 I tried rolling back the code for I version and it did not help.

I reverted to VS Code version 1.88.1 and it started working again, but that is not a long term solution.

**To Reproduce**
Expand the Object Browser and click somewhere inside it. It should show as selected by having a blue outline. Press CTRL + f. The find box opens in whatever tabs is open in the main work area, not in the object browser.

**Expected behavior**
It should open a search box in the Object Browser section. This search box used to have options for filter and fuzzy search.

**Screenshots**
![image](https://github.com/codefori/vscode-ibmi/assets/100705536/892c7832-7dab-4ac5-b2ec-f2c31264a39b)

**Environment (please complete the following information):**
 - Extension version 2.10.0
 - IBM i OS version 7.4

**Comment by worksofliam** [comment]
Hi @ttognazzini 

Sadly, this is a change as part of VS Code itself, and not something we have control over.

Here is the part of the release notes where they address this: https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding
