### ISSUE TITLE
Can't change current library from old library to new

### ISSUE THREAD

**Issue by kraudy** [codefori/vscode-ibmi#2031]
Hi, recently i changed my library on the ibm i server, so now i don't have access to that old library, lets call it LIBOLD. The new library is LIBNEW. 

Here is my problem. I can't seem to find a way to remove LIBOLD form the vscode for i lib list and also can't set LIBNEW as the new current lib. Which means, everytime i try to compile something, it tries to use LIBOLD, which i have no access anymore. 

I would aprecciate any advice. Thanks

This is LIBOLD
![image](https://github.com/codefori/vscode-ibmi/assets/19917977/7f60b81d-cd8f-4bc4-bb1c-276a9e6f49bd)

This is LIBNEW
![image](https://github.com/codefori/vscode-ibmi/assets/19917977/1fd7d919-10e3-4b58-aeb4-2e6fedba094c)

This is the error when trying to compile
![image](https://github.com/codefori/vscode-ibmi/assets/19917977/c62b589e-d794-44fb-aa8b-69aa7e8c1913)

It looks like it is in limbo
![image](https://github.com/codefori/vscode-ibmi/assets/19917977/5f4a2437-6440-4fa0-889d-15401461d810)

**Comment by SJLennon** [comment]
This doesn't work when you right click on a library?


![image](https://github.com/codefori/vscode-ibmi/assets/67484051/65f55ee9-61bc-4e9a-9457-0dd54e6ebc7f)

**Comment by kraudy** [comment]
> This doesn't work when you right click on a library?
> 
> ![image](https://private-user-images.githubusercontent.com/67484051/328051728-65f55ee9-61bc-4e9a-9457-0dd54e6ebc7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NDkyMzksIm5iZiI6MTcxNDk0ODkzOSwicGF0aCI6Ii82NzQ4NDA1MS8zMjgwNTE3MjgtNjVmNTVlZTktNjFiYy00ZTlhLTk0NTctMGRkNTRlNmViYzdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDIyNDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNGE3NTgxZDg5MDZjMjZhY2E0NDYxY2YzOWNiZjI3Y2I4NDVlZjg5MzM2MjcwZGQ1MDY4ODQ2MmIyMmE5ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DVGWPfUVc3pYYLGcNjmvXLRfTgCNY-73SfLNky_I_ws)

I can remove the new library but not the old one (which is set a current library)

**Comment by SJLennon** [comment]
You may have discovered something the developers didn't think of, so it may be a bug.

You did try right clicking and doing this?
![image](https://github.com/codefori/vscode-ibmi/assets/67484051/d2bf492a-c973-485e-a008-ac87b39d6a0c)

Does doing `CHGCURLIB `on the green screen and then reconnecting make any difference?

If you are really stuck, you could:

- Create a new connection.

- Or if you are comfortable with it, you could manually edit setting.json: But be careful...

![image](https://github.com/codefori/vscode-ibmi/assets/67484051/f2178ed9-be4e-47a4-9c5b-3266405908b6)

**Comment by kraudy** [comment]
Right click + change current library gives this error
![image](https://github.com/codefori/vscode-ibmi/assets/19917977/90488e01-7f37-411a-b4db-f0e1560480a0)

Changing the curlib on the green screen does nothing

I don't wanna try editing the settings right now cuz i have other connections and i don't know if that is gonna mess something else up and give me more headache

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the error appears.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by sebjulliand** [comment]
Hi @kraudy,
this is indeed a bug. If your settings' current library doesn't exist anymore, then it cannot be removed.
I'll work on a fix, but in the meantime, you should follow @SJLennon advice and replace your connection's `currentLibrary` by something else (like `QPGL`). This will get you going while the fix is being worked on and you have no risk of breaking anything.

Alternatively, you can use the `Copy...` action to duplicate the faulty connection and make a copy of everything but the library list.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/ccf1b63c-66ff-43aa-acc4-a7b4a5ca0a18)

**Comment by kraudy** [comment]
Here is the output @worksofliam 
![image](https://github.com/codefori/vscode-ibmi/assets/19917977/7ec9aa52-deab-48f8-862c-798354dc2315)

**Comment by sebjulliand** [comment]
@kraudy this problem has been fixed in v2.10.1 that was released today.
After you've updated the extension, you'll be able to change you current library.

**Comment by kraudy** [comment]
Thanks @sebjulliand
