### ISSUE TITLE
Runtime CCSID detected as -2 and is invalid. Please change the CCSID in your user profile. Using fallback methods to access the IBM i file systems.

### ISSUE THREAD

**Issue by gwendew** [codefori/vscode-ibmi#2034]
Hi, everytime I try to connect to an IBMi, I get the message : Runtime CCSID detected as -2 and is invalid. Please change the CCSID in your user profile. Using fallback methods to access the IBM i file systems.

I checked my user profile settings on IBM i and it is set to *SYSVAL. I tried to change it to 297 for testing purpose but I still get the same message.

My environment : 
 - Extension version :  Code for IBM i 2.10.0
 - IBM i OS version : v7r3

Can you please help me ? Thanks in advance.

Note : it wasn't happening 3 or 4 months ago ( I didn't use this extension for a couple of months)

**Comment by gwendew** [comment]
I downgraded the extension to 2.4.0 and it is now working (I don't have the message anymore). Maybe it could help

**Comment by worksofliam** [comment]
@gwendew we changed some of the messaging around, but really no functionality should change. 

Can you confirm what your:

* system QCCSID is
* what your user profile CCSID is

**Comment by gwendew** [comment]
Hi, 

Thank you for taking time to respond to me: 

The system CCSID is : 

Valeur système . . . . :   QCCSID                                    
CCSID  . . . . . . . . :   65535    

My CCSID is set to *SYSVAL so it is also 65535

**Comment by SJLennon** [comment]
@gwendew Have a look at this section of the documentation about CCSID and how to set it for your user id::
https://codefori.github.io/docs/tips/ccsid/

**Comment by gwendew** [comment]
Sorry but I don't understand why this solve my issue. As I said, It works perfectly fine with the extension v2.4.0 but It doesn't work anymore with the extension v2.10.0.

**Comment by worksofliam** [comment]
@gwendew You haven't said what doesn't work, only that you are seeing these messages (because your user profile CCSID is invalid)

**Comment by worksofliam** [comment]
@gwendew Did you check out the CCSID docs as suggested by @SJLennon?

https://codefori.github.io/docs/tips/ccsid/
