### ISSUE TITLE
Possible type in Walkthrough

### ISSUE THREAD

**Issue by rogersonra** [codefori/vscode-ibmi#2054]
I just wanted to point out that there may be a typo in the latest Local Development with ILE Walkthrough.
I think the word **directory** should have been **command**.

![image](https://github.com/codefori/vscode-ibmi/assets/32421796/001d07e1-afd2-48aa-8896-d1bd7153e888)

**Comment by worksofliam** [comment]
Good spot!

Can be fixed here: https://github.com/codefori/vscode-ibmi-walkthroughs/blob/main/content/code-ibmi-local/actions-create.md

**Comment by rogersonra** [comment]
@SJLennon, I believe you do a lot of the documentation.  As I've no experience with contributing/fixing do you think we could arrange a call so you can show me how to fix this?
If you don't have time or I have the wrong person please forgive me and maybe suggest someone who could walk me through how to fix this.

Thanks,

Rob

**Comment by SJLennon** [comment]
@rogersonra 
This doesn't look difficult.  I can do it.  
But if you want to learn to do it your self that will take a bit longer.

**Comment by rogersonra** [comment]
@SJLennon 
If you have time I'd love to see how you make the change.  Let me know if you have time to show me the ropes.
Thanks,
Rob

**Comment by SJLennon** [comment]
@rogersonra 

First, see the readme for [walkthroughs](https://github.com/codefori/vscode-ibmi-walkthroughs?tab=readme-ov-file#vscode-ibmi-walkthroughs).  Page down to the "Getting started is simple" section, and that gives you a decent start.

This change is very simple and we can make it directly on GitHub, following the above steps. (It's running VS Code in your browser--looks very similar to VS Code on your desktop.) When finished with the change it has to go from your fork back to the main project.

**_Commit the changes to the forked project._**

![image](https://github.com/codefori/vscode-ibmi/assets/67484051/53e63de5-50be-42a8-b918-1f9ac53c72c3)

**_Create a new pull request_**.

![image](https://github.com/codefori/vscode-ibmi/assets/67484051/fb9f9282-b776-4790-8a0f-7bfa87955854)

**_Complete the pull request._**

![image](https://github.com/codefori/vscode-ibmi/assets/67484051/8b60cb97-9e47-49be-b2c8-4455139b1b03)

**_And done!_**

**_You can now see the pull request on the main project:_** 

![image](https://github.com/codefori/vscode-ibmi/assets/67484051/8bf04e56-e52c-4033-b930-51891cb69dfb)



If you were making more extensive changes you need to know a bit about [GitHub markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax). 

If I was making extensive changes I would probably clone my fork to my PC and make the changes in VS Code. You need git installed on your PC, of course.
