### ISSUE TITLE
In 2.10 version, object browser does not show members list if there is more than one member. 

### ISSUE THREAD

**Issue by f-p-r** [codefori/vscode-ibmi#2063]
Save us time! Click 'Report an Issue' from the Help and Support panel inside of VS Code after you have connected to a system.

**Describe the bug**
In 2.10.0 and 2.10.1 versions, object browser does not show members list if there is more than one member. Works ok in 2.9.* versions

**To Reproduce**
1. Go to 'object browser' 
2. Click on source file with more than 1 member 
4. See no members

**Expected behavior**
list of members should be shown. 

**Screenshots**
![image](https://github.com/codefori/vscode-ibmi/assets/65034299/30099811-5540-42c9-aee0-426e0dc81115)
qrpgsrc, qinclsrc, qsegincl have more than 1 members, but no member list shows when clicking on them. Qprtsrc and qsegprt have just 1 member, that show in the member list.

**Environment (please complete the following information):**
 - Extension version [2.10.* (current today)] 
 - IBM i OS version [V7R3M0]

**Additional context**

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the list doesn't appear.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

Please also share your QCCSID with us.
