### ISSUE TITLE
Runtime CCSID detected as -2 and is invalid. Please change the CCSID in your user profile. Using fallback methods to access the IBM i file systems.

### ISSUE THREAD

**Issue by bobelliott96** [codefori/vscode-ibmi#2065]
System CCSID is 37
User profile CCSID is *SYSVAL
system version is V7R4

**Describe the bug**
Once connected, get the above error message.  When adding a library that exists on the connect i5, the description shows as '*** NOT FOUND ***'  When creating a filter, no results show.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Extension version 2.10.1
 - IBM i OS version 7.4

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the error appears.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by bobelliott96** [comment]
.: echo "This should be the only text!"
{
    "code": 0,
    "signal": null,
    "stdout": "This should be the only text!",
    "stderr": ""
}

.: echo $HOME && cd && test -w $HOME
{
    "code": 0,
    "signal": null,
    "stdout": "/home/DPWRE",
    "stderr": ""
}

/home/DPWRE: /QOpenSys/usr/bin/qsh
liblist
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/DPWRE: /QOpenSys/usr/bin/qsh
system  "CRTLIB LIB(dpwre) TEXT('Code for i temporary objects. May be cleared.')"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/DPWRE: [ -d "/tmp" ]
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/DPWRE: echo $SHELL
{
    "code": 0,
    "signal": null,
    "stdout": "/QOpenSys/pkgs/bin/bash",
    "stderr": ""
}

/home/DPWRE: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
select CHARACTER_CODE_SET_ID from table( QSYS2.QSYUSRINFO( USERNAME => upper('dpwre') ) )
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/DPWRE: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
Call QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST) OUTMBR(*FIRST *ADD)');
Call QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/PPDEVD) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST) OUTMBR(*FIRST *ADD)');
select * from QTEMP.LIBLIST;
/home/DPWRE: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select job_name, local_port from qsys2.netstat_job_info where cast(local_port_name as VarChar(14) CCSID 37) = 'is-debug-ile' fetch first row only
/home/DPWRE: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select OS_VERSION concat '.' concat OS_RELEASE as VERSION from sysibmadm.env_sys_info
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/DPWRE: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
Call QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST) OUTMBR(*FIRST *ADD)');
Call QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/PPDEVD) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST) OUTMBR(*FIRST *ADD)');
select * from QTEMP.LIBLIST;
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/DPWRE: test -r /QIBM/ProdData/IBMiDebugService/package.json
/home/DPWRE: test -r /QIBM/ProdData/IBMiDebugService/package.json
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/DPWRE: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
Call QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST) OUTMBR(*FIRST *ADD)');
Call QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/PPDEVD) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST) OUTMBR(*FIRST *ADD)');
select * from QTEMP.LIBLIST;
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/DPWRE: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select job_name, local_port from qsys2.netstat_job_info where cast(local_port_name as VarChar(14) CCSID 37) = 'is-debug-ile' fetch first row only
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/DPWRE: test -f /QIBM/UserData/IBMiDebugService/certs/debug_service.pfx
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/DPWRE: test -f /QIBM/UserData/IBMiDebugService/certs/debug_service.crt
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/DPWRE: test -f /QIBM/UserData/IBMiDebugService/.code4i.debug
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/DPWRE: test -f /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

**Comment by sebjulliand** [comment]
@bobelliott96 could you share the content of the output after you try adding a library?
Thanks!

**Comment by bobelliott96** [comment]
.: echo "This should be the only text!"
{
    "code": 0,
    "signal": null,
    "stdout": "This should be the only text!",
    "stderr": ""
}

.: echo $HOME && cd && test -w $HOME
{
    "code": 0,
    "signal": null,
    "stdout": "/home/DPWRE",
    "stderr": ""
}

/home/DPWRE: /QOpenSys/usr/bin/qsh
liblist
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/DPWRE: /QOpenSys/usr/bin/qsh
system  "CRTLIB LIB(dpwre) TEXT('Code for i temporary objects. May be cleared.')"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/DPWRE: [ -d "/tmp" ]
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/DPWRE: echo $SHELL
{
    "code": 0,
    "signal": null,
    "stdout": "/QOpenSys/pkgs/bin/bash",
    "stderr": ""
}

/home/DPWRE: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
select CHARACTER_CODE_SET_ID from table( QSYS2.QSYUSRINFO( USERNAME => upper('dpwre') ) )
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/DPWRE: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
Call QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST) OUTMBR(*FIRST *ADD)');
Call QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/PPDEVD) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST) OUTMBR(*FIRST *ADD)');
select * from QTEMP.LIBLIST;
/home/DPWRE: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select job_name, local_port from qsys2.netstat_job_info where cast(local_port_name as VarChar(14) CCSID 37) = 'is-debug-ile' fetch first row only
/home/DPWRE: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select OS_VERSION concat '.' concat OS_RELEASE as VERSION from sysibmadm.env_sys_info
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/DPWRE: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
Call QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST) OUTMBR(*FIRST *ADD)');
Call QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/PPDEVD) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST) OUTMBR(*FIRST *ADD)');
select * from QTEMP.LIBLIST;
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/DPWRE: test -r /QIBM/ProdData/IBMiDebugService/package.json
/home/DPWRE: test -r /QIBM/ProdData/IBMiDebugService/package.json
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/DPWRE: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
Call QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST) OUTMBR(*FIRST *ADD)');
Call QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/PPDEVD) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST) OUTMBR(*FIRST *ADD)');
select * from QTEMP.LIBLIST;
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/DPWRE: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select job_name, local_port from qsys2.netstat_job_info where cast(local_port_name as VarChar(14) CCSID 37) = 'is-debug-ile' fetch first row only
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/DPWRE: test -f /QIBM/UserData/IBMiDebugService/certs/debug_service.pfx
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/DPWRE: test -f /QIBM/UserData/IBMiDebugService/certs/debug_service.crt
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/DPWRE: test -f /QIBM/UserData/IBMiDebugService/.code4i.debug
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/DPWRE: test -f /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/DPWRE: /QOpenSys/usr/bin/qsh
liblist -d ; liblist -a HTEUSRJT
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/DPWRE: /QOpenSys/usr/bin/qsh
liblist -d ; liblist -a PPDEVD; liblist -a HTEUSRJT
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/DPWRE: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select job_name, local_port from qsys2.netstat_job_info where cast(local_port_name as VarChar(14) CCSID 37) = 'is-debug-ile' fetch first row only
/home/DPWRE: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
Call QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST) OUTMBR(*FIRST *ADD)');
Call QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/PPDEVD) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST) OUTMBR(*FIRST *ADD)');
Call QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/HTEUSRJT) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST) OUTMBR(*FIRST *ADD)');
select * from QTEMP.LIBLIST;
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

**Comment by dcpgm** [comment]
Hello, I have the same issue.
I tried changing the user CCSID to 870, setting the PASE environment (PASE_DEFAULT_UTF8 to "N", PASE_LANG and QIBM_PASE_CCSID), setting the SSH daemon CCSID, but nothing works for me.
The connection seems fine, but the Filter in Object Browser does not show me any object (only IFS Browser shows me the directories and the objects inside).
The output is similar to bobelliott96.
Thanks for any idea.

- Extension version 2.10.1
- IBM i OS version 7.4

**Comment by sebjulliand** [comment]
Can you try to reload your server settings when connecting and see if it changes anything?
Right-click on your connection and select this:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/326486d7-9a0d-4867-bfca-002e9f6b3cd9)

**Comment by dcpgm** [comment]
Nothing has changed. But I was trying to change the server settings and to reconnect several times. And I always got the same message about the CCSID issue. Thanks

**Comment by dcpgm** [comment]
Solved: This helped me - [https://codefori.github.io/docs/tips/setup/#no-results-from-sql-execution](url)

**Comment by bobelliott96** [comment]
When I click the link, I get "no results matched your search"

![image](https://github.com/codefori/vscode-ibmi/assets/170426543/8a180261-776e-41e6-bb51-9453ae5a9a3d)

**Comment by bobelliott96** [comment]
That one works.  Now to get with my system admin to try it.
