### ISSUE TITLE
Unable to open source member

### ISSUE THREAD

**Issue by JoeCharlesMorgan** [codefori/vscode-ibmi#2066]
Type: <b>Bug</b>

Am utilizing the CTRL + ALT + O command to open RPG source members.  I can type in the path of my source member and it shows in the dropdown box, but nothing happens when i click on the source member.  This just started happening yesterday.  

I have an Object Browser filter and can select and open source members for a filtered library though.

Extension version: 2.10.1
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.64GB (20.06GB free)|
|Process Argv|--crash-reporter-id b952ff2f-83d7-4708-b9a1-5a0b6a2c7e3f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
bdiig495:31013172
pythoncenvptcf:31049071
a69g1124:31046351
pythonprt:31047983
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the member doesn't open.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by JoeCharlesMorgan** [comment]
There is nothing in the output channel.

![image](https://github.com/codefori/vscode-ibmi/assets/16965517/911683c7-5864-44ee-99cf-5bc2d822d459)

**Comment by worksofliam** [comment]
@JoeCharlesMorgan you specifically need to change the output channel to Code for IBM i.

**Comment by JoeCharlesMorgan** [comment]
Sorry, Here is the data you request.   I tried to open a source member over which I have an Object Browser.  So, the source member was successfully opened from the Object Browser, but not opened with CNTRL + ALT + O.

![image](https://github.com/codefori/vscode-ibmi/assets/16965517/8376d546-0b51-4447-8524-658e1d7b26be)

**Comment by worksofliam** [comment]
@JoeCharlesMorgan before connecting to your system, can you use the Connect and Reload Server Settings and then try again?

**Comment by JoeCharlesMorgan** [comment]
That worked and  many thanks!  Will remember this if ever occurs again.

On May 22, 2024, at 11:26 AM, LJ ***@***.***> wrote:

﻿

@JoeCharlesMorgan<https://github.com/JoeCharlesMorgan> before connecting to your system, can you use the Connect and Reload Server Settings and then try again?
