### ISSUE TITLE
Program name with $ cause issue

### ISSUE THREAD

**Issue by kmainville** [codefori/vscode-ibmi#2072]
The editor could not be opened due to an unexpected error : Failed downloading member. CPFA0A9. Object not found.. Object is /QSYS.LIB/MYLIB.LIB/QCLSRC.FILE/J/.MBR. CPFA097: Object not copied. Object is /QSYS.LIB/MYLIB.LIB/QCLSRC.FILE/J\.MBR

In reality the object / source exist but contain $. 
Exemple J$ACBD is the member & Object name.

Thank you
<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.10.1|
|Visual Studio Code version|1.88.0|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Db2 for IBM i (vscode-db2i): 1.0.0
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Debug (ibmidebug): 1.0.0
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|3|
|CCSID Origin|user|
|Runtime CCSID|37|
|Default CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/usr/bin|/QSYS.lib/ILEDITOR.lib||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|attr|GETNEWLIBL.PGM|ILEDITOR.GETMBRINFO|QZDFMDB2.PGM|startDebugService.sh|
|iconv|||||
|ls|||||
|setccsid|||||
|tar|||||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF2111:  Library ILEDITOR already exists.",
    "cwd": "/home/bdc0105"
  },
  {
    "command": "export BUILDLIB=\"DEVBDC0105\" && export CURLIB=\"DEVBDC0105\" && export USERNAME=\"bdc0105\" && export HOST=\"BDCDEV01\" && export HOME=\"/home/bdc0105\" && export WORKDIR=\"/home/bdc0105\" && export LIBLS=\"DEVABAPGMB PRDABAMNT DEVFSSDTAA PRDCORPGDA TSTCORPGDA DEVCORPGDA PRDABAPGMA QGPL SPLAMATIC SYPFOCPGM SYPFOCDEMO TAATOOL TSTSYSOBJ ROBOTLIB QTEMP DC@COMLIB \\$_ACBSJRNL DC@DTALIB DC@PGMLIB PRDABADTA PRDABAPGM DEVABADTAA DEVABAPGMA\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=DEVBDC0105: is not an identifier",
    "cwd": "/home/bdc0105"
  },
  {
    "command": "export BUILDLIB=\"DEVBDC0105\" && export CURLIB=\"DEVBDC0105\" && export USERNAME=\"bdc0105\" && export HOST=\"BDCDEV01\" && export HOME=\"/home/bdc0105\" && export WORKDIR=\"/home/bdc0105\" && export LIBLS=\"DEVABAPGMB PRDABAMNT DEVFSSDTAA PRDCORPGDA TSTCORPGDA DEVCORPGDA PRDABAPGMA QGPL SPLAMATIC SYPFOCPGM SYPFOCDEMO TAATOOL TSTSYSOBJ ROBOTLIB QTEMP DC@COMLIB \\$_ACBSJRNL DC@DTALIB DC@PGMLIB PRDABADTA PRDABAPGM DEVABADTAA DEVABAPGMA\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=DEVBDC0105: is not an identifier",
    "cwd": "/home/bdc0105"
  }
]
```
</details>

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the editor doesn't appear.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">
