### ISSUE TITLE
object filter not filtering when using library name and member filter name only

### ISSUE THREAD

**Issue by davidlstrawn** [codefori/vscode-ibmi#2073]
![image](https://github.com/codefori/vscode-ibmi/assets/170743095/4ce50e86-2d2e-4ffb-95ee-b436185ad3f7)

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.10.1|
|Visual Studio Code version|1.89.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
CL (vscode-clle): 1.1.6
COBOL (cobol): 10.4.11
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Db2 for IBM i (vscode-db2i): 1.0.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.17.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Debug (ibmidebug): 1.0.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.5
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.26.6
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|9|
|CCSID Origin|user|
|Runtime CCSID|37|
|Default CCSID|37|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/usr/bin|/QOpenSys/pkgs/bin|/QSYS.lib/ILEDITOR.lib||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|-|
|attr|bash|GETNEWLIBL.PGM|ILEDITOR.GETMBRINFO|QZDFMDB2.PGM|startDebugService.sh|
|iconv||||||
|ls||||||
|setccsid||||||
|tar||||||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPD0012:  Characters in qualifier beginning '*) OBJTYPE' not valid.\nCPF0001:  Error found on *N command.",
    "cwd": "/home/DSTRAWN"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPD0012:  Characters in qualifier beginning '*) OBJTYPE' not valid.\nCPF0001:  Error found on *N command.",
    "cwd": "/home/DSTRAWN"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"dstrawn\" && export HOST=\"ibmi-live\" && export HOME=\"/home/DSTRAWN\" && export WORKDIR=\"/home/DSTRAWN\" && export LIBLS=\"TAXLIBF TAXLIB COALIBF COALIB NFCCLIB NFCCLIBF PAYLIB PAYLIBF QTEMP GPL\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/DSTRAWN"
  }
]
```
</details>

**Comment by sebjulliand** [comment]
Hi @davidlstrawn ,
your screenshot shows filtering on `Members` and your object browsers it shows a list of objects.
If you want to filter object names, change the `Objects` filter.

**Comment by davidlstrawn** [comment]
gotcha, was hoping to be able to bypass the source physical file "layer" and go straight to the member...  as in a Source filter on a library...
