### ISSUE TITLE
No puedo cambiar el puerto SSH

### ISSUE THREAD

**Issue by eruizrod** [codefori/vscode-ibmi#2075]
👉🏻 Issue text goes here.

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.10.1|
|Visual Studio Code version|1.89.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 10.4.11
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Db2 for IBM i (vscode-db2i): 1.0.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.17.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM Streams (ibm-streams): 1.1.2
JSON Language Features (json-language-features): 1.0.0
Language Support for Java(TM) by Red Hat (java): 1.30.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

**_Not connected_** 🔌

**Comment by SJLennon** [comment]
@eruizrod 
Traducción cortesía de DuckDuckGo translate. Mi español es inexistente.
> I can't change the SSH port

Si esto no ayuda, es probable que se necesite información más específica sobre el problema.
![image](https://github.com/codefori/vscode-ibmi/assets/67484051/68e77064-84c8-4595-98b1-fe314b9b2784)
 
![image](https://github.com/codefori/vscode-ibmi/assets/67484051/e2aa4701-4e5d-48ab-95a6-daac77014137)

Conexión existente, haga clic con el botón derecho:
![image](https://github.com/codefori/vscode-ibmi/assets/67484051/55a30e8d-54f9-4213-a02c-a6e222a77b4d)

![image](https://github.com/codefori/vscode-ibmi/assets/67484051/f7f5aa28-55d2-4bc6-a55d-a9a79950bed9)

**Comment by worksofliam** [comment]
Necesitas mas informaciones para este issue.
