### ISSUE TITLE
Error "Invalid time value"

### ISSUE THREAD

**Issue by prsbrc** [codefori/vscode-ibmi#2081]
By open an filter the vs-code reports an error: "Invalid time value"
This error comes not to all filters but at the most.

![image](https://github.com/codefori/vscode-ibmi/assets/31685593/6fc65c26-3c0f-4c6f-bc0f-6cf6b82f75a3)

|Context|Version|
|-|-|
|Code for IBM i version|2.10.1|
|Visual Studio Code version|1.89.1|
|Operating System|win32_x64|
|IBMi|7.5|

<details>
<summary>Active extensions</summary>

```
AL Language extension for Microsoft Dynamics 365 Business Central (al): 13.0.1007491
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Db2 for IBM i (vscode-db2i): 1.0.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.18.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Debug (ibmidebug): 1.0.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
NAB AL Tools (nab-al-tools): 1.32.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Server Ready Action (debug-server-ready): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
vscode-icons (vscode-icons): 12.7.0
waldo's CRS AL Language Extension (crs-al-language-extension): 1.5.31
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|2|
|CCSID Origin|user|
|Runtime CCSID|1141|
|Default CCSID|1141|
|SQL|Enabled
|Source dates|Disabled

**Comment by refahbayril** [comment]
I had this on all filters. 
Then install "v2.10.3 (pre-release)". problem gone.

**Comment by allthom** [comment]
I have this one already going on :-(

**Comment by sebjulliand** [comment]
@allthom could you share your `Code for IBM i` output content right after the error happens? Thanks!
![code for i output](https://github.com/codefori/vscode-ibmi/assets/11096890/88bc7363-2402-419f-b173-309358b914b9)

**Comment by allthom** [comment]
@sebjulliand here we go. As for the op i was only trying to open a filter
.: echo "This should be the only text!"
{
    "code": 0,
    "signal": null,
    "stdout": "This should be the only text!",
    "stderr": ""
}

.: echo $HOME && cd && test -w $HOME
{
    "code": 0,
    "signal": null,
    "stdout": "/home/LUCAG",
    "stderr": ""
}

/home/LUCAG: /QOpenSys/usr/bin/qsh
liblist
{
    "code": 0,
    "signal": null,
    "stdout": "MAXSYS      SYS\nQSYS        SYS\nQSYS2       SYS\nQHLPSYS     SYS\nQUSRSYS     SYS\nQSHELL      PRD\nQGPL        USR\nQTEMP       USR\nJGPL        USR\nACGGAA      USR",
    "stderr": ""
}

/home/LUCAG: /QOpenSys/usr/bin/qsh
system  "CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')"
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "CPC9801:  Oggetto MXCMD2RUN di tipo *DTAQ creato nella libreria QTEMP.\nCPC9801:  Oggetto MXRSNDMG di tipo *DTAQ creato nella libreria QTEMP.\nCPF2111:  La libreria ILEDITOR esiste gi�."
}

/home/LUCAG: [ -d "/tmp" ]
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/LUCAG: echo $SHELL
{
    "code": 0,
    "signal": null,
    "stdout": "/QOpenSys/usr/bin/bsh",
    "stderr": ""
}

/home/LUCAG: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
Call QSYS2.QCMDEXC('CHGJOB CCSID(280)');
select job_name, local_port from qsys2.netstat_job_info where cast(local_port_name as VarChar(14) CCSID 37) = 'is-debug-ile' fetch first row only
/home/LUCAG: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
Call QSYS2.QCMDEXC('CHGJOB CCSID(280)');
select OS_VERSION concat '.' concat OS_RELEASE as VERSION from sysibmadm.env_sys_info
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.\nDB2>\n  ?>\n\nVERSION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \n---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n7.3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \n\n  1 RECORD(S) SELECTED.",
    "stderr": ""
}

/home/LUCAG: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
Call QSYS2.QCMDEXC('CHGJOB CCSID(280)');
select max(ptf_group_level) as HIGHEST_DB2_PTF_GROUP_LEVEL from qsys2.group_ptf_info where PTF_GROUP_DESCRIPTION like 'DB2 FOR IBM I%' and ptf_group_status = 'INSTALLED';
{
    "code": 1,
    "signal": null,
    "stdout": "DB2>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.\nDB2>\n  ?>\n\nJOB_NAME                     LOCAL_PORT \n---------------------------- -----------\n\n  0 RECORD(S) SELECTED.",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.\nDB2>\n\nHIGHEST_DB2_PTF_GROUP_LEVEL \n----------------------------\n                          29\n\n  1 RECORD(S) SELECTED.\n\nDB2>",
    "stderr": ""
}

/home/LUCAG: ls $HOME/.vscode/codeforiserver-1.4.9.jar
{
    "code": 0,
    "signal": null,
    "stdout": "/home/LUCAG/.vscode/codeforiserver-1.4.9.jar",
    "stderr": ""
}

/home/LUCAG: /QOpenSys/usr/bin/qsh
system  "CHKOBJ OBJ(QSYS/ACG_AIA) OBJTYPE(*LIB) AUT(*NONE)"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/LUCAG: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
Call QSYS2.QCMDEXC('CHGJOB CCSID(280)');
select 
  t.SYSTEM_TABLE_NAME as NAME,
  '*FILE'             as TYPE,
  'PF'                as ATTRIBUTE,
  t.TABLE_TEXT        as TEXT,
  1                   as IS_SOURCE,
  t.ROW_LENGTH        as SOURCE_LENGTH
from QSYS2.SYSTABLES as t
where t.table_schema = 'ACG_AIA' and t.file_type = 'S';
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.\nDB2>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n\nNAME       TYPE  ATTRIBUTE  TEXT                                               IS_SOURCE   SOURCE_LENGTH \n---------- ----- ---------- -------------------------------------------------- ----------- --------------\nQCLSRC     *FILE PF         Source CL                                                    1            128\nQCPYSRC    *FILE PF         membri /COPY                                                 1            112\nQDDLSRC    *FILE PF         Sorgenti SQL DDL                                             1            112\nQDDSDS     *FILE PF         DS PARM                                                      1            128\nQDDSDSPF   *FILE PF                                                                      1            112\nQDDSPF     *FILE PF                                                                      1            112\nQDDSPRTF   *FILE PF                                                                      1            112\nQRPGLESRC  *FILE PF         Sorgenti (SQL)RPGLE                                          1            128\nQSQLTAB    *FILE PF                                                                      1            132\nQSRCBCK    *FILE PF         back up di sorgenti prima di stravolgerli                    1            128\nQTXT       *FILE PF                                                                      1             92\nQUTISRC    *FILE PF         Sorgenti Utilit� RPG/CL/varie                                1             92\n\n 12 RECORD(S) SELECTED.\n\nDB2>",
    "stderr": ""
}

**Comment by sebjulliand** [comment]
Thank you! This part looks OK.
Now, after the error show up, can you open the developer tools and open the Console tab?
Then see if the error is there and copy the whole block here.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/1495110c-d6d7-4326-8c73-60a36a4e24e5)
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/c732f006-e651-49f2-a9fc-c16368e3dd5d)

Thanks!

**Comment by allthom** [comment]
@sebjulliand here we go again, yes the error is in the console, see the file
[vscode-app-1718093198637.log](https://github.com/user-attachments/files/15784423/vscode-app-1718093198637.log)

**Comment by allthom** [comment]
@sebjulliand TIA for your attention
Another strange behavior that I have been experiencing for some time is when I click on a source file inside a filter and the arrow moves downwards but the list of sources, which is also present in that source file, is not shown. Nothing comes down, the arrow remains oriented downwards and nothing more
![immagine](https://github.com/codefori/vscode-ibmi/assets/141107907/f7f5bf91-7b0e-4871-995b-99aee236631e)

Here's the log 
[vscode-app-1718094131435.log](https://github.com/user-attachments/files/15784639/vscode-app-1718094131435.log)

**Comment by sebjulliand** [comment]
Both issues might be related. @allthom can you double check if you're actually using the latest prerelease here?
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/c0745cfa-e604-4189-aeb7-e9e1e007972c)
The console logs show version `2.10.1`. It may be wort switching to the prerelease version and see if it helps.

**Comment by allthom** [comment]
@sebjulliand updating to latest prerelease seem to have fixed the problem. Thank you, very helpfull

**Comment by sebjulliand** [comment]
You're welcome @allthom, glad it works 😄
