### ISSUE TITLE
Date for source insertion/editing

### ISSUE THREAD

**Issue by jhowell1030** [codefori/vscode-ibmi#2091]
So, I'm a dev that primarily uses ACS green screen for editing. A feature I use often is searching after a certain date within the source to look at changes that may have been done. I noticed that when you edit/create source using VS Code, the date values for all of source get zeroed out. Is there a way to prevent this from happening?

**Comment by sebjulliand** [comment]
Hi @jhowell1030 , sure, have a look at source date support here: https://codefori.github.io/docs/developing/sourcedates
You'll want to look at this section in your connection settings.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/be76d764-d5a8-4ff9-99c9-6ef47934d113)

**Comment by jhowell1030** [comment]
> Hi @jhowell1030 , sure, have a look at source date support here: https://codefori.github.io/docs/developing/sourcedates You'll want to look at this section in your connection settings. ![image](https://private-user-images.githubusercontent.com/11096890/335702933-be76d764-d5a8-4ff9-99c9-6ef47934d113.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxODU2NjMsIm5iZiI6MTcxNzE4NTM2MywicGF0aCI6Ii8xMTA5Njg5MC8zMzU3MDI5MzMtYmU3NmQ3NjQtZDVhOC00ZmY5LTk5YzktNmVmNDc5MzRkMTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE5NTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMjhhYzdiZjkzYzU0MzJjMjBlZDk2MzNhOTNhZDhiMTkyMjNjOTMyZjVlMzBhODgwNWNlZDMzMTBmNTMxZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8tI9R1yzCrMdDRW3AtpQryIYQHOReVFWNnJJa_JpmI0)

Thank you!
