### ISSUE TITLE
Debug Server is running but VSCode says it is not

### ISSUE THREAD

**Issue by jwoehr** [codefori/vscode-ibmi#2092]
Trying to debug a COBOL program, starting the debugger reports Debug Server is not running but is indeed running.
![Screenshot from 2024-05-31 15-11-24](https://github.com/codefori/vscode-ibmi/assets/4604036/d28e474d-68ff-4724-a056-b2f73f44b7dc)

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.10.1|
|Visual Studio Code version|1.89.1|
|Operating System|linux_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 10.5.29
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
CodeLLDB (vscode-lldb): 1.10.0
Db2 for IBM i (vscode-db2i): 1.0.0
Dev Containers (remote-containers): 0.362.0
ESLint (vscode-eslint): 2.4.4
EditorConfig for VS Code (EditorConfig): 0.16.4
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.18.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitHub Pull Requests (vscode-pull-request-github): 0.88.1
IBM i Debug (ibmidebug): 1.0.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Live Share (vsliveshare): 1.0.5918
Merge Conflict (merge-conflict): 1.0.0
MongoDB for VS Code (mongodb-vscode): 1.6.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Path Intellisense (path-intellisense): 2.8.5
Prettier - Code formatter (prettier-vscode): 10.4.0
Server Ready Action (debug-server-ready): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
Vite (vite): 0.2.5
Vue - Official (volar): 2.0.10
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|3|
|CCSID Origin|user|
|Runtime CCSID|37|
|Default CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|ILEDITOR.GETMBRINFO|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|ILEDITOR.GETNEWLIBL|||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
ANT_HOME=/opt/apache-ant-1.10.1
BUILDLIB=JWOEHR
CC=gcc-10 -pthread
CURLIB=JWOEHR
CXX=g++-10 -pthread
HISTFILESIZE=50000
HISTSIZE=50000
HOME=/home/JWOEHR
HOST=**************
JAVA_HOME=/QOpenSys/pkgs/lib/jvm/openjdk-11
LC_ALL=EN_US.UTF-8
LIBLS=QTEMP QGPL
LOGIN=jwoehr
LOGNAME=jwoehr
MAIL=/var/spool/mail/jwoehr
NVM_CD_FLAGS=
NVM_DIR=/home/JWOEHR/.nvm
OBJECT_MODE=64
OLDPWD=/home/JWOEHR
PASE_USRGRP_LIMITED=N
PATH=/home/JWOEHR/bin:/home/JWOEHR/.local/bin:/QOpenSys/pkgs/lib/jvm/openjdk-11/bin:/QOpenSys/pkgs/bin:/QOpenSys/pkgs/sbin:/QOpenSys/usr/bin:/usr/local/bin:/QOpenSys/pkgs/lib/nodejs12/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin:/opt/apache-ant-1.10.1/bin
PS1=\u@\h:\w\$
PWD=/home/JWOEHR
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=******************
SSH_CONNECTION=****************
TERM=xterm
TZ=<EST>5<EDT>,M3.2.0,M11.1.0
UBLU_HOME=/opt/ublu
USER=jwoehr
USERNAME=jwoehr
WORKDIR=/home/JWOEHR
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF2111:  Library ILEDITOR already exists.",
    "cwd": "/home/JWOEHR"
  },
  {
    "command": "cd '/home/JWOEHR/work' && /QOpenSys/pkgs/bin/stat --dereference --printf=\"%A\t%h\t%U\t%G\t%s\t%Y\t%n\n\" * .*  ",
    "code": 1,
    "stderr": "/QOpenSys/pkgs/bin/stat: cannot stat '.*': A file or directory in the path name does not exist.",
    "cwd": "/home/JWOEHR"
  },
  {
    "command": "cd '/home/JWOEHR/work/cobol' && /QOpenSys/pkgs/bin/stat --dereference --printf=\"%A\t%h\t%U\t%G\t%s\t%Y\t%n\n\" * .*  ",
    "code": 1,
    "stderr": "/QOpenSys/pkgs/bin/stat: cannot stat '.*': A file or directory in the path name does not exist.",
    "cwd": "/home/JWOEHR"
  }
]
```
</details>

**Comment by sebjulliand** [comment]
Are both the Debug Server and Service shown as running in the `IBM i Debugger` view?
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/209267df-2299-41d2-8bbe-347554ab03da)

**Comment by jwoehr** [comment]
Yes, it shows in that view as running! How odd ...
![image](https://github.com/codefori/vscode-ibmi/assets/4604036/a542049b-4fc6-42e6-bd02-d6f36b839bd6)

**Comment by mkwan01** [comment]
We have two sets of debug service PTFs before. The older ones are:
v7r3 PTF SI80858, v7r4 PTF SI81031 & v7r5 PTF SI81035

And the newer ones are:
V7r3 PTF SI83249, v7r4 PTF SI83261 & V7r5 PTF SI83262

The even newer v2.0 PTFs will be out soon. Please let us know which PTF you have.

**Comment by mkwan01** [comment]
IBM i Debug v2.0.1 was just released. It contains a number of fixes in debugger startup. Please upgrade to the v2 client (a host PTF update is also required) and try the same scenario again.

**Comment by jwoehr** [comment]
Where is the PTF announced, please?

**Comment by mkwan01** [comment]
IBM i Debug v2 client is available here:
https://marketplace.visualstudio.com/items?itemName=IBM.ibmidebug&ssr=false#overview

The Overview page also describes the required host PTF update.
