### ISSUE TITLE
Login Settings Save doesn't appear to work

### ISSUE THREAD

**Issue by Gregory1701** [codefori/vscode-ibmi#2106]
When editing the login settings for a connection, in my case I had the Host or IP Address typed incorrectly when I first setup the connection. When I try to correct the setting, click save, then go back into the login settings, it still has the old setting.

**Comment by sebjulliand** [comment]
Hi @Gregory1701 !
This has been fixed by one or two PRs that have been pre-released. Try switching to the pre-release version and it should be Ok (or wait for the release, it's up to you 😄).
