### ISSUE TITLE
Debug Service Fails to Start

### ISSUE THREAD

**Issue by Nick1497** [codefori/vscode-ibmi#2110]
Type: <b>Bug</b>

Connect to IBM i system > Start the debug server > Attempt to start the debug service in which the issue occurs at this step. It is affecting my entire team who use this tool, we all receive the same error message as well. 

![Debug Issue](https://github.com/codefori/vscode-ibmi/assets/172528062/34b96fde-2a66-4b2b-8073-a00215b8d086)

Extension version: 2.10.1
VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 7530U with Radeon Graphics      (12 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.31GB (4.87GB free)|
|Process Argv|--crash-reporter-id f363ceb0-20c6-49c7-80ad-3a25bbb3f05d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by Nick1497** [comment]
Something to note is the debugging was working fine previously (within the last month or two). All PTFs and certs seem to meet the requirements. I tried previous versions of the extension and the same issue occurred.

**Comment by sebjulliand** [comment]
Hi @Nick1497 ,
try clearing the `/QIBM/UserData/IBMiDebugService/certs` directory on the IFS to remove the existing certificate.
Then refresh the `IBM i Debugger` view.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/fd8dee57-cb46-465e-9f9e-cce1e5bc7d9e)

The Debug Service item will bear a red cross and complain a certificate needs to be generated. Click on the icon next to it to generate a new certificate (https://codefori.github.io/docs/developing/debug/#generating-certificates).
Then try to start the Service. Hopefully at this point it will start.

**Comment by Alastyr** [comment]
Here's the problem troubleshooting https://www.ibm.com/support/pages/troubleshooting-unable-open-pkcs12-keystores-due-unrecoverablekeyexception
Yesterday I lost a lot of time to find it.
