### ISSUE TITLE
All the dates of my program has been changed 

### ISSUE THREAD

**Issue by Vvisscoo** [codefori/vscode-ibmi#2112]
I was writing some code for my project, when i saved my code, the system has changed every date of the program. For example, one line of code, which date was like 01/01/2024 is now valued as the current date. I've just saved the program, i've not done anything special. I have already turned on the setting "Enable sources Dates".

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.10.1|
|Visual Studio Code version|1.90.0|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
.NET Install Tool (vscode-dotnet-runtime): 2.0.6
ARCAD-Elias (arcad-elias): 2.0.1
COBOL (cobol): 10.6.10
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Db2 for IBM i (vscode-db2i): 1.0.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.18.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
Git Graph (git-graph): 1.30.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
Highlight Matching Tag (highlight-matching-tag): 0.11.0
IBM Db2 for z/OS Developer Extension (db2forzosdeveloperextension): 2.1.5
IBM i Debug (ibmidebug): 1.0.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
IBM i Project Explorer (vscode-ibmi-projectexplorer): 2.9.0
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
Prettier SQL VSCode (prettier-sql-vscode): 1.6.0
RPG End Code Blocks (rpg-end-code-blocks): 1.0.0
RPGLE (vscode-rpgle): 0.26.6
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|8|
|CCSID Origin|user|
|Runtime CCSID|65535|
|Default CCSID|37|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|ILEDITOR.GETMBRINFO|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|||||
|git|setccsid|||||
|grep||||||
|ls||||||
|md5sum||||||
|sort||||||
|stat||||||
|tar||||||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF3012:  File FILE_NAME in library *LIBL not found.\nCPC2206:  Ownership of object QZSHSYSTEM in QTEMP type *USRSPC changed.",
    "cwd": "IFS_PATH"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPD0048:  List of values not valid for parameter FILE.\nCPF0001:  Error found on DSPFFD command.\nCPC2206:  Ownership of object QZSHSYSTEM in QTEMP type *USRSPC changed.",
    "cwd": "/IFS_PATH"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"USERNAME\" && export HOST=\"HOST_NAME\" && export HOME=\"/IFS_PATH\" && export WORKDIR=\"/IFS_PATH\" && export LIBLS=\"LIB_LIST" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/IFS_PATH"
  }
]
```
</details>

**Comment by worksofliam** [comment]
@Vvisscoo Please provide steps for us to recreate your issue. And if possible, a video, with date gutter enabled, to show us the problem.

Thanks!

**Comment by Vvisscoo** [comment]
Hello,

i’m not able to recreate my issue because it doesn’t happen on a daily basis. It just happens sometime and i’m not able to understand why it happens. I have noticed that this happens sometime when i have internet issues.

Thank you

Victor


[22389711]
Victor Scolari
Junior Software Developer | Var Engineering S.r.l.

0039 3358412024
www.vargroup.it<http://www.vargroup.it/>

[80773C47][3901B4ED][1E170283][73D92289][5FD26E7F][7681FBE5]     

 ***@***.*** <https://www.bestworkplaces.it/aziende/var-group/>

Avviso sulla tutela delle informazioni riservate. Questo messaggio è stato spedito da Var Group S.p.A. o da una delle aziende del Gruppo. Esso, e gli eventuali allegati, potrebbero contenere informazioni di carattere estremamente riservato e confidenziale. Qualora non foste i destinatari designati, vogliate cortesemente informarci immediatamente con lo stesso mezzo ed eliminare il messaggio e i relativi eventuali allegati, senza trattenerne copia.



Da: LJ ***@***.***>
Inviato: lunedì 17 giugno 2024 13:39
A: codefori/vscode-ibmi ***@***.***>
Cc: Victor Scolari ***@***.***>; Mention ***@***.***>
Oggetto: Re: [codefori/vscode-ibmi] All the dates of my program has been changed (Issue #2112)


@Vvisscoo<https://github.com/Vvisscoo> Please provide steps for us to recreate your issue. And if possible, a video, with date gutter enabled, to show us the problem.

Thanks!
