### ISSUE TITLE
I can't get IBM i: Go to File to work. I've used it in the past but now I get the message "Source Member <<fully_qualified_memberName>> does not exist".

### ISSUE THREAD

**Issue by susangantner** [codefori/vscode-ibmi#2116]
I can't get IBM i: Go to File to work. I've used it in the past but now I get the message "Source Member ... does not exist".

I can see the member in my filter and I can open it from there. 

I've tried it using both F1 > IBM i: Go to File - which brings up a list of recently opened files. I've selected several of those members - all of whom do exist - and I get the same message. I've tried manually keying in the member info. And I've tried using the icon next to Object Browser in the side bar. All attempts return the same error. 

A colleague is having the same issue. 

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.10.1|
|Visual Studio Code version|1.90.0|
|Operating System|darwin_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 10.6.11
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Db2 for IBM i (vscode-db2i): 1.0.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.18.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Debug (ibmidebug): 1.0.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.26.6
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|9|
|CCSID Origin|user|
|Runtime CCSID|37|
|Default CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|ILEDITOR.GETMBRINFO|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|||||
|git|setccsid|||||
|grep|tar|||||
|ls||||||
|md5sum||||||
|sort||||||
|stat||||||
|tn5250||||||
</details

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

**Comment by susangantner** [comment]
I just confirmed that IBM i: Go to File works fine for IFS - it's just members that I can't open.

**Comment by SJLennon** [comment]
@susangantner 
I'm on Win 10 and I can't reproduce your error.  It works for me:
![image](https://github.com/codefori/vscode-ibmi/assets/67484051/3c1f6616-e42a-41b4-b197-703f4be6eaf9)
And it opens up AAA.C.

I'm on the latest VS Code:
Version: 1.90.1 (system setup)
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:01:24.262Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by chrjorgensen** [comment]
Hi @susangantner 

Could you try the pre-release version 2.10.7 of Code for IBM i to see, if your problem is fixed in that version? And do a `Connect and Reload Server Settings` when connecting?

We have had some issues with CCSID, which should be fixed by the prerelease version... 🙏

**Comment by susangantner** [comment]
Hi @chrjorgensen

**Comment by chrjorgensen** [comment]
@susangantner Glad you got your problem fixed! 😃 

The `Connect and Reload Server Settings` command does a full connection, retrieving every setting from the server as if this was the first connection to the server. This can be a long operation, depending on the server. Then it stores the server settings most likely to not be changed on your workstation and does not retrieve them from the server on subsequent connections - much faster.

The command was created to allow for renewal of server settings stored on the workstation, in case some server or user settings were changed on the server after initial connection. You can also disable this cache of server settings in the connection settings (not recommended):

![billede](https://github.com/codefori/vscode-ibmi/assets/13275072/f3940eba-9be0-4d82-ab38-62cd0eb14bd0)

Hope this gives a better understanding of this feature. 🙏
