### ISSUE TITLE
vs code debugger- possible conflict with PRODATA DBU RDI plug in

### ISSUE THREAD

**Issue by gmikoscws** [codefori/vscode-ibmi#2133]
Type: <b>Bug</b>

We are experiencing a conflict between RDI plug in for Prodata DBU and vs code debugger. In vs code, when I end service job & restart, vs code debugger works as expected but DBU plug in fails. When service job is ended and we use QSTRUP to restart server, DBU works but vs code debugger throws and error.  Here is part of the message:  

"EQAVS1007E ... on port 8005 could not be connected......."

The certificates are renewed. The service job is listening on 8005,8009 and 8205. Prodata uses port 8205. By chance, does service job need to be listening to 8001? Any suggestions are appreciated. 

Note, I did try posting this to the debugger extension but that did not allow me to proceed.  

Thank you.

 

Extension version: 2.11.0
VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (4.87GB free)|
|Process Argv|--crash-reporter-id 062be74b-2eba-44eb-9331-a587e8be87a0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31077528

```

</details>

**Comment by sebjulliand** [comment]
There are two ports opened by the Debug Service: 8001 and 8005. Both can be changed in the Debug Service configuration file that can be opened from the IBM i Debugger view.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/1a14a5b7-db55-4ec2-8bc8-c130801beb5f)

If Prodata only listens to port 8205, it shouldn't come into conflict with the Debug Service; but it's worth trying to change the Debug Service ports (e.g. use 9001 and 9005) and restart it.
Then reconnect to your system using `Connect and Reload` so the local debug configuration gets updated:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/ee803d7c-e642-4d55-ab9a-89dd8ebba658)

We'll see if this helps!

**Comment by gmikoscws** [comment]
Conflict resolved by changing port 8005 to 8006 in dbu server.xml. Thank you Seb for your help!

**Comment by sebjulliand** [comment]
You're welcome @gmikoscws !
