### ISSUE TITLE
Debug certificate setup error: Bash is installed on the IBM i, but it is not your default shell..."

### ISSUE THREAD

**Issue by cwbuck** [codefori/vscode-ibmi#2134]
I am trying to run the Setup Service Certificate for the new Debug release here:

![image](https://github.com/codefori/vscode-ibmi/assets/68613130/8f23d395-28a4-41e4-b695-f2fb4c29939d)

But I am encountering the following error: 

![image](https://github.com/codefori/vscode-ibmi/assets/68613130/d75d1941-1e33-417e-a4f8-02ce6e6ed3a7)

As best I can tell, my default shell for my personal user is set to Bash. 
I've even added the following to my user's .profile to make sure it was getting set:
```
SHELL=/QOpenSys/pkgs/bin/bash
```

Also, I've tried running this in SQL to set bash to default for all users, but it does not seem to make a difference:
```
CALL QSYS2/SET_PASE_SHELL_INFO('*DEFAULT', '/QOpenSys/pkgs/bin/bash')
```

**Comment by cwbuck** [comment]
Well, I think I've got bigger problems now...

I've done something now to block my connection to the server. Now I can't even connect 😬

![image](https://github.com/codefori/vscode-ibmi/assets/68613130/ddcee3c7-abae-4d79-b325-11021920fe65)

**Comment by sebjulliand** [comment]
Do you have anything in your `~/.bashrc` or `~/.profile` file that would echo anything?
Also, I'd advise you remove `SHELL=/QOpenSys/pkgs/bin/bash` from your `.profile`.
Run this in a shell to make bash your default shell for sure:
```bash
/QOpenSys/pkgs/bin/chsh -s /QOpenSys/pkgs/bin/bash
```

**Comment by cwbuck** [comment]
Ah yes, I do have some custom message echos in my `~/.bashrc`. Should I remove those? 
I've removed the `SHELL=/QOpenSys/pkgs/bin/bash` already.

**Comment by sebjulliand** [comment]
> Ah yes, I do have some custom message echos in my `~/.bashrc`. Should I remove those? I've removed the `SHELL=/QOpenSys/pkgs/bin/bash` already.

Yep, remove these echos and you should be fine!

**Comment by cwbuck** [comment]
That worked! Thank you so much for your help!

**Comment by sebjulliand** [comment]
> That worked! Thank you so much for your help!

Anytime 😊
