### ISSUE TITLE
VS_Code

### ISSUE THREAD

**Issue by jaaburtog** [codefori/vscode-ibmi#2140]
👉🏻 Issue text goes here.

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.11.0|
|Visual Studio Code version|1.87.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitHub Copilot (copilot): 1.207.0
GitHub Copilot Chat (copilot-chat): 0.13.1
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

**_Not connected_** 🔌

**Comment by SJLennon** [comment]
@jaaburtog You haven't proved much to go on, but ...
1) You have checked the "Requirements" in the [documentation ](https://codefori.github.io/docs/#requirements) and SSH is started on your IBM i?
2) Which OS level is the IBM i?
3) Can you get a SSH connection to the IBM i with a client, say PuTTY or similar?

**Comment by worksofliam** [comment]
Closing due to lack of info.

**Comment by SJLennon** [comment]
@worksofliam Did you really mean to close this? If seems brand new.

**Comment by worksofliam** [comment]
@SJLennon yes, I close issues that don't initially have the required information.
