### ISSUE TITLE
Saving a source member clears field SRCDAT of the source file.

### ISSUE THREAD

**Issue by HerbertPfeifer** [codefori/vscode-ibmi#2150]
Save us time! Click 'Report an Issue' from the Help and Support panel inside of VS Code after you have connected to a system.

**Describe the bug**
Using SEU there is a "changed date" for every line. After editing a source member in VSCODE the date field for all lines is set to 0.

**To Reproduce**
Just save any source member.

**Expected behavior**
Date for unchanged lines should stay the same. Date for changed lines should be set to current date.

**Screenshots**
![image](https://github.com/codefori/vscode-ibmi/assets/38526430/c7b50a44-ed97-4caa-892f-c1bd3401da59)

**Environment (please complete the following information):**
 - Extension version 2.11.4
 - IBM i OS version 7.5

**Additional context**

**Comment by sebjulliand** [comment]
Hi @HerbertPfeifer ,
please check out the documentation page about Source date support: https://codefori.github.io/docs/developing/sourcedates/

Turning it on will solve your issue.
