### ISSUE TITLE
Trying to debug with SEP

### ISSUE THREAD

**Issue by Gregory1701** [codefori/vscode-ibmi#2156]
I have the debug service running, but anytime I try to set a service entry point, I get this error.
My Trace:
```
From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"IBMiDebug","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true,"supportsArgsCanBeInterpretedByShell":true,"supportsMemoryEvent":true,"supportsStartDebuggingRequest":true})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsEvaluateForHovers":true,"supportsSetVariable":true,"supportsValueFormattingOptions":true,"supportsModulesRequest":true,"supportTerminateDebuggee":true,"supportsFunctionBreakpoints":true,"supportsConfigurationDoneRequest":true}}
From client: launch({"type":"IBMiDebug","request":"launch","subType":"sep","action":"set","name":"Service Entry Point","user":"<user>","password":"<password>","host":"AS400295.PCRICHARD.COM","port":8005,"sepDaemonPort":8008,"secure":true,"ignoreCertificateErrors":false,"library":"TEST_PGM","program":"ADDSDV","programType":"*PGM","module":"*ALL","procedure":"*ALL","trace":true,"workbenchSettings":{"updateProductionFiles":false,"enableDebugTracing":false},"__sessionId":"be64c71c-632e-48c9-a652-1b9124118fcf"})
To client: {"type":"event","seq":2,"event":"initialized"}
To client: {"type":"event","seq":3,"event":"exited","body":{"exitcode":0,"message":"DBGM0008E Failed to set service entry point on TEST_PGM/ADDSDV *PGM."}}
To client: {"type":"response","seq":0,"request_seq":2,"success":false,"command":"launch","body":{"error":{"id":"90008","format":"DBGM0008E Failed to set service entry point on TEST_PGM/ADDSDV *PGM.","showUser":true}}}
``` 

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.11.4|
|Visual Studio Code version|1.91.0|
|Operating System|linux_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Configuration Editing (configuration-editing): 1.0.0
Db2 for IBM i (vscode-db2i): 1.0.0
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Copilot (copilot): 1.211.0
GitHub Copilot Chat (copilot-chat): 0.17.0
IBM i Debug (ibmidebug): 2.0.1
JSON Language Features (json-language-features): 1.0.0
Jira and Bitbucket (Atlassian Labs) (atlascode): 3.0.10
Local Tunnel Port Forwarding (tunnel-forwarding): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.26.8
Server Ready Action (debug-server-ready): 1.0.0
Thunder Client (vscode-thunder-client): 2.24.12
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
YAML (vscode-yaml): 1.15.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|10|
|CCSID Origin|37|
|Runtime CCSID|37|
|Default CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv||||
|find|setccsid||||
|git|||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

**Comment by mkwan01** [comment]
The DAP trace does not contain enough information about the error. Please also attach the debug service log and the debug service eclipse instance log.

Debug service log:
/QIBM/UserData/IBMIDEBUGSERVICE/DebugService_log.txt

Debug service Eclipse instance log:
/QIBM/UserData/IBMIDEBUGSERVICE/startDebugService_workspace/.metadata/.log

**Comment by Gregory1701** [comment]
[DebugService_log.txt](https://github.com/user-attachments/files/16148588/DebugService_log.txt)

I do not have anything within my /QIBM/UserData/IBMIDEBUGSERVICE/startDebugService_workspace/ folder.

**Comment by mkwan01** [comment]
The subdirectory .metadata is hidden under the "ls" command. Same for the file .log. You need to use "ls -a" to show these files. You can copy it to a regular file and then open the regular file:
> cp /QIBM/UserData/IBMIDEBUGSERVICE/startDebugService_workspace/.metadata/.log /home/myid/eclipse_log.txt

**Comment by Gregory1701** [comment]
[eclipse_log.txt](https://github.com/user-attachments/files/16149957/eclipse_log.txt)

**Comment by mkwan01** [comment]
The Eclipse log contains the following exception:
```
Caused by: com.ibm.as400.access.ObjectDoesNotExistException: /QSYS.lib/QDEVTOOLS.lib/QRSEUTILS.srvpgm: Object does not exist.
	at com.ibm.as400.access.ServiceProgramCall.run(ServiceProgramCall.java:387)
	at com.ibm.as400.data.PcmlProgram.callProgram(PcmlProgram.java:690)
	at com.ibm.as400.data.PcmlDocument.callProgram(PcmlDocument.java:460)
	at com.ibm.as400.data.ProgramCallDocument.callProgram(ProgramCallDocument.java:451)
```

**Comment by mkwan01** [comment]
This means you do not have 5770wds option 60 installed. Please install 5770wds option 60 and try again.

**Comment by sebjulliand** [comment]
> This means you do not have 5770wds option 60 installed. Please install 5770wds option 60 and try again.

@mkwan01 good finding. This should be added to the extension's description.

**Comment by worksofliam** [comment]
Sorry, didn't mean to close.

@sebjulliand @Gregory1701 What is the status here? We need a lil' doc updating?

**Comment by sebjulliand** [comment]
Guess it can be closed. The licensed product was missing and that's it.
