### ISSUE TITLE
Can the code for IBMi debugger be used with insecure ports?

### ISSUE THREAD

**Issue by mrbenp** [codefori/vscode-ibmi#2166]
👉🏻 The defult port 8005 is used by another WEB app, and I don't know how to find an unused secure PORT. We asked IBM, and as soon as we told  IBM it's for VScode the ibm tech told me to ask the Vscode forum. 

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.11.0|
|Visual Studio Code version|1.91.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
AngularDoc for Visual Studio Code (angulardoc-vscode): 6.1.3
AngularJS Template Autocomplete (angularjs-template-autocomplete): 1.0.13
COBOL (cobol): 7.7.9
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Configuration Editing (configuration-editing): 1.0.0
Db2 for IBM i (vscode-db2i): 1.0.0
ESLint (vscode-eslint): 3.0.10
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.20.0
Extension Test Runner (extension-test-runner): 0.0.11
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Debug (ibmidebug): 2.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Jira and Bitbucket (Atlassian Labs) (atlascode): 3.0.10
Live Server (LiveServer): 5.7.9
Merge Conflict (merge-conflict): 1.0.0
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Red Hat Dependency Analytics (fabric8-analytics): 0.9.4
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
YAML (vscode-yaml): 1.15.0
Zowe Explorer (vscode-extension-for-zowe): 2.16.3
ng1.5 components utility (vscode-angular-components-intellisense): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R3M0|
|Tech Refresh|n/a|
|CCSID Origin|37|
|Runtime CCSID|37|
|Default CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|ILEDITOR.GETMBRINFO|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|||||
|grep|setccsid|||||
|ls|tar|||||
|md5sum||||||
|sort||||||
|stat||||||
</details>

**Comment by sebjulliand** [comment]
The Debug Service requires two (v1) or three (v2) TCP ports to run.
Each port can be changed in the configuration file located here: `/QIBM/ProdData/IBMiDebugService/bin/DebugService.env`
You can open it from the IFS browser of the IBM i Debugger view (on the Debug Service item).
Stop the Debug Service before changing the file.

This are the configuration values you'll want to change:
![image](https://github.com/user-attachments/assets/29306dde-c4b9-40a5-a1c2-49b13e8a9cf7)

Once you've changed them, restart the Debug Service and reconnect Code for i so it get the new ports to connect to.

**Comment by worksofliam** [comment]
@sebjulliand Maybe I should add this to our documentation.

**Comment by sebjulliand** [comment]
> @sebjulliand Maybe I should add this to our documentation.

@worksofliam absolutely!

> Thanks for the reply. I'm having difficulty identifying 3 **secure** ports to change in the configuration above. Can I use any **insecure** ports not in use?

@mrbenp no TCP port is secure or non-secure. It all depends on the service that uses it. So in your case, you just need to pick ports that are not already in use by another service/application.

**Comment by mrbenp** [comment]
Perfect.. Thank you for all the quick replies.
