### ISSUE TITLE
Opening files with $ sign in name

### ISSUE THREAD

**Issue by Mdcms** [codefori/vscode-ibmi#2177]
We can't open files/members any more when name of it has a $ sign in it for example ren$sign.cblle. This is not the case when I went back to 2.9.0. 
After that I tried every version and did not work any more. What did change? And I feel like depending on versions readonly and position attributes don't work the way expected.
Help appreciated.
Thank you.

**Comment by worksofliam** [comment]
Please share the Code for IBM i output channel when both versions try and open the file. Thanks!

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by Mdcms** [comment]
With Code IBM I version v2.9.0 the file opens correctly and we get the following output:
/home/REN: /QOpenSys/usr/bin/qsh
system  "CHKOBJ OBJ(REN/QCBLSRC) OBJTYPE(*FILE) AUT(*UPD)"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/REN: /QOpenSys/usr/bin/qsh
system  "QSYS/CPYTOSTMF FROMMBR('/QSYS.LIB/REN.LIB/QCBLSRC.FILE/REN\$T01.MBR') TOSTMF('/tmp/vscodetemp-O_vHgBRecD') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": "CPCA082:  Object copied."
}

With the newest Code IBM I version v2.12.0 we get the error and we get:

/home/REN: /QOpenSys/usr/bin/qsh
system  "CHKOBJ OBJ(REN/QCBLSRC) OBJTYPE(*FILE) AUT(*UPD)"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/REN: /QOpenSys/usr/bin/qsh
system  "QSYS/CPYTOSTMF FROMMBR('/QSYS.LIB/REN.LIB/QCBLSRC.FILE/REN\\$T01.MBR') TOSTMF('/tmp/vscodetemp-O_3yTqWZd4') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "CPFA0A9:  Object not found.  Object is /QSYS.LIB/REN.LIB/QCBLSRC.FILE/REN/.MBR.\nCPFA097:  Object not copied.  Object is /QSYS.LIB/REN.LIB/QCBLSRC.FILE/REN\\.MBR."
}

![2024-07-22 19_24_27-REN$T01 CBLLE - MDOpen-vsc-8 6 - Visual Studio Code](https://github.com/user-attachments/assets/1a8e51d9-d997-484d-b21c-76f48edcdb20)
