### ISSUE TITLE
I can open a source member from the greenscreen AND VS Code at the same time

### ISSUE THREAD

**Issue by HerbertPfeifer** [codefori/vscode-ibmi#2194]
Save us time! Click 'Report an Issue' from the Help and Support panel inside of VS Code after you have connected to a system.

**Describe the bug**
It should only be possible to open a source member for editing one time. If you are working with PDM and VS Code it is very dangerous to overwrite work you have done on the other system.

**To Reproduce**
1. Open a Source Member in PDM on the greenscreen
2. Open the same one in VS Code

OR

1. Open a Source Member in VS Code
2. Open the same one in PDM the greenscreen

**Expected behavior**
If a member is opened for editing, the secons request should be rejected.

**Screenshots**

**Environment (please complete the following information):**
 - Extension version [e.g. 0.x.x]
 - IBM i OS version [e.g. 7.x]

**Additional context**

**Comment by worksofliam** [comment]
Closing as duplicate. We have existing issues and notes in the documentation that explain that Code for IBM i does not currently support member locking.
