### ISSUE TITLE
SEP to support update production

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-ibmi#2196]
This command we call to the debugger doesn't look like we pass in update debug like we do for batch.

We need an additional Boolean parameter to `ibmidebug.create-service-entry-point-with-prompt` to control this.

https://github.com/codefori/vscode-ibmi/blob/master/src/api/debug/index.ts#L457

**Comment by mkwan01** [comment]
This is an enhancement we can add in the next release. As a complete user story, only adding a parameter to ibmidebug.create-service-entry-point-with-prompt is not enough. We also need to add an action on an SEP object to toggle this setting and also show the setting value in the SEP view.

**Comment by mkwan01** [comment]
I will use a simpler implementation, which just honours the "update production files" setting from the code-for-i debug settings page when setting an SEP. We will only go with the more expensive solution of making this setting configurable for each SEP, if there is such a requirement later.

**Comment by mkwan01** [comment]
Just figured out that we also need to update the debug service for this one. SEP debug uses the attach launch configuration. We are not passing the updateProductionFiles setting in the attach launch right now. I will discuss with the team on when we can rebuild the debug service PTF.

**Comment by McJablesSupreme** [comment]
I've been unable to debug any programs that need updprod(*yes). Is there a workaround for this issue while we wait for the update to fix this?

**Comment by mkwan01** [comment]
@McJablesSupreme There is no workaround for the updprod issue in SEP debug. We will need an update to the debug service PTF.

**Comment by McJablesSupreme** [comment]
@mkwan01, that was a really fast reply! Thanks for letting me know. I'll keep an eye out for that.

**Comment by begwhite** [comment]
Change your library containing your database files from *PROD to *TEST. That worked for us.

**Comment by mkwan01** [comment]
This problem was fixed in debug client v2.0.2. The new debug client requires a debug service update via the following host PTFs:
7.3 PTF SJ02996
7.4 PTF SJ03026
7.5 PTF SJ03030

Please note that you need to regenerate the SSL certificate after updating the debug service.

@worksofliam
