### ISSUE TITLE
Cannot read properties of undefined (reading 'getFeatures') Starting IBM i SQL Job

### ISSUE THREAD

**Issue by sboisier** [codefori/vscode-ibmi#2204]
Hi,

Using vscode for i with ibm Db2 for IBM i extension installed.

Created my IBM i connection that is connecting without any problems.

Since this morning when I'm trying to execute SQL statments on my system I'm receiving this error :

Cannot read properties of undefined (reading 'getFeatures') when starting SQL Job on my IBM i

This was working fine before so really disapointed with this error.

Is somebody could help with this.

Regards

Sylvain

**Comment by worksofliam** [comment]
@sboisier I just pushed vscode-db2i 1.1.1 which will fix this issue.

@sebjulliand should we push out 2.12.1 which has the event fix?

**Comment by sebjulliand** [comment]
@worksofliam yes! It has the events fix and the logs download too. I'm all for a new release 😊

**Comment by worksofliam** [comment]
@sebjulliand I am going to make 2.12.1 and close this issue.
