### ISSUE TITLE
Routine QCMDEXC in QSYS2 not found with specified parameters. (42884)

### ISSUE THREAD

**Issue by a4ginatl** [codefori/vscode-ibmi#2210]
What is the system looking for here?

This system is a v5.4 system.

Thanks.
Darryl Freinkel.

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.12.1|
|Visual Studio Code version|1.92.0|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 10.7.23
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Configuration Editing (configuration-editing): 1.0.0
Db2 for IBM i (vscode-db2i): 1.1.1
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Debug (ibmidebug): 2.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.5
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|n/a|
|Tech Refresh|n/a|
|CCSID Origin|65535|
|Runtime CCSID|-2|
|Default CCSID|?|
|SQL|Disabled
|Source dates|Disabled

### Enabled features

|/usr/bin|/QSYS.LIB|
|-|-|
|attr|QZDFMDB2.PGM|
|iconv||
|ls||
|setccsid||
|tar||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPD0043:  Keyword SRCSTMF not valid for this command.\nCPF0001:  Error found on RUNSQLSTM command.",
    "cwd": "/"
  },
  {
    "command": "/usr/bin/attr \"/QIBM/ProdData/IBMiDebugService/bin/DebugService.env\" CCSID",
    "code": 1,
    "stderr": "attr: 001-2248 Error found getting attributes for file /QIBM/ProdData/IBMiDebugService/bin/DebugService.env.  No such path or directory.",
    "cwd": "/home/A4G_SSH"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"a4g_ssh\" && export HOST=\"192.168.250.5\" && export HOME=\"/home/A4G_SSH\" && export WORKDIR=\"/home/A4G_SSH\" && export LIBLS=\"A4G21XSF A4G21XSFS QTEMP QGPL\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/A4G_SSH"
  }
]
```
</details>

**Comment by worksofliam** [comment]
We do not support anything below 7.3.

**Comment by a4ginatl** [comment]
Pity, there are so many companies that could use this. I am not looking for all functionality. Just to be able to use the explorer and edit the members. No debug, SQL or anything like that.

Thanks, Darryl

**Comment by sebjulliand** [comment]
> Pity, there are so many companies that could use this. I am not looking for all functionality. Just to be able to use the explorer and edit the members. No debug, SQL or anything like that.
> 
> Thanks, Darryl

You can always go back to a previous version that worked for you then. The explorer has been around for ages, so if it worked for you with an old version, just go back to it.
![image](https://github.com/user-attachments/assets/b67cb27a-576c-4ce5-9a7b-70cbf595bab3)

**Comment by a4ginatl** [comment]
Thank you for the information. I will try it later today.

 

Questions:

1.	Can I have the older and current versions on the same PC?
2.	How would I set the older version to not update to a newer version?

 

Thank you.

 

Darryl Freinkel

A4G

Telephone: 770.321.8562

**Comment by sebjulliand** [comment]
> Thank you for the information. I will try it later today.
> Questions:
> 1. Can I have the older and current versions on the same PC?
> 2. How would I set the older version to not update to a newer version?

1. No, you can't by default. But looking at the code CLI option, there is a `--extensions-dir` option that lets you define the extensions' location. So I guess you could create a dedicated shortcut to open VSCode, adding `--extensions-dir path_to_a_dir` to the command line so this particular shortcut would open VSCode with another set of extensions. If it doesn't work, maybe have a look at the Portable Mode: https://code.visualstudio.com/docs/editor/portable#_enable-portable-mode
![image](https://github.com/user-attachments/assets/dddbb7d9-9fb8-44e7-81f2-6e090139a48c)

2. Disable the `Auto Update` for the extension.
![image](https://github.com/user-attachments/assets/c97b3c35-6a47-45b0-a059-c8a0c732f92d)

**Comment by a4ginatl** [comment]
Thank you

 

Darryl Freinkel

A4G

Telephone: 770.321.8562
