### ISSUE TITLE
Debug server will not start after PTF update

### ISSUE THREAD

**Issue by JonFP** [codefori/vscode-ibmi#2222]
👉🏻 Applied PTF SI86178 to obtain the SEP debugging capabilities but now debug server will not start.

The documentation states that Java 8 is required but my error message says java 11 is needed.

This is the error from the attempt to start the server.

java version "1.8.0_411"
Java(TM) SE Runtime Environment (build 8.0.8.25 - pap6480sr8fp25-20240328_01(SR8 FP25))
IBM J9 VM (build 2.9, JRE 1.8.0 OS/400 ppc64-64-Bit Compressed References 20240305_66992 (JIT enabled, AOT enabled)
OpenJ9   - e3126d7
OMR      - f2f50a8
IBM      - b81b1e2)
JCL - 20240322_01 based on Oracle jdk8u411-b09
Incorrect Java version. Java 11 is required.

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.12.1|
|Visual Studio Code version|1.92.2|
|Operating System|darwin_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 10.8.14
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Configuration Editing (configuration-editing): 1.0.0
Db2 for IBM i (vscode-db2i): 1.2.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.20.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Debug (ibmidebug): 2.0.1
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.26.8
Server Ready Action (debug-server-ready): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|10|
|CCSID Origin|37|
|Runtime CCSID|37|
|Default CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv||||
|git|setccsid||||
|grep|tar||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=PARTNER400
CURLIB=PARTNER400
HOME=/home/PARIS
HOST=ideveloper
LIBLS=CODE4ITEST SAMPLE LIBHTTP SIDDBV2 YAJL QTEMP QGPL
LOGIN=paris
LOGNAME=paris
MAIL=/var/spool/mail/paris
OLDPWD=/home/PARIS
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/PARIS
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=10.29.5.11 61301 22
SSH_CONNECTION=10.29.5.11 61301 172.29.5.35 22
TZ=<EST>5<EDT>,M3.2.0,M11.1.0
USER=paris
USERNAME=paris
WORKDIR=/home/PARIS
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF2111:  Library ILEDITOR already exists.",
    "cwd": "/home/PARIS"
  }
]
```
</details>

**Comment by sebjulliand** [comment]
Hi John,
the documentation actually states that Java 11 is required for Debug Service v2 (the version with SEP):
![image](https://github.com/user-attachments/assets/eb8ca7db-2eab-439d-8159-4960c35f4902)
Make sure you have the other PTF and 5770WDS option 60 installed too.

Regenerate the debug service certificate once everything is installed. It will sort everything out for you.
![image](https://github.com/user-attachments/assets/74b1543e-311b-43f6-acbe-eab51c34b95c)

**Comment by JonFP** [comment]
Thanks for the info - now I just have to work out how to install that. 

By the way - Looks to me like the doc you are showing has not been published yet.  I am looking at https://codefori.github.io/docs/developing/debug/ and there is nothing there - no Version 1 ... Version 2 stuff.

Also there is nothing in the extension doc to reference any Java dependency at all. Just the host PTFs

**Comment by chrjorgensen** [comment]
Hi Jon.

Do you not see this when scrolling down [the page for debug documentation](https://codefori.github.io/docs/developing/debug/#required-ptfs)?

![billede](https://github.com/user-attachments/assets/9f8c111c-c968-43b5-a922-1c29f78604b9)

**Comment by JonFP** [comment]
I see it now - after trying the link you provided - but yesterday and earlier today that Version 2 stuff was not there. I even did a force refresh of the page in two browsers and it wasn't there. No clue why but ...

Might I suggest that the Version 2 information be the default that is shown. Few are going to want to use the old non-SEP version.

**Comment by JonFP** [comment]
Java 11 has been installed and I confirmed it was at the specified location (/QOpenSys/QIBM/ProdData/JavaVM/jdk11/64bit) but I am still getting the "Needs Java 11" error.  Any ideas?

**Comment by worksofliam** [comment]
@JonFP  before connecting, right click the connection and reload the settings. Might need to clear a cache.

**Comment by JonFP** [comment]
Assuming you mean "Connect and reload ...." then it made no difference.

Debiug server starts up just fine but the Debug Service dies with the Java 11 error.

**Comment by sebjulliand** [comment]
@JonFP did you regenerate the certificate?
You can also open the debug service configuration:
![image](https://github.com/user-attachments/assets/7aacb0b0-33c9-4d13-942b-80ecc6ea736c)

There must be a `JAVA_HOME` variable in there.
![image](https://github.com/user-attachments/assets/7dc8e21b-5ff4-4f41-99a7-efc57fdf6f36)

Make sure it points to `/QOpenSys/QIBM/ProdData/JavaVM/jdk11/64bit`; if not, change it.

**Comment by JonFP** [comment]
No I did not.  I looked for the option but it did not appear.

**Comment by sebjulliand** [comment]
This was addressed during today's `Code for i Friday` session.
Turns out the Debug Service configuration was lost after it's been updated from v1 to v2. But since the certificate was still found, the IBM i debugger view did not warn about it and offered to regenerate the certificate.
John regenerated the certificate and it sorted it out.

A enhancement is underway to warn the user about this kind of situation and prevent confusion: https://github.com/codefori/vscode-ibmi/pull/2227

**Comment by JonFP** [comment]
Issue resolved during the Friday session.  Short version is that the PTF caused Code for i to overwrite the configuration file but had not updated it to point to the correct Java version.

Circumvention is to manually force recreation of the certificates which will them allow the config to be updated.

Thanks to all but particularly Seb.

Now to see if it actually works!
