### ISSUE TITLE
Source member ending in dollar sign

### ISSUE THREAD

**Issue by Gregory1701** [codefori/vscode-ibmi#2235]
We have some source member that have a $ in the name. 

Easy to recreate:

- Create a new source member, mine happened to be CLCDL$
- It will create the source member, but then give this error:
![image](https://github.com/user-attachments/assets/5f7be144-9651-4656-9a2e-9426df34a4f2)

**Comment by worksofliam** [comment]
Please share the entire contents of your Code for IBM i output channel after the member doesn't open.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by Gregory1701** [comment]
/home/PGMGREGORY: /QOpenSys/usr/bin/qsh
system  "QSYS/CPYTOSTMF FROMMBR('/QSYS.LIB/PGMGREGORY.LIB/QRPGLESRC.FILE/CLCDL\\$.MBR') TOSTMF('/tmp/vscodetemp-O_hlhfdHF9') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "CPFA0A9:  Object not found.  Object is /QSYS.LIB/PGMGREGORY.LIB/QRPGLESRC.FILE/CLCDL/$.MBR.\nCPFA097:  Object not copied.  Object is /QSYS.LIB/PGMGREGORY.LIB/QRPGLESRC.FILE/CLCDL\\$.MBR."
}

**Comment by worksofliam** [comment]
@Gregory1701 Please share the entire output - including any Object Browser output. Thanks!

**Comment by worksofliam** [comment]
@Gregory1701 Basically navigate to the member in the Object Browser, attempt to open it, and then share the entire Code for IBM i output.

**Comment by Gregory1701** [comment]
![image](https://github.com/user-attachments/assets/15ed306e-2f9c-4be8-a47d-888bde74c071)

**Comment by worksofliam** [comment]
@Gregory1701 You can use Control+A to select all in the Output channel. Please paste it here so it can be searched easily.

**Comment by Gregory1701** [comment]
/home/PGMGREGORY: /usr/bin/attr -p /QSYS.LIB/PGMGREGORY.LIB/QRPGLESRC.FILE CCSID
{
    "code": 0,
    "signal": null,
    "stdout": "CCSID=37",
    "stderr": ""
}

/home/PGMGREGORY: /QOpenSys/usr/bin/qsh
system  "QSYS/CPYTOSTMF FROMMBR('/QSYS.LIB/PGMGREGORY.LIB/QRPGLESRC.FILE/CLCDL\\$.MBR') TOSTMF('/tmp/vscodetemp-O_hlhfdHF9') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "CPFA0A9:  Object not found.  Object is /QSYS.LIB/PGMGREGORY.LIB/QRPGLESRC.FILE/CLCDL/$.MBR.\nCPFA097:  Object not copied.  Object is /QSYS.LIB/PGMGREGORY.LIB/QRPGLESRC.FILE/CLCDL\\$.MBR."
}

/home/PGMGREGORY: /QOpenSys/usr/bin/qsh
system  "QSYS/CPYTOSTMF FROMMBR('/QSYS.LIB/PGMGREGORY.LIB/QRPGLESRC.FILE/CLCDL\\$.MBR') TOSTMF('/tmp/vscodetemp-O_hlhfdHF9') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "CPFA0A9:  Object not found.  Object is /QSYS.LIB/PGMGREGORY.LIB/QRPGLESRC.FILE/CLCDL/$.MBR.\nCPFA097:  Object not copied.  Object is /QSYS.LIB/PGMGREGORY.LIB/QRPGLESRC.FILE/CLCDL\\$.MBR."
}

**Comment by worksofliam** [comment]
@Gregory1701 Last thing. Can you recreate this issue using the 'Report an Issue' button in the Help and Support view? That will also provide additional info we will need to recreate this. Thanks

**Comment by Gregory1701** [comment]
Really? So you are able to create a source member ending with a dollar sign and open it?

**Comment by Gregory1701** [comment]
<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.12.0|
|Visual Studio Code version|1.92.2|
|Operating System|linux_x64|


<details>
<summary>Active extensions</summary>

```
Code for IBM i User Spooled Files (vscode-ibmi-UserSpooledFiles): 0.0.6
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Configuration Editing (configuration-editing): 1.0.0
Db2 for IBM i (vscode-db2i): 1.1.0
Emmet (emmet): 1.0.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Copilot (copilot): 1.219.0
GitHub Copilot Chat (copilot-chat): 0.17.1
Hawkeye Pathfinder (vscode-ibmi-hawkeye): 0.0.7
IBM i Debug (ibmidebug): 2.0.1
JSON Language Features (json-language-features): 1.0.0
Jira and Bitbucket (Atlassian Labs) (atlascode): 3.0.10
Local Tunnel Port Forwarding (tunnel-forwarding): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.26.8
Server Ready Action (debug-server-ready): 1.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
YAML (vscode-yaml): 1.15.0
```
</details>


<hr />


<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|n/a|
|CCSID Origin|37|
|Runtime CCSID|37|
|Default CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|QZDFMDB2.PGM|startDebugService.sh|
|find|iconv||||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>



<details>
<summary>Shell env</summary>

```bash
```
</details>



<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>



<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPFA0A9:  Object not found.  Object is /QSYS.LIB/PGMGREGORY.LIB/QRPGLESRC.FILE/CLCDL/$.MBR.\nCPFA097:  Object not copied.  Object is /QSYS.LIB/PGMGREGORY.LIB/QRPGLESRC.FILE/CLCDL\\$.MBR.",
    "cwd": "/home/PGMGREGORY"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPFA0A9:  Object not found.  Object is /QSYS.LIB/PGMGREGORY.LIB/QRPGLESRC.FILE/CLCDL/$.MBR.\nCPFA097:  Object not copied.  Object is /QSYS.LIB/PGMGREGORY.LIB/QRPGLESRC.FILE/CLCDL\\$.MBR.",
    "cwd": "/home/PGMGREGORY"
  },
  {
    "command": "export BUILDLIB=\"PGMGREGORY\" && export CURLIB=\"PGMGREGORY\" && export USERNAME=\"pgmgregory\" && export HOST=\"prismpcr.pcrichard.com\" && export HOME=\"/home/PGMGREGORY\" && export WORKDIR=\"/home/PGMGREGORY\" && export TGTRLS=\"V7R4M0\" && export LIBLS=\"PGMSTEVEN QGPL DISKNYN DISK RICHARD DTAGREGORY PGMGREGORY QTEMP\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=PGMGREGORY: is not an identifier",
    "cwd": "/home/PGMGREGORY"
  }
]
```
</details>

**Comment by worksofliam** [comment]
A few things:

### Retested

I tested with the latest version of Code for IBM i (2.13.0) and was not able to replicate the issue:

```
/home/LIAMA: /QOpenSys/usr/bin/qsh
system  "QSYS/CPYTOSTMF FROMMBR('/QSYS.LIB/LIAMA.LIB/QRPGLESRC.FILE/BADMBR\$.MBR') TOSTMF('/tmp/vscodetemp-O_gWwVCBcz') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": "CPCA082:  Object copied."
}
```

### Version

I noticed from your additional information that you are one major version behind. Your version indicates 2.12.0, where as 2.13.0 is now available with a possible fix.

Grab this version and let me know how it goes.

**Comment by worksofliam** [comment]
@Gregory1701 Also, if you could share how you were opening the member (Object Browser, or Go to File) that would be great.

**Comment by Gregory1701** [comment]
Oh geez... I have auto update checked so I assumed I was current. Since you pointed out that I was out of date, I did some research and discovered that while on my company's VPN I can't even search for extensions. So I dropped VPN, restarted VS Code and got the updates. And now I can open source members with $ in their name.

Thanks.
