### ISSUE TITLE
IFS browser: Error moving files to directories with spaces in the pathname

### ISSUE THREAD

**Issue by kaspervanderhulst** [codefori/vscode-ibmi#2237]
When uploading a file to a folder on the IFS browser that has a location with a space in the name and then trying to move it to a subfolder in this folder. I get an error. 

![image](https://github.com/user-attachments/assets/ed38cee8-3a9a-4129-a27b-1230483c8394)
Based on the error I'm guessing it cuts of the path at the space and only takes the part of the path after the space to try and move the file

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.13.0|
|Visual Studio Code version|1.92.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 10.8.29
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Configuration Editing (configuration-editing): 1.0.0
Db2 for IBM i (vscode-db2i): 1.3.1
Dev Containers (remote-containers): 0.380.0
Diff & Merge (diff-merge): 0.7.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.20.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitLab Workflow (gitlab-workflow): 5.9.0
IBM i Debug (ibmidebug): 2.0.1
IBM i FileSystem (vscode-ibmi-fs): 0.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
IBM i Project Explorer (vscode-ibmi-projectexplorer): 2.11.1
IntelliCode (vscodeintellicode): 1.3.1
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.26.8
Rainbow CSV (rainbow-csv): 3.12.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
undefined (vscode-sourceorbit): 1.2.3
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|2|
|CCSID Origin|65535|
|Runtime CCSID|65535|
|Default CCSID|500|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv||||
|git|setccsid||||
|grep|tar||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=EASKVHU
CURLIB=EASKVHU
HOME=/home/EASKVHU
HOST=10.17.58.1
LIBLS=QTEMP QGPL QS36F ASSAB SUBR36 SPESAB ASBOEKTEST ASBOEKV2 TESCOMMON TESBH ASBOEKV3 TESDEV NEWLOON ACCLOON TESLOON NEWLOONP NEWLOONA NEWLOONT
LOGIN=easkvhu
LOGNAME=easkvhu
MAIL=/var/spool/mail/easkvhu
OLDPWD=/home/EASKVHU
PASE_USRGRP_LIMITED=N
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin:/QOpenSys/usr/bin:/usr/bin
PWD=/home/EASKVHU
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=10.222.8.126 60640 22
SSH_CONNECTION=10.222.8.126 60640 10.17.58.1 22
TZ=<CET>-1<CEST>,M3.5.0,M10.5.0/03:00:00
USER=easkvhu
USERNAME=easkvhu
WORKDIR=/home/EASKVHU
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "cd '/Import Hastus/IN' && /QOpenSys/pkgs/bin/stat --dereference --printf=\"%A\t%h\t%U\t%G\t%s\t%Y\t%n\n\" * .*  ",
    "code": 1,
    "stderr": "/QOpenSys/pkgs/bin/stat: cannot stat '*': No such file or directory",
    "cwd": "/home/EASKVHU"
  },
  {
    "command": "cd '/Import Hastus/IN' && /QOpenSys/pkgs/bin/stat --dereference --printf=\"%A\t%h\t%U\t%G\t%s\t%Y\t%n\n\" * .*  ",
    "code": 1,
    "stderr": "/QOpenSys/pkgs/bin/stat: cannot stat '*': No such file or directory",
    "cwd": "/home/EASKVHU"
  },
  {
    "command": "cd '/Import Hastus/IN' && /QOpenSys/pkgs/bin/stat --dereference --printf=\"%A\t%h\t%U\t%G\t%s\t%Y\t%n\n\" * .*  ",
    "code": 1,
    "stderr": "/QOpenSys/pkgs/bin/stat: cannot stat '*': No such file or directory",
    "cwd": "/home/EASKVHU"
  }
]
```
</details>

**Comment by chrjorgensen** [comment]
@kaspervanderhulst Are you dragging the file to the subfolder in IFS Browser and selecting `Move` (or have `move` as the default drag and drop behavior)?

I just want to confirm I've understood your issue correctly before publishing a fix for your error...

**Comment by kaspervanderhulst** [comment]
I am indeed dragging and dropping the file and then selecting 'Move'

**Comment by chrjorgensen** [comment]
@kaspervanderhulst I will notify your on this issue report when a fix is ready - stay tuned!

**Comment by chrjorgensen** [comment]
@kaspervanderhulst We have fixed your issue, and you can test it by installing pre-release 2.13.1. 😃
