### ISSUE TITLE
What does this DB2 for i error mean?

### ISSUE THREAD

**Issue by zkarj735** [codefori/vscode-ibmi#2242]
Every time I connect to a server after launching VSCode, I get the following notification.

![image](https://github.com/user-attachments/assets/142b5122-3d81-4a4e-8a3e-c8e077a20a3f)

If I click the Show button, the following is displayed. I have no idea what this is indicating.

![image](https://github.com/user-attachments/assets/2963da25-44cf-4cad-a300-e63f86a0aa0b)

**Comment by sebjulliand** [comment]
Please open DB2 extension related issues here: https://github.com/codefori/vscode-db2i/issues

Usually, this means the DB2 extension had some issue checking or updating the remote `codefori-xxx.jar` file. It happened to me a few days ago. Deleting your `/home/T816416/.vscode` folder, restarting VSCode and reconnecting may help with this issue.

**Comment by zkarj735** [comment]
Thanks, that seems to have done the trick. Noted on the correct location for issues in future.

**Comment by zkarj735** [comment]
Workaround successful
