### ISSUE TITLE
Unable to delete protected filters

### ISSUE THREAD

**Issue by stellars64** [codefori/vscode-ibmi#2251]
When filters are marked as protected, they are unable to be deleted. There is no error message, the deletion simply does not happen.

Reproduce:
Create a new protected filter, or mark an existing filter as protected.
Right click the filter, and select Delete.

Expected behavior:
That the filter gets deleted. It should only be preventing source members from being modified, not the filter itself.

This issue may be related to [https://github.com/codefori/vscode-ibmi/issues/763](url)

**Comment by sebjulliand** [comment]
Good catch @stellars64 !
A fix is on its way (see #2252)
