### ISSUE TITLE
TN5250 terminal accentued characters not correctly displayed

### ISSUE THREAD

**Issue by fredericpetit** [codefori/vscode-ibmi#2253]
Type: <b>Bug</b>

When opening a TN5250 terminal, accentued french characters are not displayed correctly.

Extension version: 2.13.0
VS Code version: Code 1.93.0 (Universal) (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Darwin arm64 23.6.0
AS400: OS400 v7.4 QCSSID 297
Screenshot :
![Capture d’écran 2024-09-12 à 15 07 21](https://github.com/user-attachments/assets/c90c77f8-2e37-4e0b-a504-27b90f339ab3)

Settings for Terminals
- 5250 encoding : default
- 5250 Terminal Type : IBM-3477-FC

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|8, 9, 9|
|Memory (System)|24.00GB (2.22GB free)|
|Process Argv|--crash-reporter-id 9405c5e7-6ff6-40b4-8dc2-a20108514c10 --crash-reporter-id 9405c5e7-6ff6-40b4-8dc2-a20108514c10|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31134655
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
pme_test_t:31118333
ei213698:31121563

```

</details>

**Comment by worksofliam** [comment]
@sebjulliand If that's the case I don't think this is a Code for IBM i issue.

What if you use `map=297` as an environment variable?

```
TERM=xterm /QOpenSys/pkgs/bin/tn5250 map=297 localhost
```

@fredericpetit You can set the map inside of Code for IBM i in the connection settings -> terminals.

**Comment by sebjulliand** [comment]
@worksofliam I did set the map and all; it doesn't change anything.
I tried the standalone version of tn5250 on Windows and the characters show up correctly. So this issue is either in tn5250 or bash, I guess.

**Comment by worksofliam** [comment]
@sebjulliand probably worth @fredericpetit raising an issue in IBM/ibmi-oss-docs and us closing this issue.

**Comment by fredericpetit** [comment]
@sebjulliand I try with map=297 but it change nothing. I'll raising an issue in IBM. Will inform you if I have a positive result.
