### ISSUE TITLE
Failing to get Db2 level

### ISSUE THREAD

**Issue by pgmchrisgz** [codefori/vscode-ibmi#2267]
I get an error when connecting to one of my connections. I cannot start an SQL job on this connection.

This is the VS Code notification pop up:

Something went really wrong during the update process! Check the Db2 for i Output log for the log

And this is the output:

Failed to get Db2 level. User does not have enough authority: NOT AUTHORIZED TO COMMAND WRKPTFGRP. (42501)
{"assetPath":"c:\\Users\\me\\.vscode\\extensions\\halcyontechltd.vscode-db2i-1.5.1\\dist\\mapepire-server-2.1.4.jar","assetExists":true}
{"basename":"mapepire-server-2.1.4.jar"}
{"code":0,"signal":null,"stdout":"/home/ME/.vscode/","stderr":""}
{"remotePath":"/home/PGMCHRISGZ/.vscode/mapepire-server-2.1.4.jar","ExecutablePathDir":"$HOME/.vscode/"}
{"code":3,"transferred":[]}
QIBM_JAVA_STDIO_CONVERT=N QIBM_PASE_DESCRIPTOR_STDIO=B QIBM_USE_DESCRIPTOR_STDIO=Y QIBM_MULTI_THREADED=Y exec undefined
{"id":"id9","type":"connect","technique":"tcp","application":"vscode-db2i 1.5.1","props":"libraries='';naming=system;full open=false;transaction isolation=none;query optimize goal=1;block size=512"}
bash: line 0: exec: undefined: not found

Exited with code 127.

<hr />

**Comment by sebjulliand** [comment]
Hi @pgmchrisgz ,
run this from QSH or a terminal:
```shell
chmod 755 /home/PGMCHRISGZ/.vscode/mapepire-server-2.1.4.jar
```

Then reconnect; the error should go away.

**Comment by pgmchrisgz** [comment]
Thanks, that did it!

**Comment by andreasweller** [comment]
Same here! Thanx

**Comment by BrianGarland** [comment]
I just tried the chmod command because I've been seeing this message when connection.   It did not work for me.   Is there anything else I can try?

**Comment by sebjulliand** [comment]
Delete the .vscore folder in your home directory (or the directory holding temporary data, set in your connection settings...it's your home folder/.vscore by default.
Then reconnect.

**Comment by BrianGarland** [comment]
That worked, thanks!
