### ISSUE TITLE
Debug user job with SEP when user does not have *ALLOBJ

### ISSUE THREAD

**Issue by begwhite** [codefori/vscode-ibmi#2268]
Been trying to debug a program for another user's job with SEP but keep getting error user does not have *ALLOBJ. 

Is there some setting somewhere to address this?

JOBQ(QSYS/QUSRNOMAX) JOBD(QSYS/QSYSJOBD) USER(nonALLOBJuser)

Error: User nonALLOBJuser doesn't have *ALLOBJ special authority.

**Comment by mkwan01** [comment]
SEP debug with another user's profile will be supported in the next debug service and client update (probably around end of the year).

**Comment by arco400** [comment]
> SEP debug with another user's profile will be supported in the next debug service and client update (probably around end of the year).

That is good news!
Thank you!

**Comment by heymchri** [comment]
That is awesome news indeed!!
