### ISSUE TITLE
Object browser unable to access source and object

### ISSUE THREAD

**Issue by slchongwy** [codefori/vscode-ibmi#2276]
Does anyone face error message prompt while access object browser as attach here? Is it due to authority?

<img width="442" alt="image" src="https://github.com/user-attachments/assets/9e9e3a89-2a72-4490-a3a5-3a01af7ca57b">

**Comment by sebjulliand** [comment]
Trying to open an object (like a *PGM in your example) will result in this error being displayed.
There is an extension that has not been released yet (but a prerelease is downloadable here: https://github.com/codefori/vscode-ibmi-fs/releases) that will allow you, for some types, to display and edit objects when applicable.
