### ISSUE TITLE
Interface bug: Download client certificate button missing if local certificate does not already exist

### ISSUE THREAD

**Issue by nick-roux** [codefori/vscode-ibmi#2280]
Debug Server fully configured and functional on the IBM i host.

When C:\User\<user>\<server.host.name>_debug_service.crt does not exists the download button is not visible on the
IBM i: Connection Settings | Debugger view.

If the local cert file already exists, the download button does appear.

**To Reproduce**
Delete C:\User\<user>\<server.host.name>_debug_service.crt or move to a PC that has not previously used to debug service.
Connect to <server.host.name>
Ctrl-Shift-P and open IBM i: Connection Settings. Click on Debugger
<img width="468" alt="Missing Download certificate button" src="https://github.com/user-attachments/assets/3c5456e9-98cf-4bb1-9e3c-cf18900bb021">

**Expected behavior**
Button should be visible at all times. 

** Workaround **
Debugger view on the left panel correctly shows "Error: Local certificate not found" and offers the option to download it.
This is fine for users that know where to find that, but many will be looking for it on Connection Settings|Debugger.

**Environment (please complete the following information):**
 - Code for IBM i v2.13.0
 - IBM i Debug v2.0.1
- VSCode
Version: 1.94.0 (user setup)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by sebjulliand** [comment]
Good catch! While this is being resolved, use the IBM i Debugger view to download the client certificate if needed:
![image](https://github.com/user-attachments/assets/4a2950f5-66a9-44aa-9e45-d212b0df9029)
