### ISSUE TITLE
Unable to open the editor due to an unexpected error. Invalid member path

### ISSUE THREAD

**Issue by viruslogic** [codefori/vscode-ibmi#2286]
Hi, I usually use the preview versions and, until a few weeks ago I have had no problems. This changes since version v2.13.1.

From this version onwards, when I try to open any source I get an error message stating: Unable to open the editor due to an unexpected error. After the member I try to open it says (Unknown (FilesystemError): Invalid member path).

If I go back to the release version. The extension works normally again.

I'm probably doing something wrong or it's a configuration problem. Maybe it's a known issue... 

I pass a screenshot with the message.

![image](https://github.com/user-attachments/assets/fb466b32-df83-45d7-8672-876ce2cbd26f)

In this case, the route is indeed wrong. But I don't understand why you are looking there. The correct path is as follows.

![image](https://github.com/user-attachments/assets/d7232c1b-16b0-482b-b9b7-76ea18e61373)

As you can see, the QSYS is missing in the path.

I repeat, this only happens to me from version v2.13.1 onwards. The release version v2.13.0 works correctly. 

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.13.3|
|Visual Studio Code version|1.94.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Autenticación de GitHub (github-authentication): 0.0.2
CL (vscode-clle): 1.1.7
COBOL (cobol): 24.10.12
Características del lenguaje JSON (json-language-features): 1.0.0
Características del lenguaje JavaScript y TypeScript (typescript-language-features): 1.0.0
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Conexión Automática a node.js en modo de depuración (debug-auto-launch): 1.0.0
Cuenta Microsoft (microsoft-authentication): 0.0.1
Db2 for IBM i (vscode-db2i): 1.6.0
Edición de configuración (configuration-editing): 1.0.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.20.0
Fusionar conflicto (merge-conflict): 1.0.0
GIT (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitLens — Git supercharged (gitlens): 15.6.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
TODO Highlight (vscode-todo-highlight): 1.0.5
```
</details>

**Comment by Alastyr** [comment]
Hi, I have the same problem with v2.13.2. v2.13.0 works correctly.

**Comment by devinhh** [comment]
Thanks for posting this.  I am having the same problem also.

**Comment by sebjulliand** [comment]
Hi guys,
you're all trying to access a member located on an iASP, right?

**Comment by devinhh** [comment]
That is correct.  I am able to access members that are not on the iASP.

**Comment by sebjulliand** [comment]
There is indeed an issue with members located on an iasp, I reproduced it.
I'll see it fixed 😊

**Comment by sebjulliand** [comment]
Once this fix is approved, we'll make a new release.

**Comment by sebjulliand** [comment]
Release `2.13.4` is out and it fixes this issue 😄

**Comment by devinhh** [comment]
Thanks for the quick fix

**Comment by viruslogic** [comment]
Thank you very much, how fast!

I confirm that it is already solved.

Cheers!!
