### ISSUE TITLE
Special Characters Being Automatically Converted To Blanks

### ISSUE THREAD

**Issue by Cody-Asher-Costco** [codefori/vscode-ibmi#2298]
Type: <b>Bug</b>

After opening a file, French special characters, for example "é",  are automatically converted to blanks. Also random characters are inserted that are not visible on the iSeries.
![Special Character VSCODE](https://github.com/user-attachments/assets/3ace27f4-aa26-471d-aee2-99ee475040db)

Extension version: 2.13.5
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 6850U with Radeon Graphics      (16 x 2695)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|30.77GB (19.59GB free)|
|Process Argv|--crash-reporter-id 2cb3d2e2-9ef3-4b81-b4a6-f623f2bc2a3e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1:31157159
showchatpanel:31153267
5fd0e150:31155592
icondisabled:31158250

```

</details>

**Comment by worksofliam** [comment]
I am going to close this for now.

@Cody-Asher-Costco In the future, issues must be opened with steps for us to recreate these issues you are facing.
