### ISSUE TITLE
Auto-connect to server configuration

### ISSUE THREAD

**Issue by p-behr** [codefori/vscode-ibmi#2300]
If I open VS Code with an RPG file left open (or open a local RPG file) I don't always want to connect to an IBM i.
I think auto-connect could be a really handy feature, though I think it needs a bit of configuration.

A global setting for auto-connect would be helpful (yes/no/ask me).
"Yes" would auto-connect to the last connection
"No" would never connect
"Ask Me"pop up a dialog box and ask me which system I want to connect to and give me the option to not connect to any of them.

**Comment by sebjulliand** [comment]
@p-behr next release will include your idea 😉
