### ISSUE TITLE
Members prefixed "£" not loading

### ISSUE THREAD

**Issue by ANSMAN-C** [codefori/vscode-ibmi#2303]
Good Afternoon - A Newbie here,

I'm hoping I could get some help?

Members appear in the Object Browser, but then fail to load with "The editor could not be opened because the file was not found."

I wonder if it's a CCSID problem?

This appeared mid-workday with my open members appearing red and crossed through as I worked. On trying to save:
Failed to save '£PGM.RPGLE': Unable to resolve nonexistent file 'member:/DEV/QRPGLESRC/£PGM.RPGLE?readonly=false&position='

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.13.5|
|Visual Studio Code version|1.93.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 24.10.5
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Configuration Editing (configuration-editing): 1.0.0
Db2 for IBM i (vscode-db2i): 1.6.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.20.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Debug (ibmidebug): 2.0.1
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.26.12
Server Ready Action (debug-server-ready): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|9|
|CCSID Origin|1146|
|Runtime CCSID|1146|
|Default CCSID|1146|
|SQL|Enabled
|Source dates|Disabled

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the doesn't work.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by ANSMAN-C** [comment]
There's nothing here:

![{3FD1DF8D-CAAE-4E06-BBE3-1999D88481E4}](https://github.com/user-attachments/assets/9bb44d93-1912-447d-a541-8489c14209f9)

**Comment by SJLennon** [comment]
@ANSMAN-C 
You need to select Code for IBM i in the dropdown.  You have Tasks selected.

**Comment by worksofliam** [comment]
Looks like a bug to me. I will assign and take a look on Monday.

**Comment by worksofliam** [comment]
This line right here: https://github.com/codefori/vscode-ibmi/blob/7562569637bafae651c76a399fe3cc90f33ba1f4/src/api/IBMiContent.ts#L955

**Comment by ANSMAN-C** [comment]
Thanks for the support with this.
