### ISSUE TITLE
Convert to Free-form incorreectly handles literals

### ISSUE THREAD

**Issue by JonFP** [codefori/vscode-ibmi#2338]
Given this fixed-form RPGIV:

`D #RdStinPtr      PR                  ExtProc('QtmhRdStin')`
`D  RcvRec                         *   Value`
`D  RcvLen                       10I 0 Const`
`D  RcvRecLen                    10I 0`
`D  WPError                      56`

The converter incorrectly upper-cases the literal QtmhRdStin.  like this

`Dcl-PR #RdStinPtr  EXTPROC('QTMHRDSTIN');` 

Literals should always retain their original case/

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.13.6|
|Visual Studio Code version|1.95.1|
|Operating System|darwin_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 24.10.26
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Configuration Editing (configuration-editing): 1.0.0
Db2 for IBM i (vscode-db2i): 1.6.1
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.20.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Debug (ibmidebug): 2.0.1
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Pylance (vscode-pylance): 2024.11.1
Python (python): 2024.18.0
RPGLE (vscode-rpgle): 0.26.12
RPGLE Free (vscode-rpgfree): 0.0.32
Server Ready Action (debug-server-ready): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

**_Not connected_** 🔌

**Comment by chrjorgensen** [comment]
@JonFP I think this issue is for the [`vscode-rpgfree`](https://github.com/BrianGarland/vscode-rpgfree) extension, which does the free-form conversion. The function is not part of Code for IBM i or `vscode-rpgle`.

Since [`vscode-rpgfree`](https://github.com/BrianGarland/vscode-rpgfree) is not in our GitHub organisation, I'm not able to transfer your issue, so I have to ask you to recreate it over there.

I hope you can get Brian Garland to fix your issue quickly. 😃

**Comment by JonFP** [comment]
Darn it!  Thanks Christian - I had forgotten that it was in a separate project.

Doesn't look like it is going to get fixed in a hurry as there is a similar request dating back to May.

**Comment by chrjorgensen** [comment]
You're welcome, Jon!

Well, it's open source and we can clone it and fix it and offer an PR to Brian... but I do not have time right now. Sorry...
