### ISSUE TITLE
Can't open source files that start with $ (ex. $SRVPGM)

### ISSUE THREAD

**Issue by aaronloo** [codefori/vscode-ibmi#2343]
After update to current version 2.13.6 I can no longer open source files that begin with $.  Unfortunately our entire code base prefixes our service programs with $ so this is a significant inconvenience.  

I tested other special characters (# and @) and they work so it is just the $.

Thank you,
Aaron Loo

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.13.6|
|Visual Studio Code version|1.93.1|
|Operating System|linux_x64|

<details>
<summary>Active extensions</summary>

```
CL (vscode-clle): 1.1.7
COBOL (cobol): 24.10.5
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Configuration Editing (configuration-editing): 1.0.0
Db2 for IBM i (vscode-db2i): 1.6.1
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.20.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Debug (ibmidebug): 2.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|9|
|CCSID Origin|37|
|Runtime CCSID|37|
|Default CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|/QOpenSys/QIBM/ProdData/JavaVM/jdk80|
|-|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|QZDFMDB2.PGM|startDebugService.sh|64bit|
|chsh|iconv|||||
|find|setccsid|||||
|git|tar|||||
|grep||||||
|ls||||||
|md5sum||||||
|sort||||||
|stat||||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=TESTENVMNT
CURLIB=TESTENVMNT
HOME=/home/ALOO
HOST=as400-dev.panetny.com
LIBLS=ALOODEV EPICOR QTEMP QGPL MDRST MDRPARTS TLABARCODE KOLIB KMLIB KMDATA KFLIB DSTPGM DSTPTFP DSTPTFT PAEDIPTF PAEDIBTOM DSTQRY DSTCUST PSACUST PAICUST DSTUPS DSTSHIP DSTDATA DSTCDATA DSTCUST2 PSADATA PAIDATA DSTPAYDB EDIBUYER EDISELLER DSTPREPROD PAIRDYRLS PAIQA DSTQA DSTOVRENV
LOGIN=aloo
LOGNAME=aloo
MAIL=/var/spool/mail/aloo
OLDPWD=/home/ALOO
PASE_USRGRP_LIMITED=N
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/ALOO
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=192.168.220.67 52090 22
SSH_CONNECTION=192.168.220.67 52090 172.18.245.21 22
TZ=<EST>5<EDT>,M3.2.0,M11.1.0
USER=aloo
USERNAME=aloo
WORKDIR=/home/ALOO
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/usr/bin/attr -p /QSYS.LIB/ALOODEV.LIB/QRPGLESRC.FILE/\\\\\\$WAVEPRIOR.MBR CREATE_TIME MODIFY_TIME DATA_SIZE",
    "code": 1,
    "stderr": "attr: 001-2248 Error found getting attributes for file /QSYS.LIB/ALOODEV.LIB/QRPGLESRC.FILE/\\$WAVEPRIOR.MBR.  No such path or directory.",
    "cwd": "/home/ALOO"
  },
  {
    "command": "/usr/bin/attr -p /QSYS.LIB/ALOODEV.LIB/QRPGLESRC.FILE/\\\\\\$WAVEPRIOR.MBR CREATE_TIME MODIFY_TIME DATA_SIZE",
    "code": 1,
    "stderr": "attr: 001-2248 Error found getting attributes for file /QSYS.LIB/ALOODEV.LIB/QRPGLESRC.FILE/\\$WAVEPRIOR.MBR.  No such path or directory.",
    "cwd": "/home/ALOO"
  },
  {
    "command": "/usr/bin/attr -p /QSYS.LIB/ALOODEV.LIB/QRPGLESRC.FILE/\\\\\\$MVTTRKQTY.MBR CREATE_TIME MODIFY_TIME DATA_SIZE",
    "code": 1,
    "stderr": "attr: 001-2248 Error found getting attributes for file /QSYS.LIB/ALOODEV.LIB/QRPGLESRC.FILE/\\$MVTTRKQTY.MBR.  No such path or directory.",
    "cwd": "/home/ALOO"
  }
]
```
</details>

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the list doesn't appear.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by aaronloo** [comment]
/home/ALOO: /QOpenSys/usr/bin/qsh
system  "CHKOBJ OBJ(ALOODEV/QRPGLESRC) OBJTYPE(*FILE) AUT(*UPD)"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/ALOO: /QOpenSys/usr/bin/qsh
system  "QSYS/CPYTOSTMF FROMMBR('/QSYS.LIB/ALOODEV.LIB/QRPGLESRC.FILE/\$GETDFTOQ_.MBR') TOSTMF('/tmp/vscodetemp-O_Cr6uwD87') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
/home/ALOO: /usr/bin/attr -p /QSYS.LIB/ALOODEV.LIB/QRPGLESRC.FILE/\\\$GETDFTOQ_.MBR CREATE_TIME MODIFY_TIME DATA_SIZE
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "attr: 001-2248 Error found getting attributes for file /QSYS.LIB/ALOODEV.LIB/QRPGLESRC.FILE/\\$GETDFTOQ_.MBR.  No such path or directory."
}

{
    "code": 0,
    "signal": null,
    "stdout": "CPCA082: Object copied.",
    "stderr": ""
}

**Comment by worksofliam** [comment]
I think I've got a fix for this and should have a test environment build for you soon.

**Comment by worksofliam** [comment]
We've shipped a pre-release with a fix, and you can switch to the 'pre-release'. When using the new release, before connecting to your server, please right click on your server and use 'Connect and Reload Server Settings'.

<img width="708" alt="image" src="https://github.com/user-attachments/assets/54095c88-797f-48fc-86fc-77cde00e2b92">
