### ISSUE TITLE
I cannot access my QDDSSRC folder on the most recent version

### ISSUE THREAD

**Issue by nmasison** [codefori/vscode-ibmi#2352]
**Describe the bug**
Hello, so in the 'object browser tab of your extension usually i have there my QDDSSRC and QRPGLESRC folder. I was able to access the contents of these folders until recently. I am not sure which exact version but I noticed it on your most recent version (version 2.13.6). I re-installed using version 2.4.0 and it works now.

- also noticed that I can access other user's QDDSSRC folder and that I can download the contents of my QDDSSRC folder. it just doesn't show the contents in the 'object browser' tab.

**To Reproduce**
1. Go to 'object browser' tab.
2. Click on 'QDDSSRC ' folder.
3. wait for it to load. 

**Expected behavior**
to view the contents of my QDDSSRC folder

**Screenshots**
![Screenshot 2024-11-18 141422_copy](https://github.com/user-attachments/assets/aaf65b71-713f-444c-90ed-366354ecb5eb)

**Comment by sebjulliand** [comment]
Hi! Can you share your Code for i output right after you expand your QDDSSRC file, with the latest version?
![code for i output](https://github.com/codefori/vscode-ibmi/assets/11096890/88bc7363-2402-419f-b173-309358b914b9)

Thanks!

**Comment by worksofliam** [comment]
@nmasison 2.4 is very much outdated. I'd recommend 2.13 at least.
