### ISSUE TITLE
Preliminar version 2.13.14 -> Character conversion between CCSID 1200 and CCSID 65535 not valid.

### ISSUE THREAD

**Issue by viruslogic** [codefori/vscode-ibmi#2355]
Hello good morning, today I decided to test the latest preview version that was released a few hours ago. When I connect to the server I get the warning that appears in the title of the issue. Even so, it shows me the list of source files.

![image](https://github.com/user-attachments/assets/2c6a21e5-2401-4689-a1d2-c5d329449017)

I have tried changing the CCSID of my user profile to 284, but I still get the same warning. I don't dare to change the CCSID of my user profile because I don't know what impact this may have on my actions...

If I try to display the content of a source file without changing the CCSID I get an error. Attached is the Code for IBM i log:

![image](https://github.com/user-attachments/assets/d5734ca9-9219-4b47-8afb-d0e0b72acdd3)

In the meantime, I'm going back to the release version...

[CodeForIBMi.txt](https://github.com/user-attachments/files/17811473/CodeForIBMi.txt)

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.13.14|
|Visual Studio Code version|1.95.3|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Autenticación de GitHub (github-authentication): 0.0.2
COBOL (cobol): 24.11.14
Características del lenguaje JSON (json-language-features): 1.0.0
Características del lenguaje JavaScript y TypeScript (typescript-language-features): 1.0.0
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Conexión Automática a node.js en modo de depuración (debug-auto-launch): 1.0.0
Cuenta Microsoft (microsoft-authentication): 0.0.1
Db2 Connect (db2connect): 2.3.1
Db2 for IBM i (vscode-db2i): 1.6.3


Edición de configuración (configuration-editing): 1.0.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.20.0
Fusionar conflicto (merge-conflict): 1.0.0
GIT (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitLens — Git supercharged (gitlens): 16.0.2
IBM i Debug (ibmidebug): 2.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
TODO Highlight (vscode-todo-highlight): 1.0.5
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|4|
|CCSID Origin|65535|
|Runtime CCSID|65535|
|Default CCSID|284|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|/QOpenSys/QIBM/ProdData/JavaVM/jdk80|/QOpenSys/QIBM/ProdData/JavaVM/jdk11|/QOpenSys/QIBM/ProdData/JavaVM/jdk17|
|-|-|-|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|QZDFMDB2.PGM|startDebugService.sh|64bit|64bit|64bit|
|chsh|iconv|||||||
|git|setccsid|||||||
|ls|tar|||||||
|md5sum||||||||
|sort||||||||
|stat||||||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=IDEA
CURLIB=IDEA
HOME=/home/sayago
HOST=POWERQP.QP.NET
LIBLS=IDEA EDPMOD LIBHSSF LIBHTTP QPFTP IQS80CPY $QS65MRP QTEMP QGPL IQSPGM MRPPGM CVEPGM PRF81MOD PRF81FILE PQSMOD VISU35MOD6 PQPMOD VISU35MODP GQPMOD IQSFIL001 IQSFIL901 IQSFCOMUN IQSFILART PQPGEN VISU35MOD PARCHEQS PRF81TMP
LOGIN=sayago
LOGNAME=sayago
MAIL=/var/spool/mail/sayago
OLDPWD=/home/sayago
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/sayago
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=192.168.2.87 56689 22
SSH_CONNECTION=192.168.2.87 56689 192.168.2.2 22
TZ=<CET>-1<CEST>,M3.5.0,M10.5.0/03:00:00
USER=sayago
USERNAME=SAYAGO
WORKDIR=/home/sayago
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "Ñ@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/home/sayago/.vscode/cqsh_1",
    "code": 1,
    "stderr": "CPF2125:  No se ha suprimido ningún objeto.",
    "cwd": "/home/sayago"
  },
  {
    "command": "/home/sayago/.vscode/cqsh_1",
    "code": 1,
    "stderr": "CPF9801:  No se ha encontrado el objeto QCPTOIMPF en la biblioteca QSYS.",
    "cwd": "/home/sayago"
  },
  {
    "command": "/home/sayago/.vscode/cqsh_1",
    "code": 1,
    "stderr": "CPF9801:  No se ha encontrado el objeto QCPFRMIMPF en la biblioteca QSYS.",
    "cwd": "/home/sayago"
  }
]
```
</details>

**Comment by worksofliam** [comment]
Couple of things:

1. It's a pre-release and we're not accepting issues for versions that aren't the primary release yet. I will close this issue, but you can still add more stuff if you want.
2. We just released 2.13.15 which will allow you to navigate your source code again, but you will get the warning still. We have always required your user profile to have a valid CCSID, now we're just showing warnings. See here: https://codefori.github.io/docs/tips/ccsid/

**Comment by viruslogic** [comment]
Hi Liam, thank you very much for your reply. I will take it into account for the next one.

Indeed, I have tested with version 2.13.18 which is the most recent at the moment and it is functional. The curious thing is that now I don't get the warning....

Regarding the CCSID, can you guide me as to the implications of changing my user profile to set a valid one since all objects are created with the default CCSID (the 65535). The fact of not doing it, as I said in my OP, is not knowing the implications it may have.

**Comment by worksofliam** [comment]
@viruslogic with the latest version of the pre-release, you no longer need to change the user CCSID.

Changing the answer the user CCSID is different to each user. I'd do some googling a little bit and see what you can find. Generally if you change a user profile CCSID to the job default the impact is minimum, but again, everyone is different.

**Comment by viruslogic** [comment]
Thank you Barry!

Code for IBM i has changed many of our lives and the way we interact with the AS400. Your work for the community is invaluable. Great Job!!

As for the CCSID, for now I have changed my user profile and put a valid one. I'm going to see the impact. If I see that it gives me problems, I'll leave it as it was.
