### ISSUE TITLE
CAnnot open members with $ in the name

### ISSUE THREAD

**Issue by ttognazzini** [codefori/vscode-ibmi#2364]
Vs Code will not open a member with a $ in the name.

**To Reproduce**
* Create a member in one of your source files with a $ (dollar sign) in the name. I tested with a member named A$ to ensure I could recreate the issue, In use it seems that it will not work with a dollar sing anywhere in the member name.
* Use the object browser to try to open the member.
* You get this error:

![{2DA6DA9A-9D64-4451-BA47-D2D6FADD3568}](https://github.com/user-attachments/assets/f8bcfdf1-ec04-4d8f-929d-d0c0a7281190)

It returns this message "The editor could not be opened because the file was not found." There is a create file button under the message. If you press the cerate file button you get an error saying the it already exists.

**Expected behavior**
It should open the member to work with. It used to work, not sure exactly when it stopped.

**Screenshots**
![{CC236DAD-F59D-46A0-AC04-4DFBB89A4266}](https://github.com/user-attachments/assets/783c3969-e078-41d0-b8f1-01ccd224ba06)

**Environment:**
VS code version 1.95.3
Code for i version 2.13.6
IBM i V7R4

**Comment by worksofliam** [comment]
Hey @ttognazzini - you should switch to the pre-release version, 2.13.18, restart VS Code, and give that a go.

<img width="714" alt="image" src="https://github.com/user-attachments/assets/25b1dbcf-bed6-4f50-a3c1-336089c6132e">

**Comment by ttognazzini** [comment]
That worked. Thanks Liam. I'll stay on the pre-release version till the next update.
