### ISSUE TITLE
Error: config.privateKeyPath does not exist at given fs path

### ISSUE THREAD

**Issue by kemp76** [codefori/vscode-ibmi#2383]
Hello.
I'm setting up VS Code with a connection to IBM i and am attempting to connect using SSH. I have generated keys and verified the SSH connection using the terminal with command ssh userID@hostName.  I successfully get into -bash-
But when I try to connect from the server pane and click  the 'connect to IBMi' triangle, I get error "config.privateKeyPath does not exist at given fs path". 
I have seen a suggestion to remove the -----BEGIN.... and -----END.... lines from the private key file and re-register it, but this made no difference. 
Maybe I need to make a manual adjustment to the config - how do I locate the config file where config.privateKeyPath is registered?
Any suggestions would be appreciated.
James

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.14.3|
|Visual Studio Code version|1.95.3|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Configuration Editing (configuration-editing): 1.0.0
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
JSON Language Features (json-language-features): 1.0.0
MDOpen for MDCMS 8.5.x (mdopen-8-5): 0.0.35
Merge Conflict (merge-conflict): 1.0.0
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

**_Not connected_** 🔌

**Comment by sebjulliand** [comment]
Hi @kemp76, this is a known bug.
See #2361 for the explanation and a workaround.

**Comment by kemp76** [comment]
Thanks so much for your help - very quick :-)

**Comment by kemp76** [comment]
Just an extra comment - I'm running VS Code on Windows and I had to specify the path to private key using double backslash :
 "privateKeyPath": "C:\\Users\\userID\\.ssh\\id_ed25519"
