### ISSUE TITLE
Action option to force filter refresh

### ISSUE THREAD

**Issue by m-tyler** [codefori/vscode-ibmi#658]
**Is your feature request related to a problem? Please describe.**
Is it feasible to add an option to actions to make it force the filters to be refreshed?  

**Describe the solution you'd like**
There are actions I have that move code around and when they complete I have to remember to refresh the filters.  I would like to set a box on an action I created to tell the tool to auto refresh the filters. 

**Describe alternatives you've considered**
None.

**Additional context**
Minor inconvenience, LOW pty ask.

**Comment by worksofliam** [comment]
Good idea. Issue with refresh is that someones it can be a bit of a performance hit. Let me see what I can do!

**Comment by m-tyler** [comment]
This is why I only want it as an option I have to choose to active.

**Comment by worksofliam** [comment]
This will happen soon.

**Comment by worksofliam** [comment]
Actually, I don't know if my fix is directly related to this.
